.TH "examples/1d_poisson/1d_poisson.cc" 3 "Fri Mar 11 2016" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples/1d_poisson/1d_poisson.cc \- 
.PP
Poisson Equation on a 1D Uniform Staggered Grid with Robin BCs\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
We solve: \[ -\nabla^2 p(x) = s(x), \] for $ x \in \Omega = [a,b] = [0,1] $\&.
.PP
The source term function is defined as: \[ s(x) = -\frac{\lambda^2\exp(\lambda x)}{\exp(\lambda) - 1}, \] where $ \lambda = -1 $ is a real-valued parameter\&.
.PP
We consider Robin's boundary conditions of the form: \[ \alpha p(a) - \beta p'(a) = \omega, \] \[ \alpha p(b) + \beta p'(b) = \epsilon, \] where $ \alpha = -\exp(\lambda) $, $ \beta = \lambda^{-1}(\exp(\lambda) - 1.0) $, $ \omega = -1 $, and $ \epsilon = 0 $\&.
.PP
The analytical solution for this problem is given by: \[ p(x) = \frac{\exp(\lambda x) - 1}{\exp(\lambda) - 1}. \]
.PP
The mimetic counterpart of this equation is: \[ -\breve{\mathbf{L}}^k_x \tilde{p} = \tilde{s}. \]
.PP
Finally, we will solve this problem considering $ k = 2 $\&.
.PP
\fBAuthor:\fP
.RS 4
: Eduardo J\&. Sanchez (ejspeiro) - esanchez at mail dot sdsu dot edu 
.RE
.PP

.PP
Definition in file \fB1d_poisson\&.cc\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Definition at line 263 of file 1d_poisson\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MTK: Mimetic Methods Toolkit from the source code\&.
