.TH "examples/3d_diffusion/3d_diffusion.cc" 3 "Mon Jul 4 2016" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples/3d_diffusion/3d_diffusion.cc \- 
.PP
Diffusion Equation on a 3D Uniform Staggered Grid with Dirichlet BCs\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
We solve: \[ \frac{\partial u}{\partial t} = \nabla^2 u(\mathbf{x}), \] for $ \mathbf{x} \in \Omega = [0,1]^3 $\&.
.PP
We consider autonomous homogeneous Dirichlet boundary conditions\&.
.PP
\fBAuthor:\fP
.RS 4
: Eduardo J\&. Sanchez (ejspeiro) - esanchez at mail dot sdsu dot edu 
.RE
.PP

.PP
Definition in file \fB3d_diffusion\&.cc\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Definition at line 139 of file 3d_diffusion\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MTK: Mimetic Methods Toolkit from the source code\&.
