.TH "examples/divergence_operators_1d_mimetic_test Directory Reference" 3 "Tue Jan 26 2016" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples/divergence_operators_1d_mimetic_test Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdivergence_operators_1d_mimetic_test\&.cc\fP"
.br
.RI "\fITest mimetic qualities of instances of a 1D divergence from the CBSA\&. \fP"
.in -1c
