.TH "include Directory Reference" 3 "Mon Nov 23 2015" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmtk\&.h\fP"
.br
.RI "\fIIncludes the entire API\&. \fP"
.ti -1c
.RI "file \fBmtk_bc_descriptor_1d\&.h\fP"
.br
.RI "\fIEnforces boundary conditions in either the operator or the grid\&. \fP"
.ti -1c
.RI "file \fBmtk_bc_descriptor_2d\&.h\fP"
.br
.RI "\fIImposes boundary conditions in either the operator or the grid\&. \fP"
.ti -1c
.RI "file \fBmtk_blas_adapter\&.h\fP"
.br
.RI "\fIAdapter class for the BLAS API\&. \fP"
.ti -1c
.RI "file \fBmtk_dense_matrix\&.h\fP"
.br
.RI "\fIDefines a common dense matrix, using a 1D array\&. \fP"
.ti -1c
.RI "file \fBmtk_div_1d\&.h\fP"
.br
.RI "\fIIncludes the definition of the class Div1D\&. \fP"
.ti -1c
.RI "file \fBmtk_div_2d\&.h\fP"
.br
.RI "\fIIncludes the definition of the class Div2D\&. \fP"
.ti -1c
.RI "file \fBmtk_enums\&.h\fP"
.br
.RI "\fIConsidered enumeration types in the MTK\&. \fP"
.ti -1c
.RI "file \fBmtk_glpk_adapter\&.h\fP"
.br
.RI "\fIAdapter class for the GLPK API\&. \fP"
.ti -1c
.RI "file \fBmtk_grad_1d\&.h\fP"
.br
.RI "\fIIncludes the definition of the class Grad1D\&. \fP"
.ti -1c
.RI "file \fBmtk_grad_2d\&.h\fP"
.br
.RI "\fIIncludes the definition of the class Grad2D\&. \fP"
.ti -1c
.RI "file \fBmtk_interp_1d\&.h\fP"
.br
.RI "\fIIncludes the definition of the class Interp1D\&. \fP"
.ti -1c
.RI "file \fBmtk_interp_2d\&.h\fP"
.br
.RI "\fIIncludes the definition of the class Interp2D\&. \fP"
.ti -1c
.RI "file \fBmtk_lap_1d\&.h\fP"
.br
.RI "\fIIncludes the definition of the class Lap1D\&. \fP"
.ti -1c
.RI "file \fBmtk_lap_2d\&.h\fP"
.br
.RI "\fIIncludes the implementation of the class Lap2D\&. \fP"
.ti -1c
.RI "file \fBmtk_lapack_adapter\&.h\fP"
.br
.RI "\fIAdapter class for the LAPACK API\&. \fP"
.ti -1c
.RI "file \fBmtk_matrix\&.h\fP"
.br
.RI "\fIDefinition of the representation of a matrix in the MTK\&. \fP"
.ti -1c
.RI "file \fBmtk_quad_1d\&.h\fP"
.br
.RI "\fIIncludes the definition of the class Quad1D\&. \fP"
.ti -1c
.RI "file \fBmtk_roots\&.h\fP"
.br
.RI "\fIFundamental definitions to be used across all classes of the MTK\&. \fP"
.ti -1c
.RI "file \fBmtk_tools\&.h\fP"
.br
.RI "\fITool manager class\&. \fP"
.ti -1c
.RI "file \fBmtk_uni_stg_grid_1d\&.h\fP"
.br
.RI "\fIDefinition of an 1D uniform staggered grid\&. \fP"
.ti -1c
.RI "file \fBmtk_uni_stg_grid_2d\&.h\fP"
.br
.RI "\fIDefinition of an 2D uniform staggered grid\&. \fP"
.in -1c
