.TH "examples/1d_positive_weights Directory Reference" 3 "Fri Mar 11 2016" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples/1d_positive_weights Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB1d_positive_weights\&.cc\fP"
.br
.RI "\fIThe CBS algorithm computes positive-definite weights, for 1D operators\&. \fP"
.in -1c
