.TH "src Directory Reference" 3 "Thu Sep 10 2015" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmtk_blas_adapter\&.cc\fP"
.br
.ti -1c
.RI "file \fBmtk_dense_matrix\&.cc\fP"
.br
.RI "\fIImplements a common dense matrix, using a 1D array\&. \fP"
.ti -1c
.RI "file \fBmtk_div_1d\&.cc\fP"
.br
.RI "\fIImplements the class Div1D\&. \fP"
.ti -1c
.RI "file \fBmtk_glpk_adapter\&.cc\fP"
.br
.RI "\fIAdapter class for the GLPK API\&. \fP"
.ti -1c
.RI "file \fBmtk_grad_1d\&.cc\fP"
.br
.RI "\fIImplements the class Grad1D\&. \fP"
.ti -1c
.RI "file \fBmtk_lap_1d\&.cc\fP"
.br
.RI "\fIIncludes the implementation of the class Lap1D\&. \fP"
.ti -1c
.RI "file \fBmtk_lapack_adapter\&.cc\fP"
.br
.RI "\fIAdapter class for the LAPACK API\&. \fP"
.ti -1c
.RI "file \fBmtk_matrix\&.cc\fP"
.br
.RI "\fIImplementing the representation of a matrix in the MTK\&. \fP"
.ti -1c
.RI "file \fBmtk_tools\&.cc\fP"
.br
.RI "\fIImplements a execution tool manager class\&. \fP"
.ti -1c
.RI "file \fBmtk_uni_stg_grid_1d\&.cc\fP"
.br
.RI "\fIImplementation of an 1D uniform staggered grid\&. \fP"
.in -1c
