.TH "examples/minimalistic_poisson_1d Directory Reference" 3 "Mon Nov 23 2015" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples/minimalistic_poisson_1d Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBminimalistic_poisson_1d\&.cc\fP"
.br
.RI "\fIPoisson Equation on a 1D Uniform Staggered Grid with Robin BCs\&. \fP"
.in -1c
