.TH "examples/curl_2d_angular_velocity Directory Reference" 3 "Tue Jan 26 2016" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples/curl_2d_angular_velocity Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcurl_2d_angular_velocity\&.cc\fP"
.br
.RI "\fICompute the curl of a 2D angular velocity field\&. \fP"
.in -1c
