.TH "examples Directory Reference" 3 "Mon Jul 4 2016" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fB1d_accuracy\fP"
.br
.ti -1c
.RI "directory \fB1d_divergence\fP"
.br
.ti -1c
.RI "directory \fB1d_gradient\fP"
.br
.ti -1c
.RI "directory \fB1d_laplacian\fP"
.br
.ti -1c
.RI "directory \fB1d_mimetic_measure\fP"
.br
.ti -1c
.RI "directory \fB1d_mimetic_threshold\fP"
.br
.ti -1c
.RI "directory \fB1d_poisson\fP"
.br
.ti -1c
.RI "directory \fB1d_poisson_minimal\fP"
.br
.ti -1c
.RI "directory \fB1d_poisson_sensitivity_threshold\fP"
.br
.ti -1c
.RI "directory \fB1d_poisson_supercritical\fP"
.br
.ti -1c
.RI "directory \fB1d_positive_weights\fP"
.br
.ti -1c
.RI "directory \fB2d_angular_velocity\fP"
.br
.ti -1c
.RI "directory \fB2d_poisson\fP"
.br
.ti -1c
.RI "directory \fB3d_diffusion\fP"
.br
.in -1c
