.TH "examples/1d_poisson Directory Reference" 3 "Fri Mar 11 2016" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples/1d_poisson Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB1d_poisson\&.cc\fP"
.br
.RI "\fIPoisson Equation on a 1D Uniform Staggered Grid with Robin BCs\&. \fP"
.in -1c
