.TH "examples/1d_divergence Directory Reference" 3 "Mon Jul 4 2016" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples/1d_divergence Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB1d_divergence\&.cc\fP"
.br
.RI "\fICreates instances of a 1D divergence as computed by the CBS algorithm\&. \fP"
.in -1c
