.TH "tests Directory Reference" 3 "Tue Nov 17 2015" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmtk_blas_adapter_test\&.cc\fP"
.br
.RI "\fITest file for the \fBmtk::BLASAdapter\fP class\&. \fP"
.ti -1c
.RI "file \fBmtk_dense_matrix_test\&.cc\fP"
.br
.RI "\fITest file for the \fBmtk::DenseMatrix\fP class\&. \fP"
.ti -1c
.RI "file \fBmtk_div_1d_test\&.cc\fP"
.br
.RI "\fITesting the mimetic 1D divergence, constructed with the CBS algorithm\&. \fP"
.ti -1c
.RI "file \fBmtk_glpk_adapter_test\&.cc\fP"
.br
.RI "\fITest file for the \fBmtk::GLPKAdapter\fP class\&. \fP"
.ti -1c
.RI "file \fBmtk_grad_1d_test\&.cc\fP"
.br
.RI "\fITesting the mimetic 1D gradient, constructed with the CBS algorithm\&. \fP"
.ti -1c
.RI "file \fBmtk_grad_2d_test\&.cc\fP"
.br
.RI "\fITest file for the \fBmtk::Grad2D\fP class\&. \fP"
.ti -1c
.RI "file \fBmtk_interp_1d_test\&.cc\fP"
.br
.RI "\fITesting the 1D interpolation\&. \fP"
.ti -1c
.RI "file \fBmtk_lap_1d_test\&.cc\fP"
.br
.RI "\fITesting the 1D Laplacian operator\&. \fP"
.ti -1c
.RI "file \fBmtk_lapack_adapter_test\&.cc\fP"
.br
.RI "\fITest file for the \fBmtk::LAPACKAdapter\fP class\&. \fP"
.ti -1c
.RI "file \fBmtk_uni_stg_grid_1d_test\&.cc\fP"
.br
.RI "\fITest file for the \fBmtk::UniStgGrid1D\fP class\&. \fP"
.ti -1c
.RI "file \fBmtk_uni_stg_grid_2d_test\&.cc\fP"
.br
.RI "\fITest file for the \fBmtk::UniStgGrid2D\fP class\&. \fP"
.in -1c
