.TH "examples/1d_mimetic_measure Directory Reference" 3 "Tue Mar 22 2016" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples/1d_mimetic_measure Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB1d_mimetic_measure\&.cc\fP"
.br
.RI "\fICompute the mimetic measure of different mimetic operators\&. \fP"
.in -1c
