.TH "bug" 3 "Tue Mar 22 2016" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bug \- Bug List 

.IP "\fBMember \fBmtk::Matrix::set_num_null\fP (const int &in) noexcept\fP" 1c
-nan assigned on construction time due to num_values_ being 0\&.  
.IP "\fBMember \fBmtk::Matrix::set_num_zero\fP (const int &in) noexcept\fP" 1c
-nan assigned on construction time due to num_values_ being 0\&. 
.PP

