.TH "Roots." 3 "Fri Nov 20 2015" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Roots. \- 
.PP
Fundamental execution parameters and defined types\&.  

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef float \fBmtk::Real\fP"
.br
.RI "\fIUsers can simply change this to build a double- or single-precision MTK\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const float \fBmtk::kZero\fP {0\&.0f}"
.br
.RI "\fIMTK's zero defined according to selective compilation\&. \fP"
.ti -1c
.RI "const float \fBmtk::kOne\fP {1\&.0f}"
.br
.RI "\fIMTK's one defined according to selective compilation\&. \fP"
.ti -1c
.RI "const float \fBmtk::kTwo\fP {2\&.0f}"
.br
.RI "\fIMTK's two defined according to selective compilation\&. \fP"
.ti -1c
.RI "const float \fBmtk::kDefaultTolerance\fP {1e-7f}"
.br
.RI "\fIConsidered tolerance for comparisons in numerical methods\&. \fP"
.ti -1c
.RI "const int \fBmtk::kDefaultOrderAccuracy\fP {2}"
.br
.RI "\fIDefault order of accuracy for mimetic operators\&. \fP"
.ti -1c
.RI "const float \fBmtk::kDefaultMimeticThreshold\fP {1e-6f}"
.br
.RI "\fIDefault tolerance for higher-order mimetic operators\&. \fP"
.ti -1c
.RI "const int \fBmtk::kCriticalOrderAccuracyDiv\fP {8}"
.br
.RI "\fIAt this order (and higher) we must use the CBSA to construct\&. \fP"
.ti -1c
.RI "const int \fBmtk::kCriticalOrderAccuracyGrad\fP {10}"
.br
.RI "\fIAt this order (and higher) we must use the CBSA to construct\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Fundamental execution parameters and defined types\&. 
.SH "Typedef Documentation"
.PP 
.SS "\fBmtk::Real\fP"

.PP
Definition at line 83 of file mtk_roots\&.h\&.
.SH "Variable Documentation"
.PP 
.SS "mtk::kCriticalOrderAccuracyDiv {8}"

.PP
Definition at line 167 of file mtk_roots\&.h\&.
.SS "mtk::kCriticalOrderAccuracyGrad {10}"

.PP
Definition at line 176 of file mtk_roots\&.h\&.
.SS "mtk::kDefaultMimeticThreshold {1e-6f}"

.PP
\fBWarning:\fP
.RS 4
Declared as double if MTK_PRECISION_DOUBLE is defined\&. 
.RE
.PP

.PP
Definition at line 157 of file mtk_roots\&.h\&.
.SS "mtk::kDefaultOrderAccuracy {2}"

.PP
\fBWarning:\fP
.RS 4
Declared as double if MTK_PRECISION_DOUBLE is defined\&. 
.RE
.PP

.PP
Definition at line 143 of file mtk_roots\&.h\&.
.SS "mtk::kDefaultTolerance {1e-7f}"

.PP
Definition at line 131 of file mtk_roots\&.h\&.
.SS "mtk::kOne {1\&.0f}"

.PP
\fBWarning:\fP
.RS 4
Declared as double if MTK_PRECISION_DOUBLE is defined\&. 
.RE
.PP

.PP
Definition at line 117 of file mtk_roots\&.h\&.
.SS "mtk::kTwo {2\&.0f}"

.PP
\fBWarning:\fP
.RS 4
Declared as double if MTK_PRECISION_DOUBLE is defined\&. 
.RE
.PP

.PP
Definition at line 118 of file mtk_roots\&.h\&.
.SS "mtk::kZero {0\&.0f}"

.PP
\fBWarning:\fP
.RS 4
Declared as double if MTK_PRECISION_DOUBLE is defined\&. 
.RE
.PP

.PP
Definition at line 116 of file mtk_roots\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MTK: Mimetic Methods Toolkit from the source code\&.
