.TH "Execution tools." 3 "Fri Mar 11 2016" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Execution tools. \- 
.PP
Tools to ensure execution correctness\&.  

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmtk::Tools\fP"
.br
.RI "\fITool manager class\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Tools to ensure execution correctness\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for MTK: Mimetic Methods Toolkit from the source code\&.
