.TH "Data structures." 3 "Fri Mar 11 2016" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Data structures. \- 
.PP
Fundamental data structures\&.  

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmtk::DenseMatrix\fP"
.br
.RI "\fIDefines a common dense matrix, using a 1D array\&. \fP"
.ti -1c
.RI "class \fBmtk::Matrix\fP"
.br
.RI "\fIDefinition of the representation of a matrix in the MTK\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Fundamental data structures\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for MTK: Mimetic Methods Toolkit from the source code\&.
