.TH "Numerical methods." 3 "Mon Feb 1 2016" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Numerical methods. \- 
.PP
Adapter classes and auxiliary numerical methods\&.  

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmtk::BLASAdapter\fP"
.br
.RI "\fIAdapter class for the BLAS API\&. \fP"
.ti -1c
.RI "class \fBmtk::GLPKAdapter\fP"
.br
.RI "\fIAdapter class for the GLPK API\&. \fP"
.ti -1c
.RI "class \fBmtk::LAPACKAdapter\fP"
.br
.RI "\fIAdapter class for the LAPACK API\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Adapter classes and auxiliary numerical methods\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for MTK: Mimetic Methods Toolkit from the source code\&.
