.TH "Grids." 3 "Sun Sep 13 2015" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Grids. \- 
.PP
Uniform rectangular staggered grids\&.  

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmtk::UniStgGrid1D\fP"
.br
.RI "\fIUniform 1D Staggered Grid\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Uniform rectangular staggered grids\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for MTK: Mimetic Methods Toolkit from the source code\&.
