.TH "Mimetic operators." 3 "Mon Nov 23 2015" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mimetic operators. \- 
.PP
Mimetic operators\&.  

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmtk::BCDescriptor1D\fP"
.br
.RI "\fIEnforces boundary conditions in either the operator or the grid\&. \fP"
.ti -1c
.RI "class \fBmtk::BCDescriptor2D\fP"
.br
.RI "\fIEnforces boundary conditions in either the operator or the grid\&. \fP"
.ti -1c
.RI "class \fBmtk::Div1D\fP"
.br
.RI "\fIImplements a 1D mimetic divergence operator\&. \fP"
.ti -1c
.RI "class \fBmtk::Div2D\fP"
.br
.RI "\fIImplements a 2D mimetic divergence operator\&. \fP"
.ti -1c
.RI "class \fBmtk::Grad1D\fP"
.br
.RI "\fIImplements a 1D mimetic gradient operator\&. \fP"
.ti -1c
.RI "class \fBmtk::Grad2D\fP"
.br
.RI "\fIImplements a 2D mimetic gradient operator\&. \fP"
.ti -1c
.RI "class \fBmtk::Interp1D\fP"
.br
.RI "\fIImplements a 1D interpolation operator\&. \fP"
.ti -1c
.RI "class \fBmtk::Interp2D\fP"
.br
.RI "\fIImplements a 2D interpolation operator\&. \fP"
.ti -1c
.RI "class \fBmtk::Lap1D\fP"
.br
.RI "\fIImplements a 1D mimetic Laplacian operator\&. \fP"
.ti -1c
.RI "class \fBmtk::Lap2D\fP"
.br
.RI "\fIImplements a 2D mimetic Laplacian operator\&. \fP"
.ti -1c
.RI "class \fBmtk::Quad1D\fP"
.br
.RI "\fIImplements a 1D mimetic quadrature\&. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef Real(* \fBmtk::CoefficientFunction2D\fP )(const Real &, const Real &)"
.br
.RI "\fIA function of a BC coefficient evaluated on a 2D domain\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Mimetic operators\&. 
.SH "Typedef Documentation"
.PP 
.SS "mtk::CoefficientFunction2D"

.PP
Definition at line 92 of file mtk_bc_descriptor_2d\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MTK: Mimetic Methods Toolkit from the source code\&.
