.TH "Mimetic operators." 3 "Tue Nov 17 2015" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mimetic operators. \- 
.PP
Mimetic operators\&.  

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmtk::Div1D\fP"
.br
.RI "\fIImplements a 1D mimetic divergence operator\&. \fP"
.ti -1c
.RI "class \fBmtk::Grad1D\fP"
.br
.RI "\fIImplements a 1D mimetic gradient operator\&. \fP"
.ti -1c
.RI "class \fBmtk::Interp1D\fP"
.br
.RI "\fIImplements a 1D interpolation operator\&. \fP"
.ti -1c
.RI "class \fBmtk::Lap1D\fP"
.br
.RI "\fIImplements a 1D mimetic Laplacian operator\&. \fP"
.ti -1c
.RI "class \fBmtk::Quad1D\fP"
.br
.RI "\fIImplements a 1D mimetic quadrature\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Mimetic operators\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for MTK: Mimetic Methods Toolkit from the source code\&.
