.TH "examples/curl_2d_angular_velocity/curl_2d_angular_velocity.cc" 3 "Tue Dec 15 2015" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples/curl_2d_angular_velocity/curl_2d_angular_velocity.cc \- 
Compute the curl of a 2D angular velocity field\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
We compute the curl of: \[ \mathbf{v}(x,y) = -y\hat{\mathbf{i}} + x\hat{\mathbf{j}}. \]
.PP
\fBAuthor:\fP
.RS 4
: Eduardo J\&. Sanchez (ejspeiro) - esanchez at mail dot sdsu dot edu 
.RE
.PP

.PP
Definition in file \fBcurl_2d_angular_velocity\&.cc\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Definition at line 106 of file curl_2d_angular_velocity\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MTK: Mimetic Methods Toolkit from the source code\&.
