.TH "include/mtk.h" 3 "Mon Feb 1 2016" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/mtk.h \- 
.PP
Includes the entire API\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'mtk_roots\&.h'\fP
.br
\fC#include 'mtk_enums\&.h'\fP
.br
\fC#include 'mtk_tools\&.h'\fP
.br
\fC#include 'mtk_matrix\&.h'\fP
.br
\fC#include 'mtk_dense_matrix\&.h'\fP
.br
\fC#include 'mtk_blas_adapter\&.h'\fP
.br
\fC#include 'mtk_lapack_adapter\&.h'\fP
.br
\fC#include 'mtk_glpk_adapter\&.h'\fP
.br
\fC#include 'mtk_uni_stg_grid_1d\&.h'\fP
.br
\fC#include 'mtk_uni_stg_grid_2d\&.h'\fP
.br
\fC#include 'mtk_uni_stg_grid_3d\&.h'\fP
.br
\fC#include 'mtk_grad_1d\&.h'\fP
.br
\fC#include 'mtk_div_1d\&.h'\fP
.br
\fC#include 'mtk_lap_1d\&.h'\fP
.br
\fC#include 'mtk_robin_bc_descriptor_1d\&.h'\fP
.br
\fC#include 'mtk_quad_1d\&.h'\fP
.br
\fC#include 'mtk_interp_1d\&.h'\fP
.br
\fC#include 'mtk_grad_2d\&.h'\fP
.br
\fC#include 'mtk_div_2d\&.h'\fP
.br
\fC#include 'mtk_curl_2d\&.h'\fP
.br
\fC#include 'mtk_lap_2d\&.h'\fP
.br
\fC#include 'mtk_robin_bc_descriptor_2d\&.h'\fP
.br
\fC#include 'mtk_grad_3d\&.h'\fP
.br
\fC#include 'mtk_div_3d\&.h'\fP
.br
\fC#include 'mtk_lap_3d\&.h'\fP
.br
\fC#include 'mtk_robin_bc_descriptor_3d\&.h'\fP
.br

.SH "Detailed Description"
.PP 
This file contains every required header file, thus containing the entire API\&. In this way, client codes only have to instruct #include 'mtk\&.h'\&.
.PP
\fBWarning:\fP
.RS 4
It is extremely important that the headers are added to this file in a specific order; that is, considering the dependence between the classes these contain\&.
.RE
.PP
\fBAuthor:\fP
.RS 4
: Eduardo J\&. Sanchez (ejspeiro) - esanchez at mail dot sdsu dot edu 
.RE
.PP

.PP
Definition in file \fBmtk\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MTK: Mimetic Methods Toolkit from the source code\&.
