.TH "mtk::BCDesc2D" 3 "Tue Nov 17 2015" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mtk::BCDesc2D \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mtk_bc_desc_2d\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBImposeOnOperatorMatrix\fP (const \fBDenseMatrix\fP &matrix, \fBReal\fP(*west)(int ii, int jj), \fBReal\fP(*east)(int ii, int jj), \fBReal\fP(*south)(int ii, int jj), \fBReal\fP(*north)(int ii, int jj))"
.br
.RI "\fIEnforces the condition on the operator represented as matrix\&. \fP"
.ti -1c
.RI "static void \fBImposeOnGrid\fP (const \fBUniStgGrid2D\fP &grid, \fBReal\fP(*west)(\fBReal\fP xx, \fBReal\fP yy), \fBReal\fP(*east)(\fBReal\fP xx, \fBReal\fP yy), \fBReal\fP(*south)(\fBReal\fP xx, \fBReal\fP yy), \fBReal\fP(*north)(\fBReal\fP xx, \fBReal\fP yy))"
.br
.RI "\fIEnforces the condition on the grid\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 66 of file mtk_bc_desc_2d\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void mtk::BCDesc2D::ImposeOnGrid (const \fBUniStgGrid2D\fP &grid, \fBReal\fP(*)(\fBReal\fP xx, \fBReal\fP yy)west, \fBReal\fP(*)(\fBReal\fP xx, \fBReal\fP yy)east, \fBReal\fP(*)(\fBReal\fP xx, \fBReal\fP yy)south, \fBReal\fP(*)(\fBReal\fP xx, \fBReal\fP yy)north)\fC [static]\fP"

.PP
\fBParameters:\fP
.RS 4
\fImatrix\fP Input operator\&. 
.br
\fIwest\fP Pointer to function returning west coefficient at (xx,yy)\&. 
.br
\fIeast\fP Pointer to function returning east coefficient at (xx,yy)\&. 
.br
\fIsouth\fP Pointer to function returning south coefficient at (xx,yy)\&. 
.br
\fInorth\fP Pointer to function returning north coefficient at (xx,yy)\&. 
.RE
.PP

.PP
Definition at line 78 of file mtk_bc_desc_2d\&.cc\&.
.SS "void mtk::BCDesc2D::ImposeOnOperatorMatrix (const \fBDenseMatrix\fP &matrix, \fBmtk::Real\fP(*)(int ii, int jj)west, \fBmtk::Real\fP(*)(int ii, int jj)east, \fBmtk::Real\fP(*)(int ii, int jj)south, \fBmtk::Real\fP(*)(int ii, int jj)north)\fC [static]\fP"

.PP
\fBParameters:\fP
.RS 4
\fImatrix\fP Input operator\&. 
.br
\fIwest\fP Pointer to function returning west coefficient at (ii,jj)\&. 
.br
\fIeast\fP Pointer to function returning east coefficient at (ii,jj)\&. 
.br
\fIsouth\fP Pointer to function returning south coefficient at (ii,jj)\&. 
.br
\fInorth\fP Pointer to function returning north coefficient at (ii,jj)\&. 
.RE
.PP

.PP
Definition at line 61 of file mtk_bc_desc_2d\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MTK: Mimetic Methods Toolkit from the source code\&.
