.TH "src/mtk_lap_1d.cc" 3 "Mon Nov 23 2015" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mtk_lap_1d.cc \- 
.PP
Includes the implementation of the class Lap1D\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <cstdlib>\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include 'mtk_roots\&.h'\fP
.br
\fC#include 'mtk_tools\&.h'\fP
.br
\fC#include 'mtk_blas_adapter\&.h'\fP
.br
\fC#include 'mtk_grad_1d\&.h'\fP
.br
\fC#include 'mtk_div_1d\&.h'\fP
.br
\fC#include 'mtk_lap_1d\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmtk\fP"
.br
.RI "\fIMimetic Methods Toolkit namespace\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBmtk::operator<<\fP (std::ostream &stream, \fBmtk::Lap1D\fP &in)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class implements a 1D Laplacian operator, constructed using the Castillo-Blomgren-Sanchez (CBS) Algorithm (CBSA)\&.
.PP
\fBAuthor:\fP
.RS 4
: Eduardo J\&. Sanchez (ejspeiro) - esanchez at mail dot sdsu dot edu 
.RE
.PP

.PP
Definition in file \fBmtk_lap_1d\&.cc\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MTK: Mimetic Methods Toolkit from the source code\&.
