.TH "mtk::BLASAdapter" 3 "Mon Dec 14 2015" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mtk::BLASAdapter \- 
.PP
Adapter class for the BLAS API\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mtk_blas_adapter\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBReal\fP \fBRealNRM2\fP (\fBReal\fP *in, int &in_length)"
.br
.RI "\fICompute the $ ||\mathbf{x}||_2 $ of given array $ \mathbf{x} $\&. \fP"
.ti -1c
.RI "static void \fBRealAXPY\fP (\fBReal\fP alpha, \fBReal\fP *xx, \fBReal\fP *yy, int &in_length)"
.br
.RI "\fIReal-Arithmetic Scalar-Vector plus a Vector\&. \fP"
.ti -1c
.RI "static \fBReal\fP \fBRelNorm2Error\fP (\fBReal\fP *computed, \fBReal\fP *known, int length)"
.br
.RI "\fIComputes the relative norm-2 of the error\&. \fP"
.ti -1c
.RI "static void \fBRealDenseMV\fP (\fBReal\fP &alpha, \fBDenseMatrix\fP &aa, \fBReal\fP *xx, \fBReal\fP &beta, \fBReal\fP *yy)"
.br
.RI "\fIReal-Arithmetic General (Dense matrices) Matrix-Vector Multiplier\&. \fP"
.ti -1c
.RI "static \fBDenseMatrix\fP \fBRealDenseMM\fP (\fBDenseMatrix\fP &aa, \fBDenseMatrix\fP &bb)"
.br
.RI "\fIReal-Arithmetic General (Dense matrices) Matrix-Matrix multiplier\&. \fP"
.ti -1c
.RI "static \fBDenseMatrix\fP \fBRealDenseSM\fP (\fBReal\fP alpha, \fBDenseMatrix\fP &aa)"
.br
.RI "\fIReal-Arithmetic General (Dense matrices) Scalar-Matrix multiplier\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This class contains a collection of static classes, that posses direct access to the underlying structure of the matrices, thus allowing programmers to exploit some of the numerical methods implemented in the BLAS\&.
.PP
The \fBBLAS (Basic Linear Algebra Subprograms)\fP are routines that provide standard building blocks for performing basic vector and matrix operations\&. The Level 1 BLAS perform scalar, vector and vector-vector operations, the Level 2 BLAS perform matrix-vector operations, and the Level 3 BLAS perform matrix-matrix operations\&.
.PP
\fBSee also:\fP
.RS 4
http://www.netlib.org/blas/ 
.RE
.PP

.PP
Definition at line 96 of file mtk_blas_adapter\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void mtk::BLASAdapter::RealAXPY (\fBmtk::Real\fPalpha, \fBmtk::Real\fP *xx, \fBmtk::Real\fP *yy, int &in_length)\fC [static]\fP"
Performs
.PP
\[ \mathbf{y} := \alpha\mathbf{A}mathbf{x} + \mathbf{y} \].PP
\fBParameters:\fP
.RS 4
\fIalpha\fP Scalar of the first array\&. 
.br
\fIxx\fP First array\&. 
.br
\fIyy\fP Second array\&. 
.br
\fIin_length\fP Lengths of the given arrays\&.
.RE
.PP
\fBReturns:\fP
.RS 4
Norm-2 of the given array\&. 
.RE
.PP

.PP
Definition at line 339 of file mtk_blas_adapter\&.cc\&.
.SS "\fBmtk::DenseMatrix\fP mtk::BLASAdapter::RealDenseMM (\fBmtk::DenseMatrix\fP &aa, \fBmtk::DenseMatrix\fP &bb)\fC [static]\fP"
Performs:
.PP
\[ \mathbf{C} := \mathbf{A}\mathbf{B} \].PP
\fBParameters:\fP
.RS 4
\fIaa\fP First matrix\&. 
.br
\fIbb\fP Second matrix\&.
.RE
.PP
\fBSee also:\fP
.RS 4
http://ejspeiro.github.io/Netlib-and-CPP/ 
.RE
.PP

.IP "1." 4
Make sure input matrices are row-major ordered\&.
.IP "2." 4
Setup the problem\&.
.IP "3." 4
Perform multiplication\&. 
.PP

.PP
Definition at line 409 of file mtk_blas_adapter\&.cc\&.
.SS "void mtk::BLASAdapter::RealDenseMV (\fBmtk::Real\fP &alpha, \fBmtk::DenseMatrix\fP &aa, \fBmtk::Real\fP *xx, \fBmtk::Real\fP &beta, \fBmtk::Real\fP *yy)\fC [static]\fP"
Performs
.PP
\[ \mathbf{y} := \alpha\mathbf{A}\mathbf{x} + \beta\mathbf{y} \].PP
\fBParameters:\fP
.RS 4
\fIalpha\fP First scalar\&. 
.br
\fIaa\fP Given matrix\&. 
.br
\fIxx\fP First vector\&. 
.br
\fIbeta\fP Second scalar\&. 
.br
\fIyy\fP Second vector (output)\&.
.RE
.PP
\fBSee also:\fP
.RS 4
http://ejspeiro.github.io/Netlib-and-CPP/ 
.RE
.PP

.PP
Definition at line 378 of file mtk_blas_adapter\&.cc\&.
.SS "\fBmtk::DenseMatrix\fP mtk::BLASAdapter::RealDenseSM (\fBmtk::Real\fPalpha, \fBmtk::DenseMatrix\fP &aa)\fC [static]\fP"
Performs:
.PP
\[ \mathbf{B} := \alpha\mathbf{A} \].PP
\fBParameters:\fP
.RS 4
\fIalpha\fP Input scalar\&. 
.br
\fIaa\fP Input matrix\&.
.RE
.PP
\fBSee also:\fP
.RS 4
http://ejspeiro.github.io/Netlib-and-CPP/ 
.RE
.PP

.IP "1." 4
Make sure input matrices are row-major ordered\&.
.IP "2." 4
Setup the problem\&.
.IP "3." 4
Perform multiplication\&. 
.PP

.PP
Definition at line 466 of file mtk_blas_adapter\&.cc\&.
.SS "\fBmtk::Real\fP mtk::BLASAdapter::RealNRM2 (\fBReal\fP *in, int &in_length)\fC [static]\fP"

.PP
\fBParameters:\fP
.RS 4
\fIin\fP Input array\&. 
.br
\fIin_length\fP Length of the array\&.
.RE
.PP
\fBReturns:\fP
.RS 4
Norm-2 of the given array\&. 
.RE
.PP

.PP
Definition at line 324 of file mtk_blas_adapter\&.cc\&.
.SS "\fBmtk::Real\fP mtk::BLASAdapter::RelNorm2Error (\fBmtk::Real\fP *computed, \fBmtk::Real\fP *known, intlength)\fC [static]\fP"
We compute
.PP
\[ \frac{||\mathbf{\tilde{x}} - \mathbf{x}||_2}{||\mathbf{x}||_2}. \].PP
\fBParameters:\fP
.RS 4
\fIknown\fP Array containing the computed solution\&. 
.br
\fIcomputed\fP Array containing the known solution (ref\&. solution)\&.
.RE
.PP
\fBReturns:\fP
.RS 4
Relative norm-2 of the error, aka, the difference between the arrays\&. 
.RE
.PP

.PP
Definition at line 358 of file mtk_blas_adapter\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MTK: Mimetic Methods Toolkit from the source code\&.
