.TH "include/mtk_bc_descriptor_2d.h" 3 "Thu Nov 19 2015" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/mtk_bc_descriptor_2d.h \- 
.PP
Imposes boundary conditions in either the operator or the grid\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'mtk_roots\&.h'\fP
.br
\fC#include 'mtk_dense_matrix\&.h'\fP
.br
\fC#include 'mtk_uni_stg_grid_2d\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmtk::BCDescriptor2D\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmtk\fP"
.br
.RI "\fIMimetic Methods Toolkit namespace\&. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef Real(* \fBmtk::CoefficientFunction2D\fP )(const Real &, const Real &)"
.br
.RI "\fIA function of a BC coefficient evaluated on a 2D domain\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This class presents an interface for the user to specify boundary conditions on 2D mimetic operators and the grids they are acting on\&.
.PP
\fBDef\&.\fP Let $ f $ be any scalar or vector field defined over a domain $ \Omega $\&. We can specify any linear combination of $ f $ and its $ n $ derivatives to fulfill a condition, which we define as a \fBboundary condition\fP:
.PP
\[ \forall \mathbf{x} \in \partial\Omega: \sum_{i = 0}^{n} c_i(\mathbf{x})\frac{\partial^i f}{\partial x^i}(\mathbf{x}) = \beta(\mathbf{x}). \].PP
This class receives information about the highest-order of differentiation, $ n $, all possible coefficient functions, $ c_i(\mathbf{x}) $ for any subset of the boundary (south, north, west and east), and each condition for any subset of the boundary, and takes care of assigning them to both, the differentiation matrices and the grids\&.
.PP
\fBAuthor:\fP
.RS 4
: Eduardo J\&. Sanchez (ejspeiro) - esanchez at mail dot sdsu dot edu 
.RE
.PP

.PP
Definition in file \fBmtk_bc_descriptor_2d\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MTK: Mimetic Methods Toolkit from the source code\&.
