.TH "tests/mtk_lap_1d_test/mtk_lap_1d_test.cc" 3 "Mon Jul 4 2016" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests/mtk_lap_1d_test/mtk_lap_1d_test.cc \- 
.PP
Testing the 1D Laplacian operator\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'mtk\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBTestDefaultConstructorFactoryMethodDefault\fP ()"
.br
.ti -1c
.RI "void \fBTestDefaultConstructorFactoryMethodFourthOrder\fP ()"
.br
.ti -1c
.RI "void \fBTestDefaultConstructorFactoryMethodSixthOrder\fP ()"
.br
.ti -1c
.RI "void \fBTestDefaultConstructorFactoryMethodEightOrderDefThreshold\fP ()"
.br
.ti -1c
.RI "void \fBTestDefaultConstructorFactoryMethodTenthOrderDefThreshold\fP ()"
.br
.ti -1c
.RI "void \fBTestDefaultConstructorFactoryMethodTwelfthOrderDefThreshold\fP ()"
.br
.ti -1c
.RI "void \fBTestReturnAsDenseMatrix\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
: Eduardo J\&. Sanchez (ejspeiro) - esanchez at mail dot sdsu dot edu
.PP
: Johnny Corbino - jcorbino at mail dot sdsu dot edu 
.RE
.PP

.PP
Definition in file \fBmtk_lap_1d_test\&.cc\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Definition at line 176 of file mtk_lap_1d_test\&.cc\&.
.SS "void TestDefaultConstructorFactoryMethodDefault ()"

.PP
Definition at line 60 of file mtk_lap_1d_test\&.cc\&.
.SS "void TestDefaultConstructorFactoryMethodEightOrderDefThreshold ()"

.PP
Definition at line 108 of file mtk_lap_1d_test\&.cc\&.
.SS "void TestDefaultConstructorFactoryMethodFourthOrder ()"

.PP
Definition at line 76 of file mtk_lap_1d_test\&.cc\&.
.SS "void TestDefaultConstructorFactoryMethodSixthOrder ()"

.PP
Definition at line 92 of file mtk_lap_1d_test\&.cc\&.
.SS "void TestDefaultConstructorFactoryMethodTenthOrderDefThreshold ()"

.PP
Definition at line 123 of file mtk_lap_1d_test\&.cc\&.
.SS "void TestDefaultConstructorFactoryMethodTwelfthOrderDefThreshold ()"

.PP
Definition at line 138 of file mtk_lap_1d_test\&.cc\&.
.SS "void TestReturnAsDenseMatrix ()"

.PP
Definition at line 153 of file mtk_lap_1d_test\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MTK: Mimetic Methods Toolkit from the source code\&.
