.TH "src/mtk_blas_adapter.cc" 3 "Thu Sep 10 2015" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mtk_blas_adapter.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'mtk_roots\&.h'\fP
.br
\fC#include 'mtk_tools\&.h'\fP
.br
\fC#include 'mtk_blas_adapter\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBmtk\fP"
.br
.RI "\fIMimetic Methods Toolkit namespace\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "float \fBmtk::snrm2_\fP (int *n, Real *x, int *incx)"
.br
.ti -1c
.RI "void \fBmtk::sgemv_\fP (char *trans, int *m, int *n, Real *alpha, Real *a, int *lda, Real *x, int *incx, Real *beta, Real *y, int *incy)"
.br
.ti -1c
.RI "void \fBmtk::sgemm_\fP (char *transa, char *transb, int *m, int *n, int *k, Real *alpha, Real *a, int *lda, Real *b, aamm int *ldb, Real *beta, Real *c, int *ldc)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MTK: Mimetic Methods Toolkit from the source code\&.
