.TH "mtk::OperatorApplicator" 3 "Mon Jul 4 2016" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mtk::OperatorApplicator \- 
.PP
Controls the process of applying a mimetic operator to a grid\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mtk_operator_applicator\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBApplyDenseMatrixGradientOn1DGrid\fP (\fBDenseMatrix\fP &grad, \fBUniStgGrid1D\fP &grid, \fBUniStgGrid1D\fP &out)"
.br
.RI "\fIApplies a gradient operator encoded as a dense matrix to a 1D grid\&. \fP"
.ti -1c
.RI "static void \fBApplyDenseMatrixDivergenceOn1DGrid\fP (\fBDenseMatrix\fP &div, \fBUniStgGrid1D\fP &grid, \fBUniStgGrid1D\fP &out)"
.br
.RI "\fIApplies a divergence operator encoded as a dense matrix to a 1D grid\&. \fP"
.ti -1c
.RI "static void \fBApplyDenseMatrixLaplacianOn1DGrid\fP (\fBDenseMatrix\fP &lap, \fBUniStgGrid1D\fP &grid, \fBUniStgGrid1D\fP &out)"
.br
.RI "\fIApplies a Laplacian operator encoded as a dense matrix to a 1D grid\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 79 of file mtk_operator_applicator\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void mtk::OperatorApplicator::ApplyDenseMatrixDivergenceOn1DGrid (\fBDenseMatrix\fP &div, \fBUniStgGrid1D\fP &grid, \fBUniStgGrid1D\fP &out)\fC [static]\fP"

.PP
\fBParameters:\fP
.RS 4
\fIdiv\fP Divergence operator\&. 
.br
\fIgrid\fP 1D grid\&. 
.br
\fIout\fP Resulting 1D grid\&. 
.RE
.PP

.PP
Definition at line 88 of file mtk_operator_applicator\&.cc\&.
.SS "void mtk::OperatorApplicator::ApplyDenseMatrixGradientOn1DGrid (\fBDenseMatrix\fP &grad, \fBUniStgGrid1D\fP &grid, \fBUniStgGrid1D\fP &out)\fC [static]\fP"

.PP
\fBParameters:\fP
.RS 4
\fIgrad\fP Gradient operator\&. 
.br
\fIgrid\fP 1D grid\&. 
.br
\fIout\fP Resulting 1D grid\&. 
.RE
.PP

.PP
Definition at line 64 of file mtk_operator_applicator\&.cc\&.
.SS "void mtk::OperatorApplicator::ApplyDenseMatrixLaplacianOn1DGrid (\fBDenseMatrix\fP &lap, \fBUniStgGrid1D\fP &grid, \fBUniStgGrid1D\fP &out)\fC [static]\fP"

.PP
\fBParameters:\fP
.RS 4
\fIlap\fP Laplacian operator\&. 
.br
\fIgrid\fP 1D grid\&. 
.br
\fIout\fP Resulting 1D grid\&. 
.RE
.PP

.PP
Definition at line 113 of file mtk_operator_applicator\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MTK: Mimetic Methods Toolkit from the source code\&.
