.TH "include/mtk_bc_descriptor_2d.h" 3 "Tue Nov 24 2015" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/mtk_bc_descriptor_2d.h \- 
.PP
Imposes mimetic boundary conditions on the operators and on the grids\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'mtk_roots\&.h'\fP
.br
\fC#include 'mtk_dense_matrix\&.h'\fP
.br
\fC#include 'mtk_uni_stg_grid_2d\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmtk::BCDescriptor2D\fP"
.br
.RI "\fIEnforces boundary conditions in either the operator or the grid\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmtk\fP"
.br
.RI "\fIMimetic Methods Toolkit namespace\&. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef Real(* \fBmtk::CoefficientFunction2D\fP )(const Real &, const Real &)"
.br
.RI "\fIA function of a BC coefficient evaluated on a 2D domain\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This class presents an interface for the user to specify mimetic boundary conditions on 2D mimetic operators and the grids they are acting on\&.
.PP
\fBDef\&.\fP Let $ f(t,\mathbf{x}) $ be any scalar field defined over a domain $ \Omega $ on a given time snapshot $ t \in [t_0,t_n] $\&. Any linear combination of $ f $ and its $ m $ derivatives fulfilling a condition $ \beta(t,\mathbf{x}) $ is defined as a \fBboundary condition\fP:
.PP
\[ \forall t \in [t_0,t_n]\; \forall \mathbf{x} \in \partial\Omega: \sum_{i = 0}^{m} c_i(\mathbf{x},t) <\hat{\mathbf{n}}, \frac{\partial^i f}{\partial \mathbf{x}^i}(\mathbf{x},t)> = \beta(\mathbf{x},t). \].PP
This class receives information about all possible coefficient functions, $ c_i(\mathbf{x},t) $ for any subset of the boundary (south, north, west and east), and every condition $\beta(\mathbf{x},t) $ for any subset of the boundary, and takes care of assigning them to both the differentiation matrices and the grids\&. The highest order of differentiation is computed based on how many coefficients have been given at run-time\&.
.PP
\fBWarning:\fP
.RS 4
For now, we only support orders as high as 1\&.
.RE
.PP
\fBSee also:\fP
.RS 4
http://mathworld.wolfram.com/NormalVector.html
.RE
.PP
\fBAuthor:\fP
.RS 4
: Eduardo J\&. Sanchez (ejspeiro) - esanchez at mail dot sdsu dot edu 
.RE
.PP

.PP
Definition in file \fBmtk_bc_descriptor_2d\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MTK: Mimetic Methods Toolkit from the source code\&.
