.TH "mtk::Lap3D" 3 "Tue Dec 15 2015" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mtk::Lap3D \- 
.PP
Implements a 3D mimetic Laplacian operator\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mtk_lap_3d\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUniStgGrid3D\fP \fBoperator*\fP (const \fBUniStgGrid3D\fP &grid) const "
.br
.RI "\fIOperator application operator on a grid\&. \fP"
.ti -1c
.RI "\fBLap3D\fP ()"
.br
.RI "\fIDefault constructor\&. \fP"
.ti -1c
.RI "\fBLap3D\fP (const \fBLap3D\fP &lap)"
.br
.RI "\fICopy constructor\&. \fP"
.ti -1c
.RI "\fB~Lap3D\fP ()"
.br
.RI "\fIDestructor\&. \fP"
.ti -1c
.RI "bool \fBConstructLap3D\fP (const \fBUniStgGrid3D\fP &grid, int order_accuracy=\fBkDefaultOrderAccuracy\fP, \fBReal\fP mimetic_threshold=\fBkDefaultMimeticThreshold\fP)"
.br
.RI "\fIFactory method implementing the CBS Algorithm to build operator\&. \fP"
.ti -1c
.RI "\fBDenseMatrix\fP \fBReturnAsDenseMatrix\fP () const "
.br
.RI "\fIReturn the operator as a dense matrix\&. \fP"
.ti -1c
.RI "\fBReal\fP * \fBdata\fP () const "
.br
.RI "\fIReturn the operator as a dense array\&. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBDenseMatrix\fP \fBlaplacian_\fP"
.br
.RI "\fIActual operator\&. \fP"
.ti -1c
.RI "int \fBorder_accuracy_\fP"
.br
.RI "\fIOrder of accuracy\&. \fP"
.ti -1c
.RI "\fBReal\fP \fBmimetic_threshold_\fP"
.br
.RI "\fIMimetic Threshold\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This class implements a 3D Laplacian operator, constructed using the Castillo-Blomgren-Sanchez (CBS) Algorithm (CBSA)\&. 
.PP
Definition at line 76 of file mtk_lap_3d\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "mtk::Lap3D::Lap3D ()"

.PP
Definition at line 76 of file mtk_lap_3d\&.cc\&.
.SS "mtk::Lap3D::Lap3D (const \fBLap3D\fP &lap)"

.PP
\fBParameters:\fP
.RS 4
\fIlap\fP Given Laplacian\&. 
.RE
.PP

.PP
Definition at line 78 of file mtk_lap_3d\&.cc\&.
.SS "mtk::Lap3D::~Lap3D ()"

.PP
Definition at line 82 of file mtk_lap_3d\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "bool mtk::Lap3D::ConstructLap3D (const \fBUniStgGrid3D\fP &grid, intorder_accuracy = \fC\fBkDefaultOrderAccuracy\fP\fP, \fBmtk::Real\fPmimetic_threshold = \fC\fBkDefaultMimeticThreshold\fP\fP)"

.PP
\fBReturns:\fP
.RS 4
Success of the construction\&. 
.RE
.PP

.PP
Definition at line 84 of file mtk_lap_3d\&.cc\&.
.SS "\fBmtk::Real\fP * mtk::Lap3D::data () const"

.PP
\fBReturns:\fP
.RS 4
The operator as a dense array\&. 
.RE
.PP

.PP
Definition at line 122 of file mtk_lap_3d\&.cc\&.
.SS "\fBmtk::UniStgGrid3D\fP mtk::Lap3D::operator* (const \fBUniStgGrid3D\fP &grid) const"

.PP
Definition at line 69 of file mtk_lap_3d\&.cc\&.
.SS "\fBmtk::DenseMatrix\fP mtk::Lap3D::ReturnAsDenseMatrix () const"

.PP
\fBReturns:\fP
.RS 4
The operator as a dense matrix\&. 
.RE
.PP

.PP
Definition at line 117 of file mtk_lap_3d\&.cc\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBDenseMatrix\fP mtk::Lap3D::laplacian_\fC [private]\fP"

.PP
Definition at line 118 of file mtk_lap_3d\&.h\&.
.SS "\fBReal\fP mtk::Lap3D::mimetic_threshold_\fC [private]\fP"

.PP
Definition at line 122 of file mtk_lap_3d\&.h\&.
.SS "int mtk::Lap3D::order_accuracy_\fC [private]\fP"

.PP
Definition at line 120 of file mtk_lap_3d\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MTK: Mimetic Methods Toolkit from the source code\&.
