.TH "src/mtk_interp_1d.cc" 3 "Wed Nov 25 2015" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mtk_interp_1d.cc \- 
.PP
Includes the implementation of the class Interp1D\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <cstring>\fP
.br
\fC#include 'mtk_tools\&.h'\fP
.br
\fC#include 'mtk_interp_1d\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmtk\fP"
.br
.RI "\fIMimetic Methods Toolkit namespace\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBmtk::operator<<\fP (std::ostream &stream, \fBmtk::Interp1D\fP &in)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class implements a 1D interpolation operator\&.
.PP
\fBAuthor:\fP
.RS 4
: Eduardo J\&. Sanchez (ejspeiro) - esanchez at mail dot sdsu dot edu
.PP
: Johnny Corbino - jcorbino at mail dot sdsu dot edu 
.RE
.PP

.PP
Definition in file \fBmtk_interp_1d\&.cc\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MTK: Mimetic Methods Toolkit from the source code\&.
