.TH "mtk::BCDesc1D" 3 "Sun Sep 13 2015" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mtk::BCDesc1D \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mtk_bc_desc_1d\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBImposeOnOperator\fP (\fBDenseMatrix\fP &matrix, const std::vector< \fBReal\fP > &west, const std::vector< \fBReal\fP > &east)"
.br
.ti -1c
.RI "static void \fBImposeOnGrid\fP (\fBUniStgGrid1D\fP &grid, const \fBReal\fP &omega, const \fBReal\fP &epsilon)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file mtk_bc_desc_1d\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void mtk::BCDesc1D::ImposeOnGrid (\fBmtk::UniStgGrid1D\fP &grid, const \fBReal\fP &omega, const \fBReal\fP &epsilon)\fC [static]\fP"

.IP "1." 4
Assign the west condition\&.
.IP "2." 4
Assign the east condition\&. 
.PP

.PP
Definition at line 30 of file mtk_bc_desc_1d\&.cc\&.
.SS "void mtk::BCDesc1D::ImposeOnOperator (\fBmtk::DenseMatrix\fP &matrix, const std::vector< \fBReal\fP > &west, const std::vector< \fBReal\fP > &east)\fC [static]\fP"

.IP "1." 4
Assign the west array\&.
.IP "2." 4
Assign the east array\&. 
.PP

.PP
Definition at line 5 of file mtk_bc_desc_1d\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MTK: Mimetic Methods Toolkit from the source code\&.
