.TH "include/mtk_enums.h" 3 "Fri Mar 11 2016" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/mtk_enums.h \- 
.PP
Considered enumeration types in the MTK\&.  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmtk\fP"
.br
.RI "\fIMimetic Methods Toolkit namespace\&. \fP"
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBmtk::MatrixStorage\fP { \fBmtk::MatrixStorage::DENSE\fP, \fBmtk::MatrixStorage::BANDED\fP, \fBmtk::MatrixStorage::CRS\fP }"
.br
.RI "\fIConsidered matrix storage schemes to implement sparse matrices\&. \fP"
.ti -1c
.RI "enum \fBmtk::MatrixOrdering\fP { \fBmtk::MatrixOrdering::ROW_MAJOR\fP, \fBmtk::MatrixOrdering::COL_MAJOR\fP }"
.br
.RI "\fIConsidered matrix ordering (for Fortran purposes)\&. \fP"
.ti -1c
.RI "enum \fBmtk::FieldNature\fP { \fBmtk::FieldNature::SCALAR\fP, \fBmtk::FieldNature::VECTOR\fP }"
.br
.RI "\fINature of the field discretized in a given grid\&. \fP"
.ti -1c
.RI "enum \fBmtk::DirInterp\fP { \fBmtk::DirInterp::SCALAR_TO_VECTOR\fP, \fBmtk::DirInterp::VECTOR_TO_SCALAR\fP }"
.br
.RI "\fIInterpolation operator\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Enumeration types are used throughout the MTK to differentiate instances of derived classes, as well as for mnemonic purposes\&. In this file, the enumeration types are listed alphabetically\&.
.PP
\fBAuthor:\fP
.RS 4
: Eduardo J\&. Sanchez (ejspeiro) - esanchez at mail dot sdsu dot edu 
.RE
.PP

.PP
Definition in file \fBmtk_enums\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MTK: Mimetic Methods Toolkit from the source code\&.
