.TH "src/mtk_lap_2d.cc" 3 "Fri Mar 11 2016" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mtk_lap_2d.cc \- 
.PP
Includes the implementation of the class Lap2D\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <cstdlib>\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include 'mtk_roots\&.h'\fP
.br
\fC#include 'mtk_blas_adapter\&.h'\fP
.br
\fC#include 'mtk_grad_2d\&.h'\fP
.br
\fC#include 'mtk_div_2d\&.h'\fP
.br
\fC#include 'mtk_lap_2d\&.h'\fP
.br

.SH "Detailed Description"
.PP 
This class implements a 2D Laplacian operator, constructed using the Castillo-Blomgren-Sanchez (CBS) Algorithm (CBSA)\&.
.PP
\fBAuthor:\fP
.RS 4
: Eduardo J\&. Sanchez (ejspeiro) - esanchez at mail dot sdsu dot edu 
.RE
.PP

.PP
Definition in file \fBmtk_lap_2d\&.cc\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MTK: Mimetic Methods Toolkit from the source code\&.
