.TH "src/mtk_bc_desc_1d.cc" 3 "Sun Sep 13 2015" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mtk_bc_desc_1d.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'mtk_tools\&.h'\fP
.br
\fC#include 'mtk_bc_desc_1d\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for MTK: Mimetic Methods Toolkit from the source code\&.
