.TH "src/mtk_curl_2d.cc" 3 "Mon Dec 14 2015" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mtk_curl_2d.cc \- 
.PP
Implements the class Curl2D\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <cstdlib>\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include 'mtk_roots\&.h'\fP
.br
\fC#include 'mtk_enums\&.h'\fP
.br
\fC#include 'mtk_uni_stg_grid_1d\&.h'\fP
.br
\fC#include 'mtk_div_1d\&.h'\fP
.br
\fC#include 'mtk_div_2d\&.h'\fP
.br
\fC#include 'mtk_curl_2d\&.h'\fP
.br

.SH "Detailed Description"
.PP 
This class implements a 2D curl matrix operator, constructed using the Castillo-Blomgren-Sanchez (CBS) Algorithm\&.
.PP
\fBAuthor:\fP
.RS 4
: Eduardo J\&. Sanchez (ejspeiro) - esanchez at mail dot sdsu dot edu 
.RE
.PP

.PP
Definition in file \fBmtk_curl_2d\&.cc\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MTK: Mimetic Methods Toolkit from the source code\&.
