.TH "mtk::Tools" 3 "Wed Nov 25 2015" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mtk::Tools \- 
.PP
Tool manager class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mtk_tools\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBPrevent\fP (const bool complement, const char *const fname, int lineno, const char *const fxname) noexcept"
.br
.RI "\fIEnforces preconditions by preventing their complements from occur\&. \fP"
.ti -1c
.RI "static void \fBBeginUnitTestNo\fP (const int &nn) noexcept"
.br
.RI "\fIBegins the execution of a unit test\&. Starts a timer\&. \fP"
.ti -1c
.RI "static void \fBEndUnitTestNo\fP (const int &nn) noexcept"
.br
.RI "\fIEnds the execution of a unit test\&. Stops and reports wall-clock time\&. \fP"
.ti -1c
.RI "static void \fBAssert\fP (const bool &condition) noexcept"
.br
.RI "\fIAsserts if the condition required to pass the unit test occurs\&. \fP"
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static int \fBtest_number_\fP"
.br
.RI "\fICurrent test being executed\&. \fP"
.ti -1c
.RI "static \fBReal\fP \fBduration_\fP"
.br
.RI "\fIDuration of the current test\&. \fP"
.ti -1c
.RI "static clock_t \fBbegin_time_\fP"
.br
.RI "\fIElapsed time on current test\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Basic tools to ensure execution correctness\&. 
.PP
Definition at line 78 of file mtk_tools\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void mtk::Tools::Assert (const bool &condition)\fC [static]\fP, \fC [noexcept]\fP"

.PP
\fBParameters:\fP
.RS 4
\fIcondition\fP Condition to be asserted\&. 
.RE
.PP

.PP
Definition at line 114 of file mtk_tools\&.cc\&.
.SS "void mtk::Tools::BeginUnitTestNo (const int &nn)\fC [static]\fP, \fC [noexcept]\fP"

.PP
\fBParameters:\fP
.RS 4
\fInn\fP Number of the test\&. 
.RE
.PP

.PP
Definition at line 91 of file mtk_tools\&.cc\&.
.SS "void mtk::Tools::EndUnitTestNo (const int &nn)\fC [static]\fP, \fC [noexcept]\fP"

.PP
\fBParameters:\fP
.RS 4
\fInn\fP Number of the test\&. 
.RE
.PP

.PP
Definition at line 105 of file mtk_tools\&.cc\&.
.SS "void mtk::Tools::Prevent (const boolcomplement, const char *constfname, intlineno, const char *constfxname)\fC [static]\fP, \fC [noexcept]\fP"

.PP
\fBSee also:\fP
.RS 4
http://stackoverflow.com/questions/8884335/print-the-file-name-line-number-and-function-name-of-a-calling-function-c-pro
.RE
.PP
\fBParameters:\fP
.RS 4
\fIcomplement\fP Complement of desired pre-condition\&. 
.br
\fIfname\fP Name of the file being checked\&. 
.br
\fIlineno\fP Number of the line where the check is executed\&. 
.br
\fIfxname\fP Name of the module containing the check\&. 
.RE
.PP

.PP
\fBTodo\fP
.RS 4
Check if this is the best way of stalling execution\&. 
.RE
.PP

.PP
Definition at line 61 of file mtk_tools\&.cc\&.
.SH "Member Data Documentation"
.PP 
.SS "clock_t mtk::Tools::begin_time_\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 121 of file mtk_tools\&.h\&.
.SS "\fBmtk::Real\fP mtk::Tools::duration_\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 119 of file mtk_tools\&.h\&.
.SS "int mtk::Tools::test_number_\fC [static]\fP, \fC [private]\fP"

.PP
\fBTodo\fP
.RS 4
Check usage of static methods and private members\&. 
.RE
.PP

.PP
Definition at line 117 of file mtk_tools\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MTK: Mimetic Methods Toolkit from the source code\&.
