.TH "src/mtk_operator_applicator.cc" 3 "Mon Jul 4 2016" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mtk_operator_applicator.cc \- 
.PP
Implements the class OperatorApplicator\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <cstdlib>\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include 'mtk_tools\&.h'\fP
.br
\fC#include 'mtk_blas_adapter\&.h'\fP
.br
\fC#include 'mtk_operator_applicator\&.h'\fP
.br

.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
: Eduardo J\&. Sanchez (ejspeiro) - esanchez at mail dot sdsu dot edu 
.RE
.PP

.PP
Definition in file \fBmtk_operator_applicator\&.cc\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MTK: Mimetic Methods Toolkit from the source code\&.
