.TH "include/mtk_operator_applicator.h" 3 "Mon Jul 4 2016" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/mtk_operator_applicator.h \- 
.PP
Controls the process of applying a mimetic operator to a grid\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'mtk_foundations\&.h'\fP
.br
\fC#include 'mtk_enums\&.h'\fP
.br
\fC#include 'mtk_dense_matrix\&.h'\fP
.br
\fC#include 'mtk_uni_stg_grid_1d\&.h'\fP
.br
\fC#include 'mtk_uni_stg_grid_2d\&.h'\fP
.br
\fC#include 'mtk_uni_stg_grid_3d\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmtk::OperatorApplicator\fP"
.br
.RI "\fIControls the process of applying a mimetic operator to a grid\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmtk\fP"
.br
.RI "\fIMimetic Methods Toolkit namespace\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
: Eduardo J\&. Sanchez (ejspeiro) - esanchez at mail dot sdsu dot edu 
.RE
.PP

.PP
Definition in file \fBmtk_operator_applicator\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MTK: Mimetic Methods Toolkit from the source code\&.
