.TH "src/mtk_uni_stg_grid_2d.cc" 3 "Thu Nov 26 2015" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mtk_uni_stg_grid_2d.cc \- 
.PP
Implementation of a 2D uniform staggered grid\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include 'mtk_tools\&.h'\fP
.br
\fC#include 'mtk_uni_stg_grid_2d\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmtk\fP"
.br
.RI "\fIMimetic Methods Toolkit namespace\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBmtk::operator<<\fP (std::ostream &stream, \fBmtk::UniStgGrid2D\fP &in)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Implementation of a 2D uniform staggered grid\&.
.PP
\fBAuthor:\fP
.RS 4
: Eduardo J\&. Sanchez (ejspeiro) - esanchez at mail dot sdsu dot edu 
.RE
.PP

.PP
Definition in file \fBmtk_uni_stg_grid_2d\&.cc\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MTK: Mimetic Methods Toolkit from the source code\&.
