.TH "tests/mtk_grad_1d_test.cc" 3 "Fri Mar 11 2016" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests/mtk_grad_1d_test.cc \- 
.PP
Testing the mimetic 1D gradient, constructed with the CBS algorithm\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
: Eduardo J\&. Sanchez (ejspeiro) - esanchez at mail dot sdsu dot edu 
.RE
.PP

.PP
Definition in file \fBmtk_grad_1d_test\&.cc\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Definition at line 319 of file mtk_grad_1d_test\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MTK: Mimetic Methods Toolkit from the source code\&.
