.TH "tests/mtk_div_1d_test/mtk_div_1d_test.cc" 3 "Mon Jul 4 2016" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests/mtk_div_1d_test/mtk_div_1d_test.cc \- 
.PP
Testing the mimetic 1D divergence, constructed with the CBS algorithm\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'mtk\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBTestDefaultConstructorFactoryMethodDefault\fP ()"
.br
.ti -1c
.RI "void \fBTestDefaultConstructorFactoryMethodFourthOrder\fP ()"
.br
.ti -1c
.RI "void \fBTestDefaultConstructorFactoryMethodSixthOrder\fP ()"
.br
.ti -1c
.RI "void \fBTestDefaultConstructorFactoryMethodEightOrderDefThreshold\fP ()"
.br
.ti -1c
.RI "void \fBTestDefaultConstructorFactoryMethodTenthOrderDefThreshold\fP ()"
.br
.ti -1c
.RI "void \fBTestDefaultConstructorFactoryMethodTwelfthOrderDefThreshold\fP ()"
.br
.ti -1c
.RI "void \fBTestDefaultConstructorFactoryMethodFourteenthOrderDefThreshold\fP ()"
.br
.ti -1c
.RI "void \fBTestSecondOrderReturnAsDenseMatrixWithGrid\fP ()"
.br
.ti -1c
.RI "void \fBTestFourthOrderReturnAsDenseMatrixWithGrid\fP ()"
.br
.ti -1c
.RI "void \fBTestSixthOrderReturnAsDenseMatrixWithGrid\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
: Eduardo J\&. Sanchez (ejspeiro) - esanchez at mail dot sdsu dot edu 
.RE
.PP

.PP
Definition in file \fBmtk_div_1d_test\&.cc\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Definition at line 294 of file mtk_div_1d_test\&.cc\&.
.SS "void TestDefaultConstructorFactoryMethodDefault ()"

.PP
Definition at line 58 of file mtk_div_1d_test\&.cc\&.
.SS "void TestDefaultConstructorFactoryMethodEightOrderDefThreshold ()"

.PP
Definition at line 106 of file mtk_div_1d_test\&.cc\&.
.SS "void TestDefaultConstructorFactoryMethodFourteenthOrderDefThreshold ()"

.PP
Definition at line 154 of file mtk_div_1d_test\&.cc\&.
.SS "void TestDefaultConstructorFactoryMethodFourthOrder ()"

.PP
Definition at line 74 of file mtk_div_1d_test\&.cc\&.
.SS "void TestDefaultConstructorFactoryMethodSixthOrder ()"

.PP
Definition at line 90 of file mtk_div_1d_test\&.cc\&.
.SS "void TestDefaultConstructorFactoryMethodTenthOrderDefThreshold ()"

.PP
Definition at line 122 of file mtk_div_1d_test\&.cc\&.
.SS "void TestDefaultConstructorFactoryMethodTwelfthOrderDefThreshold ()"

.PP
Definition at line 138 of file mtk_div_1d_test\&.cc\&.
.SS "void TestFourthOrderReturnAsDenseMatrixWithGrid ()"

.PP
Definition at line 244 of file mtk_div_1d_test\&.cc\&.
.SS "void TestSecondOrderReturnAsDenseMatrixWithGrid ()"

.PP
Definition at line 170 of file mtk_div_1d_test\&.cc\&.
.SS "void TestSixthOrderReturnAsDenseMatrixWithGrid ()"

.PP
Definition at line 269 of file mtk_div_1d_test\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MTK: Mimetic Methods Toolkit from the source code\&.
