.TH "src/mtk_blas_adapter.cc" 3 "Mon Feb 1 2016" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mtk_blas_adapter.cc \- 
.PP
Adapter class for the BLAS API\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'mtk_roots\&.h'\fP
.br
\fC#include 'mtk_tools\&.h'\fP
.br
\fC#include 'mtk_blas_adapter\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmtk\fP"
.br
.RI "\fIMimetic Methods Toolkit namespace\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "float \fBmtk::snrm2_\fP (int *n, float *x, int *incx)"
.br
.ti -1c
.RI "void \fBmtk::saxpy_\fP (int *n, float *sa, float *sx, int *incx, float *sy, int *incy)"
.br
.ti -1c
.RI "void \fBmtk::sgemv_\fP (char *trans, int *m, int *n, float *alpha, float *a, int *lda, float *x, int *incx, float *beta, float *y, int *incy)"
.br
.ti -1c
.RI "void \fBmtk::sgemm_\fP (char *transa, char *transb, int *m, int *n, int *k, double *alpha, double *a, int *lda, double *b, aamm int *ldb, double *beta, double *c, int *ldc)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Implementation of a class that contains a collection of static member functions, that posses direct access to the underlying structure of the matrices, thus allowing programmers to exploit some of the numerical methods implemented in the BLAS\&.
.PP
The \fBBLAS (Basic Linear Algebra Subprograms)\fP are routines that provide standard building blocks for performing basic vector and matrix operations\&. The Level 1 BLAS perform scalar, vector and vector-vector operations, the Level 2 BLAS perform matrix-vector operations, and the Level 3 BLAS perform matrix-matrix operations\&.
.PP
The BLAS can be installed from links given in the See Also section of this page\&.
.PP
\fBSee also:\fP
.RS 4
http://www.netlib.org/blas/
.PP
https://software.intel.com/en-us/non-commercial-software-development
.RE
.PP
\fBTodo\fP
.RS 4
Write documentation using LaTeX\&.
.RE
.PP
.PP
\fBAuthor:\fP
.RS 4
: Eduardo J\&. Sanchez (ejspeiro) - esanchez at mail dot sdsu dot edu 
.RE
.PP

.PP
Definition in file \fBmtk_blas_adapter\&.cc\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MTK: Mimetic Methods Toolkit from the source code\&.
