.TH "include/mtk_glpk_adapter.h" 3 "Thu Sep 10 2015" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/mtk_glpk_adapter.h \- 
.PP
Adapter class for the GLPK API\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include 'glpk\&.h'\fP
.br
\fC#include 'mtk_roots\&.h'\fP
.br
\fC#include 'mtk_dense_matrix\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmtk::GLPKAdapter\fP"
.br
.RI "\fIAdapter class for the GLPK API\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBmtk\fP"
.br
.RI "\fIMimetic Methods Toolkit namespace\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This class contains a collection of static classes, that posses direct access to the underlying structure of the matrices, thus allowing programmers to exploit some of the numerical methods implemented in the GLPK\&.
.PP
The \fBGLPK (GNU Linear Programming Kit)\fP package is intended for solving large-scale linear programming (LP), mixed integer programming (MIP), and other related problems\&. It is a set of routines written in ANSI C and organized in the form of a callable library\&.
.PP
\fBSee Also:\fP
.RS 4
http://www.gnu.org/software/glpk/
.RE
.PP
\fBAuthor:\fP
.RS 4
: Eduardo J\&. Sanchez (ejspeiro) - esanchez at mail dot sdsu dot edu 
.RE
.PP

.PP
Definition in file \fBmtk_glpk_adapter\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MTK: Mimetic Methods Toolkit from the source code\&.
