.TH "mtk::Lap2D" 3 "Mon Feb 1 2016" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mtk::Lap2D \- 
.PP
Implements a 2D mimetic Laplacian operator\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mtk_lap_2d\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLap2D\fP ()"
.br
.RI "\fIDefault constructor\&. \fP"
.ti -1c
.RI "\fBLap2D\fP (const \fBLap2D\fP &lap)"
.br
.RI "\fICopy constructor\&. \fP"
.ti -1c
.RI "\fB~Lap2D\fP ()"
.br
.RI "\fIDestructor\&. \fP"
.ti -1c
.RI "bool \fBConstructLap2D\fP (const \fBUniStgGrid2D\fP &grid, int order_accuracy=\fBkDefaultOrderAccuracy\fP, \fBReal\fP mimetic_threshold=\fBkDefaultMimeticThreshold\fP)"
.br
.RI "\fIFactory method implementing the CBS Algorithm to build operator\&. \fP"
.ti -1c
.RI "\fBDenseMatrix\fP \fBReturnAsDenseMatrix\fP () const "
.br
.RI "\fIReturn the operator as a dense matrix\&. \fP"
.ti -1c
.RI "\fBReal\fP * \fBdata\fP () const "
.br
.RI "\fIReturn the operator as a dense array\&. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBDenseMatrix\fP \fBlaplacian_\fP"
.br
.RI "\fIActual operator\&. \fP"
.ti -1c
.RI "int \fBorder_accuracy_\fP"
.br
.RI "\fIOrder of accuracy\&. \fP"
.ti -1c
.RI "\fBReal\fP \fBmimetic_threshold_\fP"
.br
.RI "\fIMimetic Threshold\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This class implements a 2D Laplacian operator, constructed using the Castillo-Blomgren-Sanchez (CBS) Algorithm (CBSA)\&. 
.PP
Definition at line 76 of file mtk_lap_2d\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "mtk::Lap2D::Lap2D ()"

.PP
Definition at line 69 of file mtk_lap_2d\&.cc\&.
.SS "mtk::Lap2D::Lap2D (const \fBLap2D\fP &lap)"

.PP
\fBParameters:\fP
.RS 4
\fIlap\fP Given Laplacian\&. 
.RE
.PP

.PP
Definition at line 71 of file mtk_lap_2d\&.cc\&.
.SS "mtk::Lap2D::~Lap2D ()"

.PP
Definition at line 75 of file mtk_lap_2d\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "bool mtk::Lap2D::ConstructLap2D (const \fBUniStgGrid2D\fP &grid, intorder_accuracy = \fC\fBkDefaultOrderAccuracy\fP\fP, \fBmtk::Real\fPmimetic_threshold = \fC\fBkDefaultMimeticThreshold\fP\fP)"

.PP
\fBReturns:\fP
.RS 4
Success of the construction\&. 
.RE
.PP

.PP
Definition at line 77 of file mtk_lap_2d\&.cc\&.
.SS "\fBmtk::Real\fP * mtk::Lap2D::data () const"

.PP
\fBReturns:\fP
.RS 4
The operator as a dense array\&. 
.RE
.PP

.PP
Definition at line 115 of file mtk_lap_2d\&.cc\&.
.SS "\fBmtk::DenseMatrix\fP mtk::Lap2D::ReturnAsDenseMatrix () const"

.PP
\fBReturns:\fP
.RS 4
The operator as a dense matrix\&. 
.RE
.PP

.PP
Definition at line 110 of file mtk_lap_2d\&.cc\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBDenseMatrix\fP mtk::Lap2D::laplacian_\fC [private]\fP"

.PP
Definition at line 115 of file mtk_lap_2d\&.h\&.
.SS "\fBReal\fP mtk::Lap2D::mimetic_threshold_\fC [private]\fP"

.PP
Definition at line 119 of file mtk_lap_2d\&.h\&.
.SS "int mtk::Lap2D::order_accuracy_\fC [private]\fP"

.PP
Definition at line 117 of file mtk_lap_2d\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MTK: Mimetic Methods Toolkit from the source code\&.
