.TH "src/mtk_tools.cc" 3 "Mon Jul 4 2016" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mtk_tools.cc \- 
.PP
Definition of a class to manage run-time tools\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <cstdlib>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'mtk_foundations\&.h'\fP
.br
\fC#include 'mtk_tools\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Definition of a class providing basic tools to ensure execution correctness, and to assists with unitary testing\&.
.PP
\fBAuthor:\fP
.RS 4
: Eduardo J\&. Sanchez (ejspeiro) - esanchez at mail dot sdsu dot edu 
.RE
.PP

.PP
Definition in file \fBmtk_tools\&.cc\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MTK: Mimetic Methods Toolkit from the source code\&.
