.TH "src/mtk_tools.cc" 3 "Fri Nov 20 2015" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mtk_tools.cc \- 
.PP
Implements a execution tool manager class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'mtk_roots\&.h'\fP
.br
\fC#include 'mtk_tools\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Basic tools to ensure execution correctness\&.
.PP
\fBAuthor:\fP
.RS 4
: Eduardo J\&. Sanchez (ejspeiro) - esanchez at mail dot sdsu dot edu 
.RE
.PP

.PP
Definition in file \fBmtk_tools\&.cc\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MTK: Mimetic Methods Toolkit from the source code\&.
