.TH "src/mtk_glpk_adapter.cc" 3 "Tue Dec 1 2015" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mtk_glpk_adapter.cc \- 
.PP
Adapter class for the GLPK API\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <cmath>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <limits>\fP
.br
\fC#include 'mtk_roots\&.h'\fP
.br
\fC#include 'mtk_blas_adapter\&.h'\fP
.br
\fC#include 'mtk_glpk_adapter\&.h'\fP
.br

.SH "Detailed Description"
.PP 
This class contains a collection of static classes, that posses direct access to the underlying structure of the matrices, thus allowing programmers to exploit some of the numerical methods implemented in the GLPK\&.
.PP
The \fBGLPK (GNU Linear Programming Kit)\fP package is intended for solving large-scale linear programming (LP), mixed integer programming (MIP), and other related problems\&. It is a set of routines written in ANSI C and organized in the form of a callable library\&.
.PP
\fBSee also:\fP
.RS 4
http://www.gnu.org/software/glpk/
.RE
.PP
\fBAuthor:\fP
.RS 4
: Eduardo J\&. Sanchez (ejspeiro) - esanchez at mail dot sdsu dot edu 
.RE
.PP

.PP
Definition in file \fBmtk_glpk_adapter\&.cc\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MTK: Mimetic Methods Toolkit from the source code\&.
