.TH "mtk::Interp2D" 3 "Thu Oct 15 2015" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mtk::Interp2D \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mtk_interp_2d\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInterp2D\fP ()"
.br
.ti -1c
.RI "\fBInterp2D\fP (const \fBInterp2D\fP &interp)"
.br
.ti -1c
.RI "\fB~Interp2D\fP ()"
.br
.ti -1c
.RI "\fBDenseMatrix\fP \fBConstructInterp2D\fP (const \fBUniStgGrid2D\fP &grid, int order_accuracy=\fBkDefaultOrderAccuracy\fP, \fBReal\fP mimetic_threshold=\fBkDefaultMimeticThreshold\fP)"
.br
.ti -1c
.RI "\fBDenseMatrix\fP \fBReturnAsDenseMatrix\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBDenseMatrix\fP \fBinterpolator_\fP"
.br
.ti -1c
.RI "int \fBorder_accuracy_\fP"
.br
.ti -1c
.RI "\fBReal\fP \fBmimetic_threshold_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 67 of file mtk_interp_2d\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "mtk::Interp2D::Interp2D ()"

.SS "mtk::Interp2D::Interp2D (const \fBInterp2D\fP &interp)"

.SS "mtk::Interp2D::~Interp2D ()"

.SH "Member Function Documentation"
.PP 
.SS "\fBDenseMatrix\fP mtk::Interp2D::ConstructInterp2D (const \fBUniStgGrid2D\fP &grid, intorder_accuracy = \fC\fBkDefaultOrderAccuracy\fP\fP, \fBReal\fPmimetic_threshold = \fC\fBkDefaultMimeticThreshold\fP\fP)"

.SS "\fBDenseMatrix\fP mtk::Interp2D::ReturnAsDenseMatrix ()"

.SH "Member Data Documentation"
.PP 
.SS "\fBDenseMatrix\fP mtk::Interp2D::interpolator_\fC [private]\fP"

.PP
Definition at line 78 of file mtk_interp_2d\&.h\&.
.SS "\fBReal\fP mtk::Interp2D::mimetic_threshold_\fC [private]\fP"

.PP
Definition at line 80 of file mtk_interp_2d\&.h\&.
.SS "int mtk::Interp2D::order_accuracy_\fC [private]\fP"

.PP
Definition at line 79 of file mtk_interp_2d\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MTK: Mimetic Methods Toolkit from the source code\&.
