.TH "include/mtk_tools.h" 3 "Sun Sep 13 2015" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/mtk_tools.h \- 
.PP
Tool manager class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <ctime>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmtk::Tools\fP"
.br
.RI "\fITool manager class\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBmtk\fP"
.br
.RI "\fIMimetic Methods Toolkit namespace\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Basic tools to ensure execution correctness\&.
.PP
\fBAuthor:\fP
.RS 4
: Eduardo J\&. Sanchez (ejspeiro) - esanchez at mail dot sdsu dot edu 
.RE
.PP

.PP
Definition in file \fBmtk_tools\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MTK: Mimetic Methods Toolkit from the source code\&.
