.TH "include/mtk_matrix.h" 3 "Thu Oct 15 2015" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/mtk_matrix.h \- 
.PP
Definition of the representation of a matrix in the MTK\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'mtk_roots\&.h'\fP
.br
\fC#include 'mtk_enums\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmtk::Matrix\fP"
.br
.RI "\fIDefinition of the representation of a matrix in the MTK\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBmtk\fP"
.br
.RI "\fIMimetic Methods Toolkit namespace\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition of the representation for the matrices implemented in the MTK\&.
.PP
\fBAuthor:\fP
.RS 4
: Eduardo J\&. Sanchez (ejspeiro) - esanchez at mail dot sdsu dot edu 
.RE
.PP

.PP
Definition in file \fBmtk_matrix\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MTK: Mimetic Methods Toolkit from the source code\&.
