.TH "include/mtk_lap_1d.h" 3 "Wed Nov 18 2015" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/mtk_lap_1d.h \- 
.PP
Includes the definition of the class Lap1D\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'mtk_dense_matrix\&.h'\fP
.br
\fC#include 'mtk_uni_stg_grid_1d\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmtk::Lap1D\fP"
.br
.RI "\fIImplements a 1D mimetic Laplacian operator\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmtk\fP"
.br
.RI "\fIMimetic Methods Toolkit namespace\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This class implements a 1D Laplacian operator, constructed using the Castillo-Blomgren-Sanchez (CBS) Algorithm (CBSA)\&.
.PP
\fBAuthor:\fP
.RS 4
: Eduardo J\&. Sanchez (ejspeiro) - esanchez at mail dot sdsu dot edu 
.RE
.PP

.PP
Definition in file \fBmtk_lap_1d\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MTK: Mimetic Methods Toolkit from the source code\&.
