.TH "tests/mtk_grad_1d_test/mtk_grad_1d_test.cc" 3 "Mon Jul 4 2016" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests/mtk_grad_1d_test/mtk_grad_1d_test.cc \- 
.PP
Testing the mimetic 1D gradient, constructed with the CBS algorithm\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'mtk\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBTestDefaultConstructorFactoryMethodDefault\fP ()"
.br
.ti -1c
.RI "void \fBTestDefaultConstructorFactoryMethodFourthOrder\fP ()"
.br
.ti -1c
.RI "void \fBTestDefaultConstructorFactoryMethodSixthOrder\fP ()"
.br
.ti -1c
.RI "void \fBTestDefaultConstructorFactoryMethodEightOrderDefThreshold\fP ()"
.br
.ti -1c
.RI "void \fBTestDefaultConstructorFactoryMethodTenthOrderDefThreshold\fP ()"
.br
.ti -1c
.RI "void \fBTestReturnAsDenseMatrixWithGrid\fP ()"
.br
.ti -1c
.RI "void \fBTestReturnAsDimensionlessDenseMatrix\fP ()"
.br
.ti -1c
.RI "void \fBTestWriteToFile\fP ()"
.br
.ti -1c
.RI "void \fBTestMimBndy\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
: Eduardo J\&. Sanchez (ejspeiro) - esanchez at mail dot sdsu dot edu 
.RE
.PP

.PP
Definition in file \fBmtk_grad_1d_test\&.cc\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Definition at line 303 of file mtk_grad_1d_test\&.cc\&.
.SS "void TestDefaultConstructorFactoryMethodDefault ()"

.PP
Definition at line 58 of file mtk_grad_1d_test\&.cc\&.
.SS "void TestDefaultConstructorFactoryMethodEightOrderDefThreshold ()"

.PP
Definition at line 113 of file mtk_grad_1d_test\&.cc\&.
.SS "void TestDefaultConstructorFactoryMethodFourthOrder ()"

.PP
Definition at line 77 of file mtk_grad_1d_test\&.cc\&.
.SS "void TestDefaultConstructorFactoryMethodSixthOrder ()"

.PP
Definition at line 95 of file mtk_grad_1d_test\&.cc\&.
.SS "void TestDefaultConstructorFactoryMethodTenthOrderDefThreshold ()"

.PP
Definition at line 131 of file mtk_grad_1d_test\&.cc\&.
.SS "void TestMimBndy ()"

.PP
Definition at line 281 of file mtk_grad_1d_test\&.cc\&.
.SS "void TestReturnAsDenseMatrixWithGrid ()"

.PP
Definition at line 149 of file mtk_grad_1d_test\&.cc\&.
.SS "void TestReturnAsDimensionlessDenseMatrix ()"

.PP
Definition at line 233 of file mtk_grad_1d_test\&.cc\&.
.SS "void TestWriteToFile ()"

.PP
Definition at line 253 of file mtk_grad_1d_test\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MTK: Mimetic Methods Toolkit from the source code\&.
