.TH "include/mtk_quad_1d.h" 3 "Tue Dec 1 2015" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/mtk_quad_1d.h \- 
.PP
Includes the definition of the class Quad1D\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmtk::Quad1D\fP"
.br
.RI "\fIImplements a 1D mimetic quadrature\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmtk\fP"
.br
.RI "\fIMimetic Methods Toolkit namespace\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This class implements a 1D quadrature solver based on the mimetic discretization of the gradient operator\&.
.PP
\fBSee also:\fP
.RS 4
\fBmtk::Grad1D\fP
.RE
.PP
\fBAuthor:\fP
.RS 4
: Eduardo J\&. Sanchez (ejspeiro) - esanchez at mail dot sdsu dot edu
.RE
.PP
\fBTodo\fP
.RS 4
Implement this class\&. 
.RE
.PP

.PP
Definition in file \fBmtk_quad_1d\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MTK: Mimetic Methods Toolkit from the source code\&.
