.TH "src/mtk_div_1d.cc" 3 "Fri Nov 20 2015" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mtk_div_1d.cc \- 
.PP
Implements the class Div1D\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <cmath>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <limits>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include 'mtk_tools\&.h'\fP
.br
\fC#include 'mtk_blas_adapter\&.h'\fP
.br
\fC#include 'mtk_lapack_adapter\&.h'\fP
.br
\fC#include 'mtk_glpk_adapter\&.h'\fP
.br
\fC#include 'mtk_div_1d\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmtk\fP"
.br
.RI "\fIMimetic Methods Toolkit namespace\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBmtk::operator<<\fP (std::ostream &stream, \fBmtk::Div1D\fP &in)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class implements a 1D divergence matrix operator, constructed using the Castillo-Blomgren-Sanchez (CBS) Algorithm\&.
.PP
\fBAuthor:\fP
.RS 4
: Eduardo J\&. Sanchez (ejspeiro) - esanchez at mail dot sdsu dot edu
.RE
.PP
\fBTodo\fP
.RS 4
Overload ostream operator as in \fBmtk::Lap1D\fP\&.
.RE
.PP
.PP
\fBTodo\fP
.RS 4
Implement creation of $ \mathbf{\Lambda}$ w\&. \fBmtk::BLASAdapter\fP\&. 
.RE
.PP

.PP
Definition in file \fBmtk_div_1d\&.cc\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MTK: Mimetic Methods Toolkit from the source code\&.
