.TH "include/mtk_roots.h" 3 "Tue Jan 26 2016" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/mtk_roots.h \- 
.PP
Fundamental definitions to be used across all classes of the MTK\&.  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmtk\fP"
.br
.RI "\fIMimetic Methods Toolkit namespace\&. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef float \fBmtk::Real\fP"
.br
.RI "\fIUsers can simply change this to build a double- or single-precision MTK\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const float \fBmtk::kZero\fP {0\&.0f}"
.br
.RI "\fIMTK's zero defined according to selective compilation\&. \fP"
.ti -1c
.RI "const float \fBmtk::kOne\fP {1\&.0f}"
.br
.RI "\fIMTK's one defined according to selective compilation\&. \fP"
.ti -1c
.RI "const float \fBmtk::kTwo\fP {2\&.0f}"
.br
.RI "\fIMTK's two defined according to selective compilation\&. \fP"
.ti -1c
.RI "const float \fBmtk::kDefaultTolerance\fP {1e-7f}"
.br
.RI "\fIConsidered tolerance for comparisons in numerical methods\&. \fP"
.ti -1c
.RI "const float \fBmtk::kDefaultMimeticThreshold\fP {1e-6f}"
.br
.RI "\fIDefault tolerance for higher-order mimetic operators\&. \fP"
.ti -1c
.RI "const int \fBmtk::kDefaultOrderAccuracy\fP {2}"
.br
.RI "\fIDefault order of accuracy for mimetic operators\&. \fP"
.ti -1c
.RI "const int \fBmtk::kCriticalOrderAccuracyGrad\fP {10}"
.br
.RI "\fIAt this order (and higher) we must use the CBSA to construct gradients\&. \fP"
.ti -1c
.RI "const int \fBmtk::kCriticalOrderAccuracyDiv\fP {8}"
.br
.RI "\fIAt this order (and higher) we must use the CBSA to construct divergences\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This file contains the fundamental definitions that classes of the MTK rely on to be implemented\&. Examples of these definitions are the definition of fundamental data types, and global variables affecting the construction of mimetic operators, among others\&.
.PP
\fBAuthor:\fP
.RS 4
: Eduardo J\&. Sanchez (ejspeiro) - esanchez at sciences dot sdsu dot edu
.RE
.PP
\fBTodo\fP
.RS 4
Test selective precision mechanisms\&. 
.RE
.PP

.PP
Definition in file \fBmtk_roots\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MTK: Mimetic Methods Toolkit from the source code\&.
