.TH "src/mtk_bc_descriptor_1d.cc" 3 "Mon Nov 23 2015" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mtk_bc_descriptor_1d.cc \- 
.PP
Enforces boundary conditions in either the operator or the grid\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'mtk_tools\&.h'\fP
.br
\fC#include 'mtk_bc_descriptor_1d\&.h'\fP
.br

.SH "Detailed Description"
.PP 
This class presents an interface for the user to specify boundary conditions on 1D mimetic operators and the grids they are acting on\&.
.PP
\fBAuthor:\fP
.RS 4
: Eduardo J\&. Sanchez (ejspeiro) - esanchez at mail dot sdsu dot edu 
.RE
.PP

.PP
Definition in file \fBmtk_bc_descriptor_1d\&.cc\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MTK: Mimetic Methods Toolkit from the source code\&.
