.TH "mtk::Div2D" 3 "Tue Dec 15 2015" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mtk::Div2D \- 
.PP
Implements a 2D mimetic divergence operator\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mtk_div_2d\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDiv2D\fP ()"
.br
.RI "\fIDefault constructor\&. \fP"
.ti -1c
.RI "\fBDiv2D\fP (const \fBDiv2D\fP &div)"
.br
.RI "\fICopy constructor\&. \fP"
.ti -1c
.RI "\fB~Div2D\fP ()"
.br
.RI "\fIDestructor\&. \fP"
.ti -1c
.RI "bool \fBConstructDiv2D\fP (const \fBUniStgGrid2D\fP &grid, int order_accuracy=\fBkDefaultOrderAccuracy\fP, \fBReal\fP mimetic_threshold=\fBkDefaultMimeticThreshold\fP)"
.br
.RI "\fIFactory method implementing the CBS Algorithm to build operator\&. \fP"
.ti -1c
.RI "\fBDenseMatrix\fP \fBReturnAsDenseMatrix\fP () const "
.br
.RI "\fIReturn the operator as a dense matrix\&. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBDenseMatrix\fP \fBdivergence_\fP"
.br
.RI "\fIActual operator\&. \fP"
.ti -1c
.RI "int \fBorder_accuracy_\fP"
.br
.RI "\fIOrder of accuracy\&. \fP"
.ti -1c
.RI "\fBReal\fP \fBmimetic_threshold_\fP"
.br
.RI "\fIMimetic Threshold\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This class implements a 2D divergence operator, constructed using the Castillo-Blomgren-Sanchez (CBS) Algorithm (CBSA)\&. 
.PP
Definition at line 76 of file mtk_div_2d\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "mtk::Div2D::Div2D ()"

.PP
Definition at line 69 of file mtk_div_2d\&.cc\&.
.SS "mtk::Div2D::Div2D (const \fBDiv2D\fP &div)"

.PP
\fBParameters:\fP
.RS 4
\fIdiv\fP Given divergence\&. 
.RE
.PP

.PP
Definition at line 73 of file mtk_div_2d\&.cc\&.
.SS "mtk::Div2D::~Div2D ()"

.PP
Definition at line 77 of file mtk_div_2d\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "bool mtk::Div2D::ConstructDiv2D (const \fBUniStgGrid2D\fP &grid, intorder_accuracy = \fC\fBkDefaultOrderAccuracy\fP\fP, \fBmtk::Real\fPmimetic_threshold = \fC\fBkDefaultMimeticThreshold\fP\fP)"

.PP
\fBReturns:\fP
.RS 4
Success of the construction\&. 
.RE
.PP

.PP
Definition at line 79 of file mtk_div_2d\&.cc\&.
.SS "\fBmtk::DenseMatrix\fP mtk::Div2D::ReturnAsDenseMatrix () const"

.PP
\fBReturns:\fP
.RS 4
The operator as a dense matrix\&. 
.RE
.PP

.PP
Definition at line 147 of file mtk_div_2d\&.cc\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBDenseMatrix\fP mtk::Div2D::divergence_\fC [private]\fP"

.PP
Definition at line 108 of file mtk_div_2d\&.h\&.
.SS "\fBReal\fP mtk::Div2D::mimetic_threshold_\fC [private]\fP"

.PP
Definition at line 112 of file mtk_div_2d\&.h\&.
.SS "int mtk::Div2D::order_accuracy_\fC [private]\fP"

.PP
Definition at line 110 of file mtk_div_2d\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MTK: Mimetic Methods Toolkit from the source code\&.
