.TH "page_def_decs" 3 "Mon Jul 4 2016" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
page_def_decs \- Definitions and Declarations 
Throughout the library, we emphasize the difference between definitions and declarations as explained in: http://www.lurklurk.org/linkers/linkers.html#cfile
.PP
A definition associates a name with an implementation of that name, which could be either data or code (\&.\&.\&.)
.PP
A declaration tells the C compiler that a definition of something (with a particular name) exists elsewhere in the program, probably in a different C file\&. (Note that a definition also counts as a declaration—it's a declaration that also happens to fill in the particular 'elsewhere')\&. 
