.TH "page_architectures" 3 "Mon Feb 1 2016" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
page_architectures \- Tests and Test Architectures 
Tests are given in the \fCfiles list\fP section\&. They are provided in the /tests/ folder within the distributed software\&.
.PP
In this page we intend to make a summary of all of the architectures in where the MTK has been tested\&. The MTK is intended to be as portable as possible throughout architectures\&. The following architectures have provided flawless installations of the API and correct execution of the tests and the examples:
.PP
.PP
.nf
1. Intel(R) Pentium(R) M CPU 1.73 GHz 2048 KB of cache and stepping of 8.
   Linux 3.2.0-23-generic-pae #36-Ubuntu SMP i386 GNU/Linux
   gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5)

2. Intel(R) Core(TM) i7-4700MQ CPU 2.40 GHz 6144 KB of cache and stepping of 3.
   Linux 3.13.0-67-generic #110-Ubuntu SMP x86_64 GNU/Linux
   gcc version 4.8.4 (Ubuntu 4.4.4-2ubuntu1~14.04)

3. Intel(R) Core(TM) i7-4600U CPU 2.10 GHz 4096 KB of cache and a stepping of 1.
   Linux 3.16.7-29-desktop #1 SMP PREEMPT (6be6a97) x86_64 GNU/Linux
   openSUSE 13.2 (Harlequin) (x86_64)
   gcc (SUSE Linux) 4.8.3 20140627 [gcc-4_8-branch revision 212064]
.fi
.PP
.PP
Further architectures will be tested! 
