.TH "page_ref_the" 3 "Mon Nov 30 2015" "MTK: Mimetic Methods Toolkit" \" -*- nroff -*-
.ad l
.nh
.SH NAME
page_ref_the \- User Manual, References and Theory 
The main source of references for this work can be found in:
.PP
http://www.csrc.sdsu.edu/mimetic-book/
.PP
However, a \&.PDF copy of this manual can be found \fChere\fP\&. 
