# Makefile for the examples folder.

examples:
	@( cd gradient_operators_1d; $(MAKE))
	@( cd divergence_operators_1d; $(MAKE))
	@( cd laplacian_operators_1d; $(MAKE))
	@( cd mimetic_threshold_div_grad; $(MAKE))
	@( cd poisson_1d; $(MAKE))
	@( cd minimalistic_poisson_1d; $(MAKE))
	@( cd poisson_2d; $(MAKE))
	@( cd curl_2d_angular_velocity; $(MAKE))
	@( cd diffusion_3d; $(MAKE))
	@( cd positive_weights_1d; $(MAKE))

clean:
	@( cd gradient_operators_1d; $(MAKE) clean )
	@( cd divergence_operators_1d; $(MAKE) clean )
	@( cd laplacian_operators_1d; $(MAKE) clean )
	@( cd mimetic_threshold_div_grad; $(MAKE) clean )
	@( cd poisson_1d; $(MAKE) clean )
	@( cd minimalistic_poisson_1d; $(MAKE) clean)
	@( cd poisson_2d; $(MAKE) clean )
	@( cd curl_2d_angular_velocity; $(MAKE) clean)
	@( cd diffusion_3d; $(MAKE) clean)
	@( cd positive_weights_1d; $(MAKE) clean)
