# Makefile for the examples folder.

examples:
	@( cd 1d_accuracy; $(MAKE))
	@( cd 1d_divergence; $(MAKE))
	@( cd 1d_gradient; $(MAKE))
	@( cd 1d_laplacian; $(MAKE))
	@( cd 1d_mimetic_measure; $(MAKE))
	@( cd 1d_mimetic_threshold; $(MAKE))
	@( cd 1d_poisson; $(MAKE))
	@( cd 1d_poisson_minimal; $(MAKE))
	@( cd 1d_positive_weights; $(MAKE))
	@( cd 2d_angular_velocity; $(MAKE))
	@( cd 2d_poisson; $(MAKE))
	@( cd 3d_diffusion; $(MAKE))

clean:
	@( cd 1d_accuracy; $(MAKE) clean )
	@( cd 1d_divergence; $(MAKE) clean )
	@( cd 1d_gradient; $(MAKE) clean )
	@( cd 1d_laplacian; $(MAKE) clean )
	@( cd 1d_mimetic_measure; $(MAKE) clean )
	@( cd 1d_mimetic_threshold; $(MAKE) clean )
	@( cd 1d_poisson; $(MAKE) clean )
	@( cd 1d_poisson_minimal; $(MAKE) clean )
	@( cd 1d_positive_weights; $(MAKE) clean )
	@( cd 2d_angular_velocity; $(MAKE) clean )
	@( cd 2d_poisson; $(MAKE) clean )
	@( cd 3d_diffusion; $(MAKE) clean )
