# Makefile for the examples folder.

examples:
	@( cd poisson_1d; $(MAKE))
	@( cd minimalistic_poisson_1d; $(MAKE))

clean:
	@( cd poisson_1d; $(MAKE) clean )
	@( cd minimalistic_poisson_1d; $(MAKE) clean)
