1d_poisson_minimal.cc
mtk::Real Alpha(const mtk::Real &tt, const std::vector< mtk::Real > &pp)
Referenced by main.
mtk::Real Beta(const mtk::Real &tt, const std::vector< mtk::Real > &pp)
Referenced by main.
mtk::Real Omega(const mtk::Real &tt)
Referenced by main.
mtk::Real Epsilon(const mtk::Real &tt)
Referenced by main.
mtk::Real Source(const mtk::Real &xx, const std::vector< mtk::Real > &pp)
Referenced by main.
mtk::Real KnownSolution(const mtk::Real &xx, const std::vector< mtk::Real > &pp)
Referenced by main.
int main()
References mtk::Lap1D::ConstructLap1D, mtk::Lap1D::ReturnAsDenseMatrix, mtk::UniStgGrid1D::BindScalarField, Source, mtk::RobinBCDescriptor1D::PushBackWestCoeff, Alpha, Beta, mtk::RobinBCDescriptor1D::PushBackEastCoeff, mtk::RobinBCDescriptor1D::set_west_condition, Omega, mtk::RobinBCDescriptor1D::set_east_condition, Epsilon, mtk::kOne, mtk::RobinBCDescriptor1D::ImposeOnLaplacianMatrix, mtk::RobinBCDescriptor1D::ImposeOnGrid, mtk::LAPACKAdapter::SolveDenseSystem, mtk::UniStgGrid1D::WriteToFile, KnownSolution, mtk::BLASAdapter::RelNorm2Error, mtk::UniStgGrid1D::discrete_field, mtk::UniStgGrid1D::num_cells_x.