mtk::UniStgGrid1D
FieldNature mtk::UniStgGrid1D::field_nature_
Nature of the discrete field.
Referenced by mtk::operator<<, operator=.
std::vector<Real> mtk::UniStgGrid1D::discrete_domain_x_
Array of spatial data.
Referenced by mtk::operator<<, operator=, UniStgGrid1D.
std::vector<Real> mtk::UniStgGrid1D::discrete_field_
Array of field's data.
Referenced by mtk::operator<<, operator=, UniStgGrid1D.
Real mtk::UniStgGrid1D::west_bndy_x_
West boundary spatial coordinate.
Referenced by mtk::operator<<, operator=.
Real mtk::UniStgGrid1D::east_bndy_x_
East boundary spatial coordinate.
Referenced by mtk::operator<<, operator=.
Real mtk::UniStgGrid1D::num_cells_x_
Number of cells discretizing the domain.
Referenced by mtk::operator<<, operator=.
Real mtk::UniStgGrid1D::delta_x_
Produced $ \Delta x $.
Referenced by operator=.
std::ostream& operator<<(std::ostream &stream, UniStgGrid1D &in)
Prints the grid as a tuple of arrays.
mtk::UniStgGrid1D & mtk::UniStgGrid1D::operator=(const UniStgGrid1D &in)
Overloaded assignment operator.
in Given grid. Copy of the given grid.
References field_nature_, west_bndy_x_, east_bndy_x_, num_cells_x_, delta_x_, discrete_domain_x_, discrete_field_.
mtk::UniStgGrid1D::UniStgGrid1D()
Default constructor.
mtk::UniStgGrid1D::UniStgGrid1D(const UniStgGrid1D &grid)
Copy constructor.
grid Given grid.
References discrete_domain_x_, discrete_field_.
mtk::UniStgGrid1D::UniStgGrid1D(const Real &west_bndy_x, const Real &east_bndy_x, const int &num_cells_x, const mtk::FieldNature &field_nature=mtk::FieldNature::SCALAR)
Construct a grid based on spatial discretization parameters.
west_bndy_x Coordinate for the west boundary. east_bndy_x Coordinate for the east boundary. num_cells_x Number of cells of the required grid. field_nature Nature of the discrete field to hold. mtk::FieldNature
References mtk::Tools::Prevent, mtk::kZero.
mtk::UniStgGrid1D::~UniStgGrid1D()
Destructor.
mtk::Real mtk::UniStgGrid1D::west_bndy_x() const
Provides access to west boundary spatial coordinate.
West boundary spatial coordinate.
mtk::Real mtk::UniStgGrid1D::east_bndy_x() const
Provides access to east boundary spatial coordinate.
East boundary spatial coordinate.
mtk::Real mtk::UniStgGrid1D::delta_x() const
Provides access to the computed $ x $.
Computed $ x $.
Referenced by mtk::Div1D::ReturnAsDenseMatrix, mtk::Grad1D::ReturnAsDenseMatrix, mtk::Lap1D::ConstructLap1D, mtk::Lap1D::ReturnAsDenseMatrix.
const mtk::Real * mtk::UniStgGrid1D::discrete_domain_x() const
Provides access to the grid spatial data.
Pointer to the spatial data. TodoReview const-correctness of the pointer we return.
mtk::Real * mtk::UniStgGrid1D::discrete_field()
Provides access to the grid field data.
Pointer to the field data. TodoReview const-correctness of the pointer we return. Look at the STL!
Referenced by mtk::LAPACKAdapter::SolveDenseSystem, mtk::OperatorApplicator::ApplyDenseMatrixGradientOn1DGrid, mtk::OperatorApplicator::ApplyDenseMatrixDivergenceOn1DGrid, mtk::OperatorApplicator::ApplyDenseMatrixLaplacianOn1DGrid, mtk::RobinBCDescriptor1D::ImposeOnGrid.
int mtk::UniStgGrid1D::num_cells_x() const
Provides access to the number of cells of the grid.
Number of cells of the grid.
Referenced by mtk::Div1D::ReturnAsDenseMatrix, mtk::Grad1D::ReturnAsDenseMatrix, mtk::Interp1D::ReturnAsDenseMatrix, mtk::Lap1D::ReturnAsDenseMatrix, mtk::RobinBCDescriptor1D::ImposeOnGrid.
mtk::FieldNature mtk::UniStgGrid1D::field_nature() const
Provides access to the field nature.
Nature of the filed on the grid.
Referenced by mtk::Div1D::ReturnAsDenseMatrix, mtk::Grad1D::ReturnAsDenseMatrix, mtk::OperatorApplicator::ApplyDenseMatrixGradientOn1DGrid, mtk::OperatorApplicator::ApplyDenseMatrixDivergenceOn1DGrid, mtk::OperatorApplicator::ApplyDenseMatrixLaplacianOn1DGrid.
void mtk::UniStgGrid1D::GenerateDiscreteDomainX()
Generates the actual set of spatial coordinates.
References mtk::Tools::Prevent, mtk::SCALAR.
void mtk::UniStgGrid1D::ReserveDiscreteField()
Allocates memory for the discrete set of field samples.
References mtk::Tools::Prevent, mtk::SCALAR.
void mtk::UniStgGrid1D::BindScalarField(Real(*ScalarField)(const Real &xx, const std::vector< Real > &pp), const std::vector< Real > &parameters=std::vector< Real >())
Binds a given scalar field to the grid.
ScalarField Pointer to the function implementing the scalar field. parameters Array of parameters for the field to be evaluated.
References mtk::Tools::Prevent, mtk::VECTOR.
void mtk::UniStgGrid1D::BindScalarField(const std::vector< Real > &samples)
Binds a given scalar field (as an array) to the grid.
samples Array of samples.
References mtk::Tools::Prevent, mtk::VECTOR.
void mtk::UniStgGrid1D::BindVectorField(Real(*VectorField)(const Real &xx, const std::vector< Real > &pp), const std::vector< Real > &parameters=std::vector< Real >())
Binds a given vector field to the grid.
We assume the field to be of the form: \[ \mathbf{v}(\mathbf{x}) = v(x)\hat{\mathbf{i}} \] VectorField Pointer to the function implementing the vector field. parameters Array of parameters for the field to be evaluated.
References mtk::Tools::Prevent, mtk::SCALAR.
bool mtk::UniStgGrid1D::WriteToFile(std::string filename, std::string space_name, std::string field_name) const
Writes grid to a file compatible with gnuplot 4.6.
filename Name of the output file. space_name Name for the first column of the data. field_name Name for the second column of the data. Success of the file writing process. http://www.gnuplot.info/