mtk::LAPACKAdapter
int mtk::LAPACKAdapter::SolveDenseSystem(mtk::DenseMatrix &mm, mtk::Real *rhs)
Solves a dense system of linear equations.
Adapts the MTK to LAPACK's dgesv_ routine. matrix Input matrix. rhs Input right-hand sides vector. std::bad_alloc
References mtk::Tools::Prevent, mtk::DenseMatrix::num_rows, mtk::DenseMatrix::data.
Referenced by mtk::Div1D::ComputeStencilInteriorGrid, mtk::Div1D::ComputeRationalBasisNullSpace, mtk::Grad1D::ComputeStencilInteriorGrid, mtk::Grad1D::ComputeRationalBasisNullSpace.
int mtk::LAPACKAdapter::SolveDenseSystem(mtk::DenseMatrix &mm, mtk::DenseMatrix &rr)
Solves a dense system of linear equations.
Adapts the MTK to LAPACK's dgesv_ routine. matrix Input matrix. rr Input right-hand sides matrix. std::bad_alloc
References mtk::DenseMatrix::num_rows, mtk::Tools::Prevent, mtk::DenseMatrix::data, mtk::DenseMatrix::SetOrdering, mtk::COL_MAJOR, mtk::DenseMatrix::OrderRowMajor.
int mtk::LAPACKAdapter::SolveDenseSystem(mtk::DenseMatrix &mm, mtk::UniStgGrid1D &rhs)
Solves a dense system of linear equations.
Adapts the MTK to LAPACK's dgesv_ routine. matrix Input matrix. rr Input right-hand side from info on a grid. std::bad_alloc
References mtk::DenseMatrix::num_rows, mtk::DenseMatrix::OrderColMajor, mtk::DenseMatrix::data, mtk::UniStgGrid1D::discrete_field_u, mtk::DenseMatrix::OrderRowMajor.
int mtk::LAPACKAdapter::SolveRectangularDenseSystem(const mtk::DenseMatrix &aa, mtk::Real *ob_, int ob_ld_)
Solves overdetermined or underdetermined real linear systems.
Adapts the MTK to LAPACK's routine. matrix Input matrix. Success of the solution. std::bad_alloc
References mtk::kZero, mtk::DenseMatrix::num_cols, mtk::DenseMatrix::num_rows, mtk::DenseMatrix::data, mtk::sgels_.
Referenced by mtk::Div1D::ComputePreliminaryApproximations, mtk::Div1D::ComputeWeights, mtk::Grad1D::ComputePreliminaryApproximations, mtk::Grad1D::ComputeWeights.
mtk::DenseMatrix mtk::LAPACKAdapter::QRFactorDenseMatrix(DenseMatrix &matrix)
Performs a QR factorization on a dense matrix.
Adapts the MTK to LAPACK's routine. matrix Input matrix. Matrix $ \mathbf{Q}$. std::bad_alloc
References mtk::kZero, mtk::DenseMatrix::data, mtk::DenseMatrix::num_cols, mtk::DenseMatrix::num_rows.
Referenced by mtk::Div1D::ComputeRationalBasisNullSpace, mtk::Grad1D::ComputeRationalBasisNullSpace.