mtk::UniStgGrid2D
std::vector<Real> mtk::UniStgGrid2D::discrete_domain_x_
Array of spatial data.
Referenced by mtk::operator<<, UniStgGrid2D.
std::vector<Real> mtk::UniStgGrid2D::discrete_domain_y_
Array of spatial data.
Referenced by mtk::operator<<, UniStgGrid2D.
std::vector<Real> mtk::UniStgGrid2D::discrete_field_
Array of field's data.
Referenced by mtk::operator<<, UniStgGrid2D.
FieldNature mtk::UniStgGrid2D::nature_
Nature of the discrete field.
Referenced by mtk::operator<<.
Real mtk::UniStgGrid2D::west_bndy_
West boundary spatial coordinate.
Referenced by mtk::operator<<.
Real mtk::UniStgGrid2D::east_bndy_
East boundary spatial coordinate.
Referenced by mtk::operator<<.
int mtk::UniStgGrid2D::num_cells_x_
Number of cells discretizing the domain.
Referenced by mtk::operator<<.
Real mtk::UniStgGrid2D::delta_x_
Computed $ \Delta x $.
Real mtk::UniStgGrid2D::south_bndy_
West boundary spatial coordinate.
Referenced by mtk::operator<<.
Real mtk::UniStgGrid2D::north_bndy_
East boundary spatial coordinate.
Referenced by mtk::operator<<.
int mtk::UniStgGrid2D::num_cells_y_
Number of cells discretizing the domain.
Referenced by mtk::operator<<.
Real mtk::UniStgGrid2D::delta_y_
Computed $ \Delta y $.
std::ostream& operator<<(std::ostream &stream, UniStgGrid2D &in)
Prints the grid as a tuple of arrays.
mtk::UniStgGrid2D::UniStgGrid2D()
Default constructor.
mtk::UniStgGrid2D::UniStgGrid2D(const UniStgGrid2D &grid)
Copy constructor.
grid Given grid.
References discrete_domain_x_, discrete_domain_y_, discrete_field_.
mtk::UniStgGrid2D::UniStgGrid2D(const Real &west_bndy_x, const Real &east_bndy_x, const int &num_cells_x, const Real &south_bndy_y, const Real &north_bndy_y, const int &num_cells_y, const mtk::FieldNature &nature=mtk::SCALAR)
Construct a grid based on spatial discretization parameters.
west_bndy_x Coordinate for the west boundary. east_bndy_x Coordinate for the east boundary. num_cells_x Number of cells of the required grid. south_bndy_y Coordinate for the west boundary. north_bndy_y Coordinate for the east boundary. num_cells_y Number of cells of the required grid. nature Nature of the discrete field to hold. mtk::FieldNature
References mtk::Tools::Prevent, mtk::kZero.
mtk::UniStgGrid2D::~UniStgGrid2D()
Destructor.
const mtk::Real * mtk::UniStgGrid2D::discrete_domain_x() const
Provides access to the grid spatial data.
Pointer to the spatial data. TodoReview const-correctness of the pointer we return.
Referenced by mtk::RobinBCDescriptor2D::ImposeOnSouthBoundaryWithSpace, mtk::RobinBCDescriptor2D::ImposeOnNorthBoundaryWithSpace.
const mtk::Real * mtk::UniStgGrid2D::discrete_domain_y() const
Provides access to the grid spatial data.
Pointer to the spatial data. TodoReview const-correctness of the pointer we return.
Referenced by mtk::RobinBCDescriptor2D::ImposeOnWestBoundaryWithSpace, mtk::RobinBCDescriptor2D::ImposeOnEastBoundaryWithSpace.
mtk::Real * mtk::UniStgGrid2D::discrete_field()
Provides access to the grid field data.
Pointer to the field data.
Referenced by mtk::LAPACKAdapter::SolveDenseSystem, mtk::RobinBCDescriptor2D::ImposeOnGrid.
mtk::FieldNature mtk::UniStgGrid2D::nature() const
Physical nature of the data bound to the grid.
Value of an enumeration. mtk::FieldNature
Referenced by mtk::RobinBCDescriptor2D::ImposeOnLaplacianMatrix, mtk::RobinBCDescriptor2D::ImposeOnGrid.
mtk::Real mtk::UniStgGrid2D::west_bndy() const
Provides access to west boundary spatial coordinate.
West boundary spatial coordinate.
Referenced by mtk::Curl2D::ConstructCurl2D, mtk::Div2D::ConstructDiv2D, mtk::Grad2D::ConstructGrad2D, mtk::RobinBCDescriptor2D::ImposeOnSouthBoundaryNoSpace, mtk::RobinBCDescriptor2D::ImposeOnNorthBoundaryNoSpace, mtk::RobinBCDescriptor2D::ImposeOnGrid.
mtk::Real mtk::UniStgGrid2D::east_bndy() const
Provides access to east boundary spatial coordinate.
East boundary spatial coordinate.
Referenced by mtk::Curl2D::ConstructCurl2D, mtk::Div2D::ConstructDiv2D, mtk::Grad2D::ConstructGrad2D, mtk::RobinBCDescriptor2D::ImposeOnSouthBoundaryNoSpace, mtk::RobinBCDescriptor2D::ImposeOnNorthBoundaryNoSpace, mtk::RobinBCDescriptor2D::ImposeOnGrid.
int mtk::UniStgGrid2D::num_cells_x() const
Provides access to the number of cells of the grid.
Number of cells of the grid.
Referenced by mtk::Curl2D::ConstructCurl2D, mtk::Div2D::ConstructDiv2D, mtk::Grad2D::ConstructGrad2D, mtk::RobinBCDescriptor2D::ImposeOnSouthBoundaryNoSpace, mtk::RobinBCDescriptor2D::ImposeOnSouthBoundaryWithSpace, mtk::RobinBCDescriptor2D::ImposeOnNorthBoundaryNoSpace, mtk::RobinBCDescriptor2D::ImposeOnNorthBoundaryWithSpace, mtk::RobinBCDescriptor2D::ImposeOnWestBoundaryNoSpace, mtk::RobinBCDescriptor2D::ImposeOnWestBoundaryWithSpace, mtk::RobinBCDescriptor2D::ImposeOnEastBoundaryNoSpace, mtk::RobinBCDescriptor2D::ImposeOnEastBoundaryWithSpace, mtk::RobinBCDescriptor2D::ImposeOnLaplacianMatrix, mtk::RobinBCDescriptor2D::ImposeOnGrid.
mtk::Real mtk::UniStgGrid2D::delta_x() const
Provides access to the computed $ x $.
Computed $ x $.
Referenced by mtk::RobinBCDescriptor2D::ImposeOnSouthBoundaryNoSpace, mtk::RobinBCDescriptor2D::ImposeOnNorthBoundaryNoSpace, mtk::RobinBCDescriptor2D::ImposeOnGrid.
mtk::Real mtk::UniStgGrid2D::south_bndy() const
Provides access to south boundary spatial coordinate.
South boundary spatial coordinate.
Referenced by mtk::Curl2D::ConstructCurl2D, mtk::Div2D::ConstructDiv2D, mtk::Grad2D::ConstructGrad2D, mtk::RobinBCDescriptor2D::ImposeOnWestBoundaryNoSpace, mtk::RobinBCDescriptor2D::ImposeOnEastBoundaryNoSpace, mtk::RobinBCDescriptor2D::ImposeOnGrid.
mtk::Real mtk::UniStgGrid2D::north_bndy() const
Provides access to north boundary spatial coordinate.
North boundary spatial coordinate.
Referenced by mtk::RobinBCDescriptor2D::ImposeOnWestBoundaryNoSpace, mtk::RobinBCDescriptor2D::ImposeOnEastBoundaryNoSpace, mtk::RobinBCDescriptor2D::ImposeOnGrid.
int mtk::UniStgGrid2D::num_cells_y() const
Provides access to the number of cells of the grid.
Number of cells of the grid.
Referenced by mtk::Curl2D::ConstructCurl2D, mtk::Div2D::ConstructDiv2D, mtk::Grad2D::ConstructGrad2D, mtk::RobinBCDescriptor2D::ImposeOnNorthBoundaryNoSpace, mtk::RobinBCDescriptor2D::ImposeOnNorthBoundaryWithSpace, mtk::RobinBCDescriptor2D::ImposeOnWestBoundaryNoSpace, mtk::RobinBCDescriptor2D::ImposeOnWestBoundaryWithSpace, mtk::RobinBCDescriptor2D::ImposeOnEastBoundaryNoSpace, mtk::RobinBCDescriptor2D::ImposeOnEastBoundaryWithSpace, mtk::RobinBCDescriptor2D::ImposeOnLaplacianMatrix, mtk::RobinBCDescriptor2D::ImposeOnGrid.
mtk::Real mtk::UniStgGrid2D::delta_y() const
Provides access to the computed $ y $.
Computed $ y $.
Referenced by mtk::RobinBCDescriptor2D::ImposeOnWestBoundaryNoSpace, mtk::RobinBCDescriptor2D::ImposeOnEastBoundaryNoSpace, mtk::RobinBCDescriptor2D::ImposeOnGrid.
bool mtk::UniStgGrid2D::Bound() const
Have any field been bound to the grid?
True is a field has been bound.
Referenced by mtk::RobinBCDescriptor2D::ImposeOnLaplacianMatrix.
int mtk::UniStgGrid2D::Size() const
Total number of samples in the grid.
Total number of samples in the grid.
void mtk::UniStgGrid2D::BindScalarField(Real(*ScalarField)(const Real &xx, const Real &yy))
Binds a given scalar field to the grid.
ScalarField Pointer to the function implementing the scalar field.
References mtk::Tools::Prevent.
void mtk::UniStgGrid2D::BindVectorField(Real(*VectorFieldPComponent)(const Real &xx, const Real &yy), Real(*VectorFieldQComponent)(const Real &xx, const Real &yy))
Binds a given vector field to the grid.
We assume the field to be of the form: \[ \mathbf{v}(\mathbf{x}) = p(x, y)\hat{\mathbf{i}} + q(x, y)\hat{\mathbf{j}} \] VectorFieldPComponent Pointer to the function implementing the $ p $ component of the vector field. VectorFieldPComponent Pointer to the function implementing the $ q $ component of the vector field.
References mtk::Tools::Prevent.
bool mtk::UniStgGrid2D::WriteToFile(std::string filename, std::string space_name_x, std::string space_name_y, std::string field_name) const
Writes grid to a file compatible with Gnuplot 4.6.
filename Name of the output file. space_name_x Name for the first column of the (spatial) data. space_name_y Name for the second column of the (spatial) data. field_name Name for the second column of the (physical field) data. Success of the file writing process. http://www.gnuplot.info/
References mtk::kZero.
void mtk::UniStgGrid2D::BindVectorFieldPComponent(Real(*VectorFieldPComponent)(const Real &xx, const Real &yy))
Binds a given component of a vector field to the grid.
We assume the field to be of the form: \[ \mathbf{v}(\mathbf{x}) = p(x, y)\hat{\mathbf{i}} + q(x, y)\hat{\mathbf{j}} \] BindVectorFieldPComponent Pointer to the function implementing the $ p $ component of the vector field.
void mtk::UniStgGrid2D::BindVectorFieldQComponent(Real(*VectorFieldQComponent)(const Real &xx, const Real &yy))
Binds a given component of a vector field to the grid.
We assume the field to be of the form: \[ \mathbf{v}(\mathbf{x}) = p(x, y)\hat{\mathbf{i}} + q(x, y)\hat{\mathbf{j}} \] BindVectorFieldQComponent Pointer to the function implementing the $ q $ component of the vector field.