mtk::Div1D
int mtk::Div1D::order_accuracy_
Order of numerical accuracy of the operator.
Referenced by mtk::operator<<.
int mtk::Div1D::dim_null_
Dim. null-space for boundary approximations.
Referenced by mtk::operator<<.
int mtk::Div1D::num_bndy_coeffs_
Req. coeffs. per bndy pt. uni. order accuracy.
Referenced by mtk::operator<<.
int mtk::Div1D::divergence_length_
Length of the output array.
int mtk::Div1D::minrow_
Row from the optimizer with the minimum rel. nor.
int mtk::Div1D::row_
Row currently processed by the optimizer.
DenseMatrix mtk::Div1D::rat_basis_null_space_
Rational b. null-space w. bndy.
Real* mtk::Div1D::coeffs_interior_
Interior stencil.
Real* mtk::Div1D::prem_apps_
2D array of boundary preliminary approximations.
Real* mtk::Div1D::weights_crs_
Array containing weights from CRSA.
Real* mtk::Div1D::weights_cbs_
Array containing weights from CBSA.
Real* mtk::Div1D::mim_bndy_
Array containing mimetic boundary approximations.
Real* mtk::Div1D::divergence_
Output array containing the operator and weights.
Referenced by mtk::operator<<.
Real mtk::Div1D::mimetic_threshold_
< Mimetic threshold.
std::ostream& operator<<(std::ostream &stream, Div1D &in)
Output stream operator for printing.
mtk::Div1D::Div1D()
Default constructor.
mtk::Div1D::Div1D(const Div1D &div)
Copy constructor.
div Given divergence.
mtk::Div1D::~Div1D()
Destructor.
bool mtk::Div1D::ConstructDiv1D(int order_accuracy=kDefaultOrderAccuracy, Real mimetic_threshold=kDefaultMimeticThreshold)
Factory method implementing the CBS Algorithm to build operator.
Success of the construction.
References mtk::Tools::Prevent, mtk::kZero, mtk::kCriticalOrderAccuracyDiv.
Referenced by mtk::Div2D::ConstructDiv2D, mtk::Lap1D::ConstructLap1D.
int mtk::Div1D::num_bndy_coeffs() const
Returns how many coefficients are approximating at the boundary.
How many coefficients are approximating at the boundary.
mtk::Real * mtk::Div1D::coeffs_interior() const
Returns coefficients for the interior of the grid.
Coefficients for the interior of the grid.
mtk::Real * mtk::Div1D::weights_crs(void) const
Return collection of weights as computed by the CRSA.
Collection of weights as computed by the CRSA.
mtk::Real * mtk::Div1D::weights_cbs(void) const
Return collection of weights as computed by the CBSA.
Collection of weights as computed by the CBSA.
mtk::DenseMatrix mtk::Div1D::mim_bndy() const
Return collection of mimetic approximations at the boundary.
Collection of mimetic approximations at the boundary.
References mtk::DenseMatrix::SetValue.
mtk::DenseMatrix mtk::Div1D::ReturnAsDenseMatrix(const UniStgGrid1D &grid) const
Return the operator as a dense matrix.
The operator as a dense matrix.
References mtk::UniStgGrid1D::num_cells_x, mtk::Tools::Prevent, mtk::kOne, mtk::UniStgGrid1D::delta_x, mtk::DenseMatrix::SetValue, mtk::kZero.
Referenced by mtk::Div2D::ConstructDiv2D, mtk::Lap1D::ConstructLap1D.
bool mtk::Div1D::ComputeStencilInteriorGrid(void)
Stage 1 of the CBS Algorithm.
Compute the stencil approximating the interior of the staggered grid.
References mtk::kZero, mtk::kOne, mtk::LAPACKAdapter::SolveDenseSystem.
bool mtk::Div1D::ComputeRationalBasisNullSpace(void)
Stage 2.1 of the CBS Algorithm.
Compute a rational basis for the null-space of the Vandermonde matrix approximating at the west boundary.
References mtk::kZero, mtk::kOne, mtk::LAPACKAdapter::QRFactorDenseMatrix, mtk::DenseMatrix::data, mtk::DenseMatrix::num_rows, mtk::DenseMatrix::num_cols, mtk::DenseMatrix::Transpose, mtk::LAPACKAdapter::SolveDenseSystem, mtk::BLASAdapter::RealDenseMM.
bool mtk::Div1D::ComputePreliminaryApproximations(void)
Stage 2.2 of the CBS Algorithm.
Compute the set of preliminary approximations on the boundary neighborhood.
References mtk::kZero, mtk::kOne, mtk::LAPACKAdapter::SolveRectangularDenseSystem, mtk::BLASAdapter::RealDenseMV.
bool mtk::Div1D::ComputeWeights(void)
Stage 2.3 of the CBS Algorithm.
Compute the set of mimetic weights to impose the mimetic condition.
References mtk::DenseMatrix::data, mtk::kZero, mtk::kOne, mtk::DenseMatrix::num_cols, mtk::DenseMatrix::Transpose, mtk::LAPACKAdapter::SolveRectangularDenseSystem, mtk::kCriticalOrderAccuracyDiv, mtk::BLASAdapter::RealNRM2, mtk::GLPKAdapter::SolveSimplexAndCompare.
bool mtk::Div1D::ComputeStencilBoundaryGrid(void)
Stage 2.4 of the CBS Algorithm.
Compute mimetic stencil approximating at boundary.
References mtk::kZero.
bool mtk::Div1D::AssembleOperator(void)
Stage 3 of the CBS Algorithm.
Construct the output array with the operator and its weights.
References mtk::kDefaultOrderAccuracy, mtk::kZero.