mtk::RobinBCDescriptor1D
int mtk::RobinBCDescriptor1D::highest_order_diff_west_
Highest order of differentiation west.
int mtk::RobinBCDescriptor1D::highest_order_diff_east_
Highest order of differentiation east.
std::vector<CoefficientFunction0D> mtk::RobinBCDescriptor1D::west_coefficients_
Coeffs. west.
std::vector<CoefficientFunction0D> mtk::RobinBCDescriptor1D::east_coefficients_
Coeffs. east.
Real(* mtk::RobinBCDescriptor1D::west_condition_)(const Real &tt))(const Real &tt)
Condition for west.
Real(* mtk::RobinBCDescriptor1D::east_condition_)(const Real &tt))(const Real &tt)
Condition for east.
mtk::RobinBCDescriptor1D::RobinBCDescriptor1D()
Default constructor.
mtk::RobinBCDescriptor1D::RobinBCDescriptor1D(const RobinBCDescriptor1D &desc)
Copy constructor.
desc Given 1D descriptor.
mtk::RobinBCDescriptor1D::~RobinBCDescriptor1D() noexcept
Destructor.
int mtk::RobinBCDescriptor1D::highest_order_diff_west() const noexcept
Getter for the highest order of differentiation in the west boundary.
Integer highest order of differentiation in the west boundary.
int mtk::RobinBCDescriptor1D::highest_order_diff_east() const noexcept
Getter for the highest order of differentiation in the east boundary.
Integer highest order of differentiation in the east boundary.
void mtk::RobinBCDescriptor1D::PushBackWestCoeff(CoefficientFunction0D cw)
Push back coefficient function at west of lowest order diff. available.
cw Function $ c_w(x,y):\Omega\mapsto\mathbb{R} $.
References mtk::Tools::Prevent.
Referenced by main.
void mtk::RobinBCDescriptor1D::PushBackEastCoeff(CoefficientFunction0D ce)
Push back coefficient function at east of lowest order diff. available.
ce Function $ c_e(x,y):\Omega\mapsto\mathbb{R} $.
References mtk::Tools::Prevent.
Referenced by main.
void mtk::RobinBCDescriptor1D::set_west_condition(Real(*west_condition)(const Real &tt)) noexcept
Set boundary condition at west.
west_condition $ \beta_w(y,t):\Omega\mapsto\mathbb{R} $.
References mtk::Tools::Prevent.
Referenced by main.
void mtk::RobinBCDescriptor1D::set_east_condition(Real(*east_condition)(const Real &tt)) noexcept
Set boundary condition at east.
east_condition $ \beta_e(y,t):\Omega\mapsto\mathbb{R} $.
References mtk::Tools::Prevent.
Referenced by main.
bool mtk::RobinBCDescriptor1D::ImposeOnDivergenceMatrix(const Div1D &div, DenseMatrix &matrix, const std::vector< Real > &parameters=std::vector< Real >(), const Real &time=mtk::kZero) const
Imposes the condition on the operator represented as matrix.
div Operator in the Matrix. matrix Input Divergence operator. time Current time snapshot. Default is kZero. Success of the imposition.
References mtk::Tools::Prevent, mtk::DenseMatrix::num_rows, mtk::DenseMatrix::num_cols, mtk::DenseMatrix::SetValue.
bool mtk::RobinBCDescriptor1D::ImposeOnLaplacianMatrix(const Lap1D &lap, DenseMatrix &matrix, const std::vector< Real > &parameters=std::vector< Real >(), const Real &time=mtk::kZero) const
Imposes the condition on the operator represented as matrix.
lap Operator in the Matrix. matrix Input Laplacian operator. time Current time snapshot. Default is kZero. Success of the imposition.
References mtk::Tools::Prevent, mtk::DenseMatrix::num_rows, mtk::DenseMatrix::num_cols, mtk::DenseMatrix::SetValue, mtk::Grad1D::ConstructGrad1D, mtk::Lap1D::order_accuracy, mtk::Lap1D::mimetic_threshold, mtk::Grad1D::mim_bndy, mtk::kOne, mtk::Lap1D::delta, mtk::DenseMatrix::GetValue.
Referenced by main.
void mtk::RobinBCDescriptor1D::ImposeOnGrid(UniStgGrid1D &grid, const Real &time=mtk::kZero) const
Imposes the condition on the grid.
grid Grid upon which impose the desired boundary condition. time Current time snapshot. Default is kZero.
References mtk::Tools::Prevent, mtk::UniStgGrid1D::num_cells_x, mtk::UniStgGrid1D::discrete_field.
Referenced by main.