mtk::UniStgGrid3D
std::vector<Real> mtk::UniStgGrid3D::discrete_domain_x_
Array of spatial data.
Referenced by mtk::operator<<, UniStgGrid3D.
std::vector<Real> mtk::UniStgGrid3D::discrete_domain_y_
Array of spatial data.
Referenced by mtk::operator<<, UniStgGrid3D.
std::vector<Real> mtk::UniStgGrid3D::discrete_domain_z_
Array of spatial data.
Referenced by mtk::operator<<, UniStgGrid3D.
std::vector<Real> mtk::UniStgGrid3D::discrete_field_
Array of field's data.
Referenced by mtk::operator<<, UniStgGrid3D.
FieldNature mtk::UniStgGrid3D::nature_
Nature of the discrete field.
Referenced by mtk::operator<<.
Real mtk::UniStgGrid3D::west_bndy_
West boundary spatial coordinate.
Referenced by mtk::operator<<.
Real mtk::UniStgGrid3D::east_bndy_
East boundary spatial coordinate.
Referenced by mtk::operator<<.
int mtk::UniStgGrid3D::num_cells_x_
Number of cells discretizing the domain.
Referenced by mtk::operator<<.
Real mtk::UniStgGrid3D::delta_x_
Computed $ \Delta x $.
Real mtk::UniStgGrid3D::south_bndy_
West boundary spatial coordinate.
Referenced by mtk::operator<<.
Real mtk::UniStgGrid3D::north_bndy_
East boundary spatial coordinate.
Referenced by mtk::operator<<.
int mtk::UniStgGrid3D::num_cells_y_
Number of cells discretizing the domain.
Referenced by mtk::operator<<.
Real mtk::UniStgGrid3D::delta_y_
Computed $ \Delta y $.
Real mtk::UniStgGrid3D::bottom_bndy_
Bottom boundary spatial coordinate.
Referenced by mtk::operator<<.
Real mtk::UniStgGrid3D::top_bndy_
Top boundary spatial coordinate.
Referenced by mtk::operator<<.
int mtk::UniStgGrid3D::num_cells_z_
Number of cells discretizing the domain.
Referenced by mtk::operator<<.
Real mtk::UniStgGrid3D::delta_z_
Computed $ \Delta z $.
std::ostream& operator<<(std::ostream &stream, UniStgGrid3D &in)
Prints the grid as a tuple of arrays.
mtk::UniStgGrid3D mtk::UniStgGrid3D::operator=(const UniStgGrid3D &in)
Overloaded assignment operator.
in Given grid. Copy of the given grid.
mtk::UniStgGrid3D::UniStgGrid3D()
Default constructor.
mtk::UniStgGrid3D::UniStgGrid3D(const UniStgGrid3D &grid)
Copy constructor.
grid Given grid.
References discrete_domain_x_, discrete_domain_y_, discrete_domain_z_, discrete_field_.
mtk::UniStgGrid3D::UniStgGrid3D(const Real &west_bndy_x, const Real &east_bndy_x, const int &num_cells_x, const Real &south_bndy_y, const Real &north_bndy_y, const int &num_cells_y, const Real &bottom_bndy_z, const Real &top_bndy_z, const int &num_cells_z, const mtk::FieldNature &nature=mtk::FieldNature::SCALAR)
Construct a grid based on spatial discretization parameters.
west_bndy_x Coordinate for the west boundary. east_bndy_x Coordinate for the east boundary. num_cells_x Number of cells of the required grid. south_bndy_y Coordinate for the west boundary. north_bndy_y Coordinate for the east boundary. num_cells_y Number of cells of the required grid. bottom_bndy_z Coordinate for the bottom boundary. top_bndy_z Coordinate for the top boundary. num_cells_z Number of cells of the required grid. nature Nature of the discrete field to hold. mtk::FieldNature
References mtk::Tools::Prevent, mtk::kZero.
mtk::UniStgGrid3D::~UniStgGrid3D()
Destructor.
const mtk::Real * mtk::UniStgGrid3D::discrete_domain_x() const
Provides access to the grid spatial data.
Pointer to the spatial data. TodoReview const-correctness of the pointer we return.
const mtk::Real * mtk::UniStgGrid3D::discrete_domain_y() const
Provides access to the grid spatial data.
Pointer to the spatial data. TodoReview const-correctness of the pointer we return.
const mtk::Real * mtk::UniStgGrid3D::discrete_domain_z() const
Provides access to the grid spatial data.
Pointer to the spatial data. TodoReview const-correctness of the pointer we return.
mtk::Real * mtk::UniStgGrid3D::discrete_field()
Provides access to the grid field data.
Pointer to the field data.
mtk::FieldNature mtk::UniStgGrid3D::nature() const
Physical nature of the data bound to the grid.
Value of an enumeration. mtk::FieldNature
mtk::Real mtk::UniStgGrid3D::west_bndy() const
Provides access to west boundary spatial coordinate.
West boundary spatial coordinate.
Referenced by mtk::Div3D::ConstructDiv3D, mtk::Grad3D::ConstructGrad3D, TestGetters.
mtk::Real mtk::UniStgGrid3D::east_bndy() const
Provides access to east boundary spatial coordinate.
East boundary spatial coordinate.
Referenced by mtk::Div3D::ConstructDiv3D, mtk::Grad3D::ConstructGrad3D, TestGetters.
int mtk::UniStgGrid3D::num_cells_x() const
Provides access to the number of cells of the grid.
Number of cells of the grid.
Referenced by mtk::Div3D::ConstructDiv3D, mtk::Grad3D::ConstructGrad3D, TestGetters.
mtk::Real mtk::UniStgGrid3D::delta_x() const
Provides access to the computed $ x $.
Computed $ x $.
Referenced by TestDefaultConstructor, TestConstructWithWestEastNumCellsXSouthNorthBndysNumCellsYOStreamOperator.
mtk::Real mtk::UniStgGrid3D::south_bndy() const
Provides access to south boundary spatial coordinate.
South boundary spatial coordinate.
Referenced by mtk::Div3D::ConstructDiv3D, mtk::Grad3D::ConstructGrad3D, TestGetters.
mtk::Real mtk::UniStgGrid3D::north_bndy() const
Provides access to north boundary spatial coordinate.
North boundary spatial coordinate.
Referenced by mtk::Grad3D::ConstructGrad3D, TestGetters.
int mtk::UniStgGrid3D::num_cells_y() const
Provides access to the number of cells of the grid.
Number of cells of the grid.
Referenced by mtk::Div3D::ConstructDiv3D, mtk::Grad3D::ConstructGrad3D, TestGetters.
mtk::Real mtk::UniStgGrid3D::delta_y() const
Provides access to the computed $ y $.
Computed $ y $.
Referenced by TestDefaultConstructor, TestConstructWithWestEastNumCellsXSouthNorthBndysNumCellsYOStreamOperator.
mtk::Real mtk::UniStgGrid3D::bottom_bndy() const
Provides access to bottom boundary spatial coordinate.
Bottom boundary spatial coordinate.
Referenced by mtk::Div3D::ConstructDiv3D, mtk::Grad3D::ConstructGrad3D, TestGetters.
mtk::Real mtk::UniStgGrid3D::top_bndy() const
Provides access to top boundary spatial coordinate.
Top boundary spatial coordinate.
Referenced by mtk::Div3D::ConstructDiv3D, mtk::Grad3D::ConstructGrad3D, TestGetters.
int mtk::UniStgGrid3D::num_cells_z() const
Provides access to the number of cells of the grid.
Number of cells of the grid.
Referenced by mtk::Div3D::ConstructDiv3D, mtk::Grad3D::ConstructGrad3D, TestGetters.
mtk::Real mtk::UniStgGrid3D::delta_z() const
Provides access to the computed $ z $.
Computed $ z $.
Referenced by TestDefaultConstructor.
bool mtk::UniStgGrid3D::Bound() const
Have any field been bound to the grid?
True is a field has been bound.
int mtk::UniStgGrid3D::Size() const
Total number of samples in the grid.
Total number of samples in the grid.
void mtk::UniStgGrid3D::BindScalarField(Real(*ScalarField)(const Real &xx, const Real &yy, const Real &zz))
Binds a given scalar field to the grid.
ScalarField Pointer to the function implementing the scalar field.
References mtk::Tools::Prevent, mtk::SCALAR, mtk::kTwo, ScalarField.
Referenced by TestBindScalarFieldWriteToFile.
void mtk::UniStgGrid3D::BindVectorField(Real(*VectorFieldPComponent)(const Real &xx, const Real &yy, const Real &zz), Real(*VectorFieldQComponent)(const Real &xx, const Real &yy, const Real &zz), Real(*VectorFieldRComponent)(const Real &xx, const Real &yy, const Real &zz))
Binds a given vector field to the grid.
We assume the field to be of the form: \[ \mathbf{v}(\mathbf{x}) = p(x, y, z)\hat{\mathbf{i}} + q(x, y, z)\hat{\mathbf{j}} + r(x, y, z)\hat{\mathbf{k}} \] VectorFieldPComponent Pointer to the function implementing the $ p $ component of the vector field. VectorFieldPComponent Pointer to the function implementing the $ q $ component of the vector field. VectorFieldRComponent Pointer to the function implementing the $ r $ component of the vector field.
References mtk::Tools::Prevent, mtk::VECTOR, VectorFieldPComponent, VectorFieldQComponent.
bool mtk::UniStgGrid3D::WriteToFile(std::string filename, std::string space_name_x, std::string space_name_y, std::string space_name_z, std::string field_name) const
Writes grid to a file compatible with Gnuplot 4.6.
filename Name of the output file. space_name_x Name for the first column of the (spatial) data. space_name_y Name for the second column of the (spatial) data. space_name_z Name for the third column of the (spatial) data. field_name Name for the second column of the (physical field) data. Success of the file writing process. http://www.gnuplot.info/
References mtk::SCALAR.
Referenced by TestBindScalarFieldWriteToFile.
void mtk::UniStgGrid3D::BindVectorFieldPComponent(Real(*VectorFieldPComponent)(const Real &xx, const Real &yy, const Real &zz))
Binds a given component of a vector field to the grid.
We assume the field to be of the form: \[ \mathbf{v}(\mathbf{x}) = p(x, y, z)\hat{\mathbf{i}} + q(x, y, z)\hat{\mathbf{j}} + r(x, y, z)\hat{\mathbf{k}} \] BindVectorFieldPComponent Pointer to the function implementing the $ p $ component of the vector field.
void mtk::UniStgGrid3D::BindVectorFieldQComponent(Real(*VectorFieldQComponent)(const Real &xx, const Real &yy, const Real &zz))
Binds a given component of a vector field to the grid.
We assume the field to be of the form: \[ \mathbf{v}(\mathbf{x}) = p(x, y, z)\hat{\mathbf{i}} + q(x, y, z)\hat{\mathbf{j}} + r(x, y, z)\hat{\mathbf{k}} \] BindVectorFieldQComponent Pointer to the function implementing the $ q $ component of the vector field.
void mtk::UniStgGrid3D::BindVectorFieldRComponent(Real(*VectorFieldRComponent)(const Real &xx, const Real &yy, const Real &zz))
Binds a given component of a vector field to the grid.
We assume the field to be of the form: \[ \mathbf{v}(\mathbf{x}) = p(x, y, z)\hat{\mathbf{i}} + q(x, y, z)\hat{\mathbf{j}} + r(x, y, z)\hat{\mathbf{k}} \] BindVectorFieldRComponent Pointer to the function implementing the $ r $ component of the vector field.