mtk::Tools
int mtk::Tools::test_number_
Current test being executed.
mtk::Real mtk::Tools::duration_
Duration of the current test.
clock_t mtk::Tools::begin_time_
Elapsed time on current test.
void mtk::Tools::Prevent(const bool complement, const char *const fname, int lineno, const char *const fxname) noexcept
Enforces preconditions by preventing their complements from occur.
http://stackoverflow.com/questions/8884335/print-the-file-name-line-number-and-function-name-of-a-calling-function-c-pro complement Complement of desired pre-condition. fname Name of the file being checked. lineno Number of the line where the check is executed. fxname Name of the module containing the check.
Referenced by mtk::BLASAdapter::RealNRM2, mtk::BLASAdapter::RealAXPY, mtk::BLASAdapter::RelNorm2Error, mtk::BLASAdapter::RealDenseMV, mtk::BLASAdapter::RealDenseMM, mtk::BLASAdapter::RealDenseSM, mtk::DenseMatrix::DenseMatrix, mtk::DenseMatrix::SetOrdering, mtk::DenseMatrix::set_encoded_operator, mtk::DenseMatrix::GetValue, mtk::DenseMatrix::SetValue, mtk::Div1D::ConstructDiv1D, mtk::Div1D::ReturnAsDenseMatrix, mtk::Div1D::ReturnAsDimensionlessDenseMatrix, mtk::Grad1D::ConstructGrad1D, mtk::Grad1D::ReturnAsDenseMatrix, mtk::Grad1D::ReturnAsDimensionlessDenseMatrix, mtk::Interp1D::ConstructInterp1D, mtk::Interp1D::ReturnAsDenseMatrix, mtk::Lap1D::ConstructLap1D, mtk::Lap1D::ReturnAsDenseMatrix, mtk::LAPACKAdapter::SolveDenseSystem, mtk::Matrix::set_encoded_operator, mtk::Matrix::set_storage, mtk::Matrix::set_ordering, mtk::Matrix::set_num_rows, mtk::Matrix::set_num_cols, mtk::Matrix::set_num_low_diags, mtk::Matrix::set_num_upp_diags, mtk::Matrix::set_num_null, mtk::Matrix::set_num_zero, mtk::Matrix::IncreaseNumNull, mtk::Matrix::DecreaseNumNull, mtk::Matrix::IncreaseNumZero, mtk::Matrix::DecreaseNumZero, mtk::Matrix::ComputeNumValues, mtk::Matrix::ComputeLeadingDimension, mtk::Matrix::ComputeBandwidth, mtk::Matrix::ComputeNumNonNull, mtk::Matrix::ComputeAbsDensity, mtk::Matrix::ComputeAbsSparsity, mtk::Matrix::ComputeNumNonZero, mtk::Matrix::ComputeRelDensity, mtk::Matrix::ComputeRelSparsity, mtk::OperatorApplicator::ApplyDenseMatrixGradientOn1DGrid, mtk::OperatorApplicator::ApplyDenseMatrixDivergenceOn1DGrid, mtk::OperatorApplicator::ApplyDenseMatrixLaplacianOn1DGrid, mtk::RobinBCDescriptor1D::PushBackWestCoeff, mtk::RobinBCDescriptor1D::PushBackEastCoeff, mtk::RobinBCDescriptor1D::set_west_condition, mtk::RobinBCDescriptor1D::set_east_condition, mtk::RobinBCDescriptor1D::ImposeOnDivergenceMatrix, mtk::RobinBCDescriptor1D::ImposeOnLaplacianMatrix, mtk::RobinBCDescriptor1D::ImposeOnGrid, mtk::RobinBCDescriptor2D::PushBackWestCoeff, mtk::RobinBCDescriptor2D::PushBackEastCoeff, mtk::RobinBCDescriptor2D::PushBackSouthCoeff, mtk::RobinBCDescriptor2D::PushBackNorthCoeff, mtk::RobinBCDescriptor2D::set_west_condition, mtk::RobinBCDescriptor2D::set_east_condition, mtk::RobinBCDescriptor2D::set_south_condition, mtk::RobinBCDescriptor2D::set_north_condition, mtk::RobinBCDescriptor2D::ImposeOnLaplacianMatrix, mtk::RobinBCDescriptor2D::ImposeOnGrid, BeginUnitTestNo, EndUnitTestNo, mtk::UniStgGrid1D::UniStgGrid1D, mtk::UniStgGrid1D::GenerateDiscreteDomainX, mtk::UniStgGrid1D::ReserveDiscreteField, mtk::UniStgGrid1D::BindScalarField, mtk::UniStgGrid1D::BindVectorField, mtk::UniStgGrid2D::UniStgGrid2D, mtk::UniStgGrid2D::BindScalarField, mtk::UniStgGrid2D::BindVectorField, mtk::UniStgGrid3D::UniStgGrid3D, mtk::UniStgGrid3D::BindScalarField, mtk::UniStgGrid3D::BindVectorField.
void mtk::Tools::BeginUnitTestNo(const int &nn) noexcept
Begins the execution of a unit test. Starts a timer.
nn Number of the test.
References Prevent.
Referenced by TestRealDenseMM, TestDefaultConstructor, TestConstructorWithNumRowsNumCols, TestConstructAsIdentity, TestConstructAsVandermonde, TestSetValueGetValue, TestConstructAsVandermondeTranspose, TestKron, TestConstructWithNumRowsNumColsAssignmentOperator, TestConstructAsVandermondeTransposeAssignmentOperator, TestDefaultConstructorFactoryMethodDefault, TestDefaultConstructorFactoryMethodFourthOrder, TestDefaultConstructorFactoryMethodSixthOrder, TestDefaultConstructorFactoryMethodEightOrderDefThreshold, TestDefaultConstructorFactoryMethodTenthOrderDefThreshold, TestDefaultConstructorFactoryMethodTwelfthOrderDefThreshold, TestDefaultConstructorFactoryMethodFourteenthOrderDefThreshold, TestSecondOrderReturnAsDenseMatrixWithGrid, TestFourthOrderReturnAsDenseMatrixWithGrid, TestSixthOrderReturnAsDenseMatrixWithGrid, TestDefaultConstructorFactory, TestReturnAsDenseMatrixWriteToFile, Test1, TestReturnAsDenseMatrixWithGrid, TestReturnAsDimensionlessDenseMatrix, TestWriteToFile, TestMimBndy, TestReturnAsDenseMatrix, TestDefaultConstructorGetters, TestSettersGettersCopyConstructor, TestIncreaseDecreaseNumNull, TestIncreaseDecreaseNumZero, TestPushBackImposeOnLaplacianMatrix, TestImposeOnGrid, TestConstructWithWestBndyEastBndyNumCellsOStreamOperatorBindScalarField, TestBindScalarFieldWriteToFile, TestBindVectorField, TestConstructWithWestEastNumCellsXSouthNorthBndysNumCellsYOStreamOperator, TestGetters.
void mtk::Tools::EndUnitTestNo(const int &nn) noexcept
Ends the execution of a unit test. Stops and reports wall-clock time.
nn Number of the test.
References Prevent.
Referenced by TestRealDenseMM, TestDefaultConstructor, TestConstructorWithNumRowsNumCols, TestConstructAsIdentity, TestConstructAsVandermonde, TestSetValueGetValue, TestConstructAsVandermondeTranspose, TestKron, TestConstructWithNumRowsNumColsAssignmentOperator, TestConstructAsVandermondeTransposeAssignmentOperator, TestDefaultConstructorFactoryMethodDefault, TestDefaultConstructorFactoryMethodFourthOrder, TestDefaultConstructorFactoryMethodSixthOrder, TestDefaultConstructorFactoryMethodEightOrderDefThreshold, TestDefaultConstructorFactoryMethodTenthOrderDefThreshold, TestDefaultConstructorFactoryMethodTwelfthOrderDefThreshold, TestDefaultConstructorFactoryMethodFourteenthOrderDefThreshold, TestSecondOrderReturnAsDenseMatrixWithGrid, TestFourthOrderReturnAsDenseMatrixWithGrid, TestSixthOrderReturnAsDenseMatrixWithGrid, TestDefaultConstructorFactory, TestReturnAsDenseMatrixWriteToFile, Test1, TestReturnAsDenseMatrixWithGrid, TestReturnAsDimensionlessDenseMatrix, TestWriteToFile, TestMimBndy, TestReturnAsDenseMatrix, TestDefaultConstructorGetters, TestSettersGettersCopyConstructor, TestIncreaseDecreaseNumNull, TestIncreaseDecreaseNumZero, TestPushBackImposeOnLaplacianMatrix, TestImposeOnGrid, TestConstructWithWestBndyEastBndyNumCellsOStreamOperatorBindScalarField, TestBindScalarFieldWriteToFile, TestBindVectorField, TestConstructWithWestEastNumCellsXSouthNorthBndysNumCellsYOStreamOperator, TestGetters.
void mtk::Tools::Assert(const bool &condition) noexcept
Asserts if the condition required to pass the unit test occurs.
condition Condition to be asserted.
Referenced by TestRealDenseMM, TestDefaultConstructor, TestConstructorWithNumRowsNumCols, TestConstructAsIdentity, TestConstructAsVandermonde, TestSetValueGetValue, TestConstructAsVandermondeTranspose, TestKron, TestConstructWithNumRowsNumColsAssignmentOperator, TestConstructAsVandermondeTransposeAssignmentOperator, TestDefaultConstructorFactoryMethodDefault, TestDefaultConstructorFactoryMethodFourthOrder, TestDefaultConstructorFactoryMethodSixthOrder, TestDefaultConstructorFactoryMethodEightOrderDefThreshold, TestDefaultConstructorFactoryMethodTenthOrderDefThreshold, TestDefaultConstructorFactoryMethodTwelfthOrderDefThreshold, TestDefaultConstructorFactoryMethodFourteenthOrderDefThreshold, TestSecondOrderReturnAsDenseMatrixWithGrid, TestDefaultConstructorFactory, TestReturnAsDenseMatrixWriteToFile, TestReturnAsDenseMatrixWithGrid, TestReturnAsDimensionlessDenseMatrix, TestWriteToFile, TestMimBndy, TestReturnAsDenseMatrix, TestDefaultConstructorGetters, TestSettersGettersCopyConstructor, TestIncreaseDecreaseNumNull, TestIncreaseDecreaseNumZero, TestPushBackImposeOnLaplacianMatrix, TestImposeOnGrid, TestConstructWithWestBndyEastBndyNumCellsOStreamOperatorBindScalarField, TestBindScalarFieldWriteToFile, TestBindVectorField, TestConstructWithWestEastNumCellsXSouthNorthBndysNumCellsYOStreamOperator, TestGetters.