mtk::DenseMatrix
Matrix mtk::DenseMatrix::matrix_properties_
Data related to the matrix nature.
Referenced by mtk::operator<<, operator=, DenseMatrix, Kron.
Real* mtk::DenseMatrix::data_
Array holding the data in contiguous position in memory.
Referenced by mtk::operator<<, operator=, DenseMatrix, Kron.
std::ostream& operator<<(std::ostream &stream, DenseMatrix &in)
Prints the matrix as a block of numbers (standard way).
mtk::DenseMatrix & mtk::DenseMatrix::operator=(const DenseMatrix &in)
Overloaded assignment operator.
in Given matrix. Copy of the given matrix.
References matrix_properties_, mtk::Matrix::set_encoded_operator, mtk::Matrix::encoded_operator, mtk::Matrix::set_storage, mtk::Matrix::storage, mtk::Matrix::set_ordering, mtk::Matrix::ordering, mtk::Matrix::num_rows, mtk::Matrix::set_num_rows, matrix_properties, mtk::Matrix::num_cols, mtk::Matrix::set_num_cols, mtk::Matrix::num_zero, mtk::Matrix::set_num_zero, mtk::Matrix::num_null, mtk::Matrix::set_num_null, num_rows, num_cols, data_, mtk::kZero.
bool mtk::DenseMatrix::operator==(const DenseMatrix &in)
Overloaded comparison operator.
References num_rows, num_cols, data, mtk::kDefaultTolerance.
mtk::DenseMatrix::DenseMatrix()
Default constructor.
References matrix_properties_, mtk::Matrix::set_encoded_operator, mtk::NOOP, mtk::Matrix::set_storage, mtk::DENSE, mtk::Matrix::set_ordering, mtk::ROW_MAJOR.
mtk::DenseMatrix::DenseMatrix(const DenseMatrix &in)
Copy constructor.
in Given matrix.
References matrix_properties_, mtk::Matrix::encoded_operator, mtk::Matrix::storage, mtk::Matrix::ordering, mtk::Matrix::num_rows, matrix_properties, mtk::Matrix::num_cols, mtk::Matrix::num_zero, mtk::Matrix::num_null, mtk::kZero, data_.
mtk::DenseMatrix::DenseMatrix(const int &num_rows, const int &num_cols)
Construct a dense matrix based on the given dimensions.
num_rows Number of rows of the required matrix. num_cols Number of rows of the required matrix. std::bad_alloc
References mtk::Tools::Prevent, mtk::NOOP, mtk::DENSE, mtk::ROW_MAJOR, mtk::kZero.
mtk::DenseMatrix::DenseMatrix(const int &rank, const bool &padded, const bool &transpose)
Construct a zero-rows-padded identity matrix.
Used in the construction of the mimetic operators.Def**. A padded matrix is a matrix with its first and last rows initialized to only zero values:\[ \bar{\mathbf{I}} = \left(\begin{array}{ccccc} 0 & 0 & 0 & \dots & 0 \\ 1 & 0 & 0 & \dots & 0 \\ 0 & 1 & 0 & \dots & 0 \\ \vdots & \vdots & \vdots & \ddots & \vdots \\ 0 & 0 & 0 & \dots & 1 \\ 0 & 0 & 0 & \dots & 0 \end{array}\right) \] rank Rank or number of rows/cols in square matrix. padded Should it be padded? transpose Should I return the transpose of the requested matrix? std::bad_alloc
References mtk::Tools::Prevent, mtk::NOOP, mtk::DENSE, mtk::ROW_MAJOR, mtk::kZero, mtk::kOne.
mtk::DenseMatrix::DenseMatrix(const Real *const gen, const int &gen_length, const int &pro_length, const bool &transpose)
Construct a dense Vandermonde matrix.
Def**. In linear algebra, a Vandermonde matrix is a matrix with terms of a geometric progression in each row. This progression uses the terms of a given generator vector:\[ \mathbf{V} = \left(\begin{array}{ccccc} 1 & \alpha_1 & \alpha_1^2 & \dots & \alpha_1^{n-1}\\ 1 & \alpha_2 & \alpha_2^2 & \dots & \alpha_2^{n-1}\\ 1 & \alpha_3 & \alpha_3^2 & \dots & \alpha_3^{n-1}\\ \vdots & \vdots & \vdots & \ddots &\vdots \\ 1 & \alpha_m & \alpha_m^2 & \dots & \alpha_m^{n-1} \end{array}\right) \]This constructor generates a Vandermonde matrix, as defined above.Obs**. It in important to understand that the generator vectors to be used are nothing but a very particular instance of a grid. These are little chunks, little samples, if you will, of a grid which is rectangular and uniform. So the selected samples, on the mtk::Div1D and mtk::Grad1D, basically represent the entire space, the entire grid. This is why nor the CRS nor the CBS algorithms may work for irregular geometries, such as curvilinear grids. gen Given generator vector. gen_length Length generator vector. pro_length Length the progression. transpose Should the transpose be created instead? std::bad_alloc
References mtk::Tools::Prevent, mtk::NOOP, mtk::DENSE, mtk::ROW_MAJOR, mtk::kZero.
mtk::DenseMatrix::~DenseMatrix()
Destructor.
mtk::EncodedOperator mtk::DenseMatrix::encoded_operator() const
Return operator encoded by this matrix.
Operator encoded by this matrix.
Referenced by mtk::OperatorApplicator::ApplyDenseMatrixGradientOn1DGrid, mtk::OperatorApplicator::ApplyDenseMatrixDivergenceOn1DGrid, mtk::OperatorApplicator::ApplyDenseMatrixLaplacianOn1DGrid.
void mtk::DenseMatrix::set_encoded_operator(const EncodedOperator &op)
Sets the encoded operator.
op Encoded operator.
References mtk::NOOP, mtk::GRADIENT, mtk::DIVERGENCE, mtk::INTERPOLATION, mtk::CURL, mtk::LAPLACIAN, mtk::Tools::Prevent.
Referenced by mtk::Curl2D::ConstructCurl2D, mtk::Div1D::ReturnAsDenseMatrix, mtk::Div1D::ReturnAsDimensionlessDenseMatrix, mtk::Grad1D::ReturnAsDenseMatrix, mtk::Grad1D::ReturnAsDimensionlessDenseMatrix, mtk::Interp1D::ReturnAsDenseMatrix, mtk::Lap1D::ConstructLap1D, mtk::Lap1D::ReturnAsDenseMatrix, TestSecondOrderReturnAsDenseMatrixWithGrid, TestReturnAsDenseMatrixWithGrid.
mtk::Matrix mtk::DenseMatrix::matrix_properties() const noexcept
Provides access to the matrix data.
Pointer to a Matrix.
Referenced by mtk::BLASAdapter::RealDenseMV, mtk::BLASAdapter::RealDenseMM, mtk::BLASAdapter::RealDenseSM, operator=, DenseMatrix.
int mtk::DenseMatrix::num_rows() const noexcept
Gets the number of rows.
Number of rows of the matrix.
Referenced by mtk::BLASAdapter::RealDenseMV, mtk::BLASAdapter::RealDenseMM, mtk::BLASAdapter::RealDenseSM, operator=, operator==, mtk::Div1D::ComputeRationalBasisNullSpace, mtk::Grad1D::ComputeRationalBasisNullSpace, mtk::LAPACKAdapter::SolveDenseSystem, mtk::LAPACKAdapter::QRFactorDenseMatrix, mtk::LAPACKAdapter::SolveRectangularDenseSystem, mtk::RobinBCDescriptor1D::ImposeOnDivergenceMatrix, mtk::RobinBCDescriptor1D::ImposeOnLaplacianMatrix, mtk::RobinBCDescriptor2D::ImposeOnSouthBoundaryNoSpace, mtk::RobinBCDescriptor2D::ImposeOnNorthBoundaryNoSpace, mtk::RobinBCDescriptor2D::ImposeOnWestBoundaryNoSpace, mtk::RobinBCDescriptor2D::ImposeOnEastBoundaryNoSpace, mtk::RobinBCDescriptor2D::ImposeOnLaplacianMatrix, TestConstructorWithNumRowsNumCols.
int mtk::DenseMatrix::num_cols() const noexcept
Gets the number of columns.
Number of columns of the matrix.
Referenced by mtk::BLASAdapter::RealDenseMV, mtk::BLASAdapter::RealDenseMM, mtk::BLASAdapter::RealDenseSM, operator=, operator==, mtk::Div1D::ComputeRationalBasisNullSpace, mtk::Div1D::ComputeWeights, mtk::Grad1D::ComputeRationalBasisNullSpace, mtk::Grad1D::ComputeWeights, mtk::LAPACKAdapter::QRFactorDenseMatrix, mtk::LAPACKAdapter::SolveRectangularDenseSystem, mtk::RobinBCDescriptor1D::ImposeOnDivergenceMatrix, mtk::RobinBCDescriptor1D::ImposeOnLaplacianMatrix, mtk::RobinBCDescriptor2D::ImposeOnSouthBoundaryNoSpace, mtk::RobinBCDescriptor2D::ImposeOnNorthBoundaryNoSpace, mtk::RobinBCDescriptor2D::ImposeOnWestBoundaryNoSpace, mtk::RobinBCDescriptor2D::ImposeOnEastBoundaryNoSpace, mtk::RobinBCDescriptor2D::ImposeOnLaplacianMatrix, TestConstructorWithNumRowsNumCols.
mtk::Real * mtk::DenseMatrix::data() const noexcept
Provides access to the matrix value array.
Pointer to an array of mtk::Real.
Referenced by mtk::BLASAdapter::RealDenseMV, mtk::BLASAdapter::RealDenseMM, mtk::BLASAdapter::RealDenseSM, operator==, mtk::Div1D::ComputeRationalBasisNullSpace, mtk::Div1D::ComputeWeights, mtk::Grad1D::ComputeRationalBasisNullSpace, mtk::Grad1D::ComputeWeights, mtk::Lap1D::data, mtk::LAPACKAdapter::SolveDenseSystem, mtk::LAPACKAdapter::QRFactorDenseMatrix, mtk::LAPACKAdapter::SolveRectangularDenseSystem, TestDefaultConstructor, TestConstructorWithNumRowsNumCols, TestSetValueGetValue.
void mtk::DenseMatrix::SetOrdering(mtk::MatrixOrdering oo) noexcept
Sets the ordering of the matrix.
oo Ordering. The required value at the specified coordinates.
References mtk::Tools::Prevent, mtk::ROW_MAJOR, mtk::COL_MAJOR.
Referenced by mtk::BLASAdapter::RealDenseMM, mtk::LAPACKAdapter::SolveDenseSystem.
mtk::Real mtk::DenseMatrix::GetValue(const int &row_coord, const int &col_coord) const noexcept
Gets a value on the given coordinates.
row_coord Row coordinate. col_coord Column coordinate. The required value at the specified coordinates.
References mtk::Tools::Prevent.
Referenced by mtk::Curl2D::ConstructCurl2D, mtk::Div2D::ConstructDiv2D, mtk::Div3D::ConstructDiv3D, mtk::Grad2D::ConstructGrad2D, mtk::Grad3D::ConstructGrad3D, mtk::Lap1D::ConstructLap1D, mtk::Lap1D::ReturnAsDenseMatrix, mtk::RobinBCDescriptor1D::ImposeOnLaplacianMatrix, mtk::RobinBCDescriptor2D::ImposeOnWestBoundaryNoSpace, mtk::RobinBCDescriptor2D::ImposeOnEastBoundaryNoSpace, TestSetValueGetValue, TestReturnAsDenseMatrixWithGrid.
void mtk::DenseMatrix::SetValue(const int &row_coord, const int &col_coord, const Real &val) noexcept
Sets a value on the given coordinates.
row_coord Row coordinate. col_coord Column coordinate. val Row Actual value to be inserted.
References mtk::Tools::Prevent.
Referenced by mtk::Curl2D::ConstructCurl2D, mtk::Div1D::mim_bndy, mtk::Div1D::ReturnAsDenseMatrix, mtk::Div1D::ReturnAsDimensionlessDenseMatrix, mtk::Div2D::ConstructDiv2D, mtk::Div3D::ConstructDiv3D, mtk::Grad1D::mim_bndy, mtk::Grad1D::ReturnAsDenseMatrix, mtk::Grad1D::ReturnAsDimensionlessDenseMatrix, mtk::Grad2D::ConstructGrad2D, mtk::Grad3D::ConstructGrad3D, mtk::Interp1D::ReturnAsDenseMatrix, mtk::Lap1D::ReturnAsDenseMatrix, mtk::RobinBCDescriptor1D::ImposeOnDivergenceMatrix, mtk::RobinBCDescriptor1D::ImposeOnLaplacianMatrix, mtk::RobinBCDescriptor2D::ImposeOnSouthBoundaryNoSpace, mtk::RobinBCDescriptor2D::ImposeOnSouthBoundaryWithSpace, mtk::RobinBCDescriptor2D::ImposeOnNorthBoundaryNoSpace, mtk::RobinBCDescriptor2D::ImposeOnNorthBoundaryWithSpace, mtk::RobinBCDescriptor2D::ImposeOnWestBoundaryNoSpace, mtk::RobinBCDescriptor2D::ImposeOnWestBoundaryWithSpace, mtk::RobinBCDescriptor2D::ImposeOnEastBoundaryNoSpace, mtk::RobinBCDescriptor2D::ImposeOnEastBoundaryWithSpace, TestRealDenseMM, TestConstructAsIdentity, TestConstructAsVandermonde, TestSetValueGetValue, TestConstructAsVandermondeTranspose, TestKron, TestConstructWithNumRowsNumColsAssignmentOperator, TestSecondOrderReturnAsDenseMatrixWithGrid, TestReturnAsDenseMatrixWithGrid.
void mtk::DenseMatrix::Transpose()
Transpose this matrix.
References mtk::kZero.
Referenced by mtk::Div1D::ComputeRationalBasisNullSpace, mtk::Div1D::ComputeWeights, mtk::Grad1D::ComputeRationalBasisNullSpace, mtk::Grad1D::ComputeWeights, TestConstructWithNumRowsNumColsAssignmentOperator, TestConstructAsVandermondeTransposeAssignmentOperator.
void mtk::DenseMatrix::OrderRowMajor()
Make the matrix row-wise ordered.
References mtk::COL_MAJOR, mtk::kZero, mtk::ROW_MAJOR.
Referenced by mtk::BLASAdapter::RealDenseMV, mtk::BLASAdapter::RealDenseMM, mtk::BLASAdapter::RealDenseSM, mtk::LAPACKAdapter::SolveDenseSystem.
void mtk::DenseMatrix::OrderColMajor()
Make the matrix column-wise ordered.
References mtk::ROW_MAJOR, mtk::kZero, mtk::COL_MAJOR.
Referenced by mtk::LAPACKAdapter::SolveDenseSystem.
bool mtk::DenseMatrix::WriteToFile(const std::string &filename) const
Writes matrix to a file compatible with Gnuplot 4.6.
filename Name of the output file. Success of the file writing process. http://www.gnuplot.info/
Referenced by TestReturnAsDenseMatrixWriteToFile, TestWriteToFile.
mtk::DenseMatrix mtk::DenseMatrix::Kron(const DenseMatrix &aa, const DenseMatrix &bb)
Construct a dense matrix based on the Kronecker product of arguments.
aa First matrix. bb Second matrix. std::bad_alloc TodoImplement Kronecker product using the BLAS.
References matrix_properties_, mtk::Matrix::num_rows, mtk::Matrix::num_cols, data_, mtk::Matrix::set_storage, mtk::DENSE, mtk::Matrix::set_ordering, mtk::ROW_MAJOR.
Referenced by mtk::Curl2D::ConstructCurl2D, mtk::Div2D::ConstructDiv2D, mtk::Div3D::ConstructDiv3D, mtk::Grad2D::ConstructGrad2D, mtk::Grad3D::ConstructGrad3D, TestKron.