mtk::BLASAdapter
mtk::Real mtk::BLASAdapter::RealNRM2(Real *in, int &in_length)
Compute the $ ||\mathbf{x}||_2 $ of given array $ \mathbf{x} $.
in Input array. in_length Length of the array. Norm-2 of the given array.
References mtk::Tools::Prevent, mtk::snrm2_.
Referenced by RelNorm2Error, mtk::Div1D::ComputeWeights, mtk::GLPKAdapter::SolveSimplexAndCompare, mtk::Grad1D::ComputeWeights.
void mtk::BLASAdapter::RealAXPY(Real alpha, Real *xx, Real *yy, int &in_length)
Real-Arithmetic Scalar-Vector plus a Vector.
Performs\[ \mathbf{y} := \alpha\mathbf{A}mathbf{x} + \mathbf{y} \] alpha Scalar of the first array. xx First array. yy Second array. in_length Lengths of the given arrays. Norm-2 of the given array.
References mtk::Tools::Prevent, mtk::saxpy_.
Referenced by RelNorm2Error.
mtk::Real mtk::BLASAdapter::RelNorm2Error(Real *computed, Real *known, int length)
Computes the relative norm-2 of the error.
We compute\[ \frac{||\mathbf{\tilde{x}} - \mathbf{x}||_2}{||\mathbf{x}||_2}. \] known Array containing the computed solution. computed Array containing the known solution (ref. solution). Relative norm-2 of the error, aka, the difference between the arrays.
References mtk::Tools::Prevent, RealNRM2, mtk::kOne, RealAXPY.
void mtk::BLASAdapter::RealDenseMV(Real &alpha, DenseMatrix &aa, Real *xx, Real &beta, Real *yy)
Real-Arithmetic General (Dense matrices) Matrix-Vector Multiplier.
Performs \[ \mathbf{y} := \alpha\mathbf{A}\mathbf{x} + \beta\mathbf{y} \] alpha First scalar. aa Given matrix. xx First vector. beta Second scalar. yy Second vector (output). http://ejspeiro.github.io/Netlib-and-CPP/
References mtk::DenseMatrix::matrix_properties, mtk::Matrix::ordering, mtk::COL_MAJOR, mtk::DenseMatrix::OrderRowMajor, mtk::DenseMatrix::num_rows, mtk::DenseMatrix::num_cols, mtk::DenseMatrix::data, mtk::sgemv_.
Referenced by mtk::Div1D::ComputePreliminaryApproximations, mtk::Grad1D::ComputePreliminaryApproximations, mtk::OperatorApplicator::ApplyDenseMatrixGradientOn1DGrid, mtk::OperatorApplicator::ApplyDenseMatrixDivergenceOn1DGrid, mtk::OperatorApplicator::ApplyDenseMatrixLaplacianOn1DGrid.
void mtk::BLASAdapter::RealDenseMV(Real &alpha, Real *aa, MatrixOrdering &ordering, int num_rows, int num_cols, int lda, Real *xx, Real &beta, Real *yy)
Real-Arithmetic General (Dense matrices) Matrix-Vector Multiplier.
Performs \[ \mathbf{y} := \alpha\mathbf{A}\mathbf{x} + \beta\mathbf{y} \] alpha First scalar. aa Given matrix. ordering Ordering of the matrix. num_rows Number of rows. num_cols Number of columns. lda Leading dimension. xx First vector. beta Second scalar. yy Second vector (output). http://ejspeiro.github.io/Netlib-and-CPP/
References mtk::Tools::Prevent, mtk::ROW_MAJOR, mtk::sgemv_.
mtk::DenseMatrix mtk::BLASAdapter::RealDenseMM(DenseMatrix &aa, DenseMatrix &bb)
Real-Arithmetic General (Dense matrices) Matrix-Matrix multiplier.
Performs:\[ \mathbf{C} := \mathbf{A}\mathbf{B} \] aa First matrix. bb Second matrix. http://ejspeiro.github.io/Netlib-and-CPP/
References mtk::Tools::Prevent, mtk::DenseMatrix::num_cols, mtk::DenseMatrix::num_rows, mtk::DenseMatrix::matrix_properties, mtk::Matrix::ordering, mtk::COL_MAJOR, mtk::DenseMatrix::OrderRowMajor, mtk::kOne, mtk::kZero, mtk::DenseMatrix::SetOrdering, mtk::DenseMatrix::data, mtk::sgemm_.
Referenced by mtk::Div1D::ComputeRationalBasisNullSpace, mtk::Grad1D::ComputeRationalBasisNullSpace, mtk::Lap1D::ConstructLap1D, mtk::Lap2D::ConstructLap2D, mtk::Lap3D::ConstructLap3D.
mtk::DenseMatrix mtk::BLASAdapter::RealDenseSM(Real alpha, DenseMatrix &aa)
Real-Arithmetic General (Dense matrices) Scalar-Matrix multiplier.
Performs:\[ \mathbf{B} := \alpha\mathbf{A} \] alpha Input scalar. aa Input matrix. http://ejspeiro.github.io/Netlib-and-CPP/
References mtk::Tools::Prevent, mtk::DenseMatrix::num_rows, mtk::DenseMatrix::num_cols, mtk::DenseMatrix::matrix_properties, mtk::Matrix::ordering, mtk::COL_MAJOR, mtk::DenseMatrix::OrderRowMajor, mtk::kZero, mtk::DenseMatrix::data, mtk::sgemm_.