mtk::Matrix
EncodedOperator mtk::Matrix::encoded_operator_
MatrixStorage mtk::Matrix::storage_
Type of mimetic operator encoded.
What type of matrix is this?
MatrixOrdering mtk::Matrix::ordering_
What kind of ordering is it following?
int mtk::Matrix::num_rows_
Number of rows.
int mtk::Matrix::num_cols_
Number of columns.
int mtk::Matrix::num_values_
Number of total values in matrix.
int mtk::Matrix::leading_dimension_
Elements between successive rows when row-major.
int mtk::Matrix::num_low_diags_
Number of lower diagonals on a banded matrix.
int mtk::Matrix::num_upp_diags_
Number of upper diagonals on a banded matrix.
int mtk::Matrix::bandwidth_
Bandwidth of the matrix.
int mtk::Matrix::num_null_
Number of null (no meaning) values.
int mtk::Matrix::num_non_null_
Number of null values.
Real mtk::Matrix::abs_density_
Absolute density of matrix.
Real mtk::Matrix::abs_sparsity_
Absolute sparsity of matrix.
int mtk::Matrix::num_zero_
Number of zeros (with meaning).
int mtk::Matrix::num_non_zero_
Number of non-zero values.
Real mtk::Matrix::rel_density_
Relative density of matrix.
Real mtk::Matrix::rel_sparsity_
Relative sparsity of matrix.
mtk::Matrix::Matrix()
Default constructor.
References mtk::NOOP, mtk::DENSE, mtk::ROW_MAJOR.
mtk::Matrix::Matrix(const Matrix &in)
Copy constructor.
in Given matrix.
mtk::Matrix::~Matrix() noexcept
Destructor.
mtk::EncodedOperator mtk::Matrix::encoded_operator() const noexcept
Gets the type of mimetic operator encoded by this matrix.
Type of mimetic operator encoded by this matrix. mtk::EncodedOperator.
Referenced by mtk::DenseMatrix::operator=, mtk::DenseMatrix::DenseMatrix, TestDefaultConstructorGetters, TestSettersGettersCopyConstructor, TestIncreaseDecreaseNumNull, TestIncreaseDecreaseNumZero.
mtk::MatrixStorage mtk::Matrix::storage() const noexcept
Gets the type of storage of this matrix.
Type of storage of this matrix. mtk::MatrixStorage.
Referenced by mtk::DenseMatrix::operator=, mtk::DenseMatrix::DenseMatrix, TestDefaultConstructorGetters, TestSettersGettersCopyConstructor, TestIncreaseDecreaseNumNull, TestIncreaseDecreaseNumZero.
mtk::MatrixOrdering mtk::Matrix::ordering() const noexcept
Gets the type of ordering of this matrix.
Type of ordering of this matrix. mtk::MatrixOrdering.
Referenced by mtk::BLASAdapter::RealDenseMV, mtk::BLASAdapter::RealDenseMM, mtk::BLASAdapter::RealDenseSM, mtk::operator<<, mtk::DenseMatrix::operator=, mtk::DenseMatrix::DenseMatrix, TestDefaultConstructorGetters, TestSettersGettersCopyConstructor, TestIncreaseDecreaseNumNull, TestIncreaseDecreaseNumZero.
int mtk::Matrix::num_rows() const noexcept
Gets the number of rows.
Number of rows of the matrix.
Referenced by mtk::operator<<, mtk::DenseMatrix::operator=, mtk::DenseMatrix::DenseMatrix, mtk::DenseMatrix::Kron, TestDefaultConstructorGetters, TestSettersGettersCopyConstructor, TestIncreaseDecreaseNumNull, TestIncreaseDecreaseNumZero.
int mtk::Matrix::num_cols() const noexcept
Gets the number of rows.
Number of rows of the matrix.
Referenced by mtk::operator<<, mtk::DenseMatrix::operator=, mtk::DenseMatrix::DenseMatrix, mtk::DenseMatrix::Kron, TestDefaultConstructorGetters, TestSettersGettersCopyConstructor, TestIncreaseDecreaseNumNull, TestIncreaseDecreaseNumZero.
int mtk::Matrix::num_values() const noexcept
Gets the number of values.
Number of values of the matrix.
Referenced by TestDefaultConstructorGetters, TestSettersGettersCopyConstructor, TestIncreaseDecreaseNumNull, TestIncreaseDecreaseNumZero.
int mtk::Matrix::leading_dimension() const noexcept
Gets the matrix' leading dimension.
Leading dimension of the data array is the number of elements between successive rows (for row major storage) in memory. Most of the cases, the leading dimension is the same as the number of columns.Leading dimension of the matrix.
Referenced by TestDefaultConstructorGetters, TestSettersGettersCopyConstructor, TestIncreaseDecreaseNumNull, TestIncreaseDecreaseNumZero.
int mtk::Matrix::num_zero() const noexcept
Gets the number of zeros.
Number of zeros of the matrix.
Referenced by mtk::DenseMatrix::operator=, mtk::DenseMatrix::DenseMatrix, TestDefaultConstructorGetters, TestSettersGettersCopyConstructor, TestIncreaseDecreaseNumNull, TestIncreaseDecreaseNumZero.
int mtk::Matrix::num_non_zero() const noexcept
Gets the number of non-zero values.
Number of non-zero values of the matrix.
Referenced by TestDefaultConstructorGetters, TestSettersGettersCopyConstructor, TestIncreaseDecreaseNumNull, TestIncreaseDecreaseNumZero.
int mtk::Matrix::num_null() const noexcept
Gets the number of null values.
Number of null values of the matrix. http://www.csrc.sdsu.edu/research_reports/CSRCR2013-01.pdf
Referenced by mtk::DenseMatrix::operator=, mtk::DenseMatrix::DenseMatrix, TestDefaultConstructorGetters, TestSettersGettersCopyConstructor, TestIncreaseDecreaseNumNull, TestIncreaseDecreaseNumZero.
int mtk::Matrix::num_non_null() const noexcept
Gets the number of non-null values.
Number of non-null values of the matrix. http://www.csrc.sdsu.edu/research_reports/CSRCR2013-01.pdf
Referenced by TestDefaultConstructorGetters, TestSettersGettersCopyConstructor, TestIncreaseDecreaseNumNull, TestIncreaseDecreaseNumZero.
int mtk::Matrix::num_low_diags() const noexcept
Gets the number of lower diagonals.
Number of lower diagonals.
Referenced by TestDefaultConstructorGetters, TestSettersGettersCopyConstructor.
int mtk::Matrix::num_upp_diags() const noexcept
Gets the number of upper diagonals.
Number of upper diagonals.
Referenced by TestDefaultConstructorGetters, TestSettersGettersCopyConstructor.
int mtk::Matrix::bandwidth() const noexcept
Gets the bandwidth.
Bandwidth of the matrix.
Referenced by TestDefaultConstructorGetters, TestSettersGettersCopyConstructor.
mtk::Real mtk::Matrix::abs_density() const noexcept
Gets the absolute density.
Absolute density of the matrix. http://www.csrc.sdsu.edu/research_reports/CSRCR2013-01.pdf
Referenced by TestDefaultConstructorGetters, TestSettersGettersCopyConstructor, TestIncreaseDecreaseNumNull, TestIncreaseDecreaseNumZero.
mtk::Real mtk::Matrix::rel_density() const noexcept
Gets the relative density.
Relative density of the matrix. http://www.csrc.sdsu.edu/research_reports/CSRCR2013-01.pdf
Referenced by TestDefaultConstructorGetters, TestSettersGettersCopyConstructor, TestIncreaseDecreaseNumNull, TestIncreaseDecreaseNumZero.
mtk::Real mtk::Matrix::abs_sparsity() const noexcept
Gets the Absolute sparsity.
Absolute sparsity of the matrix. http://www.csrc.sdsu.edu/research_reports/CSRCR2013-01.pdf
Referenced by TestDefaultConstructorGetters, TestSettersGettersCopyConstructor, TestIncreaseDecreaseNumNull, TestIncreaseDecreaseNumZero.
mtk::Real mtk::Matrix::rel_sparsity() const noexcept
Gets the Relative sparsity.
Relative sparsity of the matrix. http://www.csrc.sdsu.edu/research_reports/CSRCR2013-01.pdf
Referenced by TestDefaultConstructorGetters, TestSettersGettersCopyConstructor, TestIncreaseDecreaseNumNull, TestIncreaseDecreaseNumZero.
void mtk::Matrix::set_encoded_operator(const EncodedOperator &in) noexcept
Sets the type of encoded operator of the matrix.
in Type of encoded operator. mtk::EncodedOperator
References mtk::NOOP, mtk::GRADIENT, mtk::DIVERGENCE, mtk::INTERPOLATION, mtk::CURL, mtk::LAPLACIAN, mtk::Tools::Prevent.
Referenced by mtk::DenseMatrix::operator=, mtk::DenseMatrix::DenseMatrix, TestSettersGettersCopyConstructor, TestIncreaseDecreaseNumNull, TestIncreaseDecreaseNumZero.
void mtk::Matrix::set_storage(const MatrixStorage &tt) noexcept
Sets the storage type of the matrix.
tt Type of the matrix storage. mtk::MatrixStorage
References mtk::Tools::Prevent, mtk::DENSE, mtk::BANDED, mtk::CRS.
Referenced by mtk::DenseMatrix::operator=, mtk::DenseMatrix::DenseMatrix, mtk::DenseMatrix::Kron, TestSettersGettersCopyConstructor, TestIncreaseDecreaseNumNull, TestIncreaseDecreaseNumZero.
void mtk::Matrix::set_ordering(const MatrixOrdering &oo) noexcept
Sets the ordering of the matrix.
oo Ordering of the matrix. mtk::MatrixOrdering
References mtk::ROW_MAJOR, mtk::COL_MAJOR, mtk::Tools::Prevent.
Referenced by mtk::DenseMatrix::operator=, mtk::DenseMatrix::DenseMatrix, mtk::DenseMatrix::Kron, TestSettersGettersCopyConstructor, TestIncreaseDecreaseNumNull, TestIncreaseDecreaseNumZero.
void mtk::Matrix::set_num_rows(const int &num_rows) noexcept
Sets the number of rows of the matrix.
num_rows Number of rows.
References mtk::Tools::Prevent.
Referenced by mtk::DenseMatrix::operator=, TestSettersGettersCopyConstructor, TestIncreaseDecreaseNumNull, TestIncreaseDecreaseNumZero.
void mtk::Matrix::set_num_cols(const int &num_cols) noexcept
Sets the number of columns of the matrix.
num_cols Number of columns.
References mtk::Tools::Prevent.
Referenced by mtk::DenseMatrix::operator=, TestSettersGettersCopyConstructor, TestIncreaseDecreaseNumNull, TestIncreaseDecreaseNumZero.
void mtk::Matrix::set_num_low_diags(const int &num_low_diags) noexcept
Sets the number of lower diagonals of the matrix.
num_low_diags Number of lower diagonals.
References mtk::Tools::Prevent.
Referenced by TestSettersGettersCopyConstructor.
void mtk::Matrix::set_num_upp_diags(const int &num_upp_diags) noexcept
Sets the number of upper diagonals of the matrix.
num_upp_diags Number of upper diagonals.
References mtk::Tools::Prevent.
Referenced by TestSettersGettersCopyConstructor.
void mtk::Matrix::set_num_null(const int &num_null) noexcept
Sets the number of null elements of the matrix.
num_null Number of null elements.
References mtk::Tools::Prevent.
Referenced by mtk::DenseMatrix::operator=.
void mtk::Matrix::set_num_zero(const int &num_zero) noexcept
Sets the number of zeros of the matrix.
num_zero Number of zeros on the matrix.
References mtk::Tools::Prevent.
Referenced by mtk::DenseMatrix::operator=.
void mtk::Matrix::IncreaseNumNull() noexcept
Decreases the number of values that equal zero but with no meaning.
References mtk::Tools::Prevent.
Referenced by TestIncreaseDecreaseNumNull.
void mtk::Matrix::DecreaseNumNull() noexcept
Decreases the number of values that equal zero but with no meaning.
References mtk::Tools::Prevent.
Referenced by TestIncreaseDecreaseNumNull.
void mtk::Matrix::IncreaseNumZero() noexcept
Increases the number of values that equal zero but with meaning.
References mtk::Tools::Prevent.
Referenced by TestIncreaseDecreaseNumZero.
void mtk::Matrix::DecreaseNumZero() noexcept
Decreases the number of values that equal zero but with meaning.
References mtk::Tools::Prevent.
Referenced by TestIncreaseDecreaseNumZero.
int mtk::Matrix::ComputeNumValues(const int &num_rows, const int &num_cols) const noexcept
Computes the leading dimension of the matrix.
num_rows Number of rows. num_cols Number of columns. Number of values of the matrix.
References mtk::Tools::Prevent.
int mtk::Matrix::ComputeLeadingDimension(const int &num_rows, const int &num_cols) const noexcept
Computes the leading dimension of the matrix.
num_rows Number of rows. num_cols Number of columns. Leading dimension of the matrix.
References mtk::Tools::Prevent, mtk::ROW_MAJOR.
int mtk::Matrix::ComputeBandwidth(const int &num_low_diags, const int &num_upp_diags) const noexcept
Computes the bandwidth of the matrix.
num_low_diags Number of lower diagonals. num_upp_diags Number of upper diagonals. Bandwidth of the matrix.
References mtk::Tools::Prevent.
int mtk::Matrix::ComputeNumNonNull(const int &num_values, const int &num_null) const noexcept
Computes the number of non-null values of the matrix.
num_values Number of values of the matrix. num_null Number of null values of the matrix. Number of non-null values of the matrix.
References mtk::Tools::Prevent.
mtk::Real mtk::Matrix::ComputeAbsDensity(const int &num_non_null, const int &num_values) const noexcept
Computes the absolute density of the matrix.
Defined as \[ \frac{\textrm{num\_non\_null}}{\textrm{num\_values}}. \] num_non_null Number of non-null values of the matrix. num_values Number of total values of the matrix. Absolute density of the matrix.
References mtk::Tools::Prevent, mtk::kZero.
mtk::Real mtk::Matrix::ComputeAbsSparsity(const mtk::Real &absolute_density) const noexcept
Computes the absolute sparsity of the matrix.
Defined as \[ 1 - \frac{\textrm{num\_non\_null}}{\textrm{num\_values}}. \] absolute_density Absolute density of the matrix. Absolute sparsity of the matrix.
References mtk::Tools::Prevent, mtk::kOne.
int mtk::Matrix::ComputeNumNonZero(const int &num_values, const int &num_zero) const noexcept
Computes the number of non-zero values of the matrix.
num_values Number of values of the matrix. num_zero Number of zero values of the matrix. Number of non-zero values of the matrix.
References mtk::Tools::Prevent.
mtk::Real mtk::Matrix::ComputeRelDensity(const int &num_non_zero, const int &num_values) const noexcept
Computes the relative density of the matrix.
Defined as \[ \frac{\textrm{num\_non\_zero}}{\textrm{num\_values}}. \] num_non_zero Number of non-zero values of the matrix. num_values Number of total values of the matrix. Relative density of the matrix.
References mtk::Tools::Prevent, mtk::kZero, mtk::kOne.
mtk::Real mtk::Matrix::ComputeRelSparsity(const mtk::Real &relative_density) const noexcept
Computes the relative sparsity of the matrix.
Defined as \[ 1 - \frac{\textrm{num\_non\_zero}}{\textrm{num\_values}}. \] relative_density Relative density of the matrix. Relative sparsity of the matrix.
References mtk::Tools::Prevent, mtk::kOne.