mtk::Grad1D
int mtk::Grad1D::order_accuracy_
Order of numerical accuracy of the operator.
Referenced by mtk::operator<<.
int mtk::Grad1D::dim_null_
Dim. null-space for boundary approximations.
int mtk::Grad1D::num_bndy_approxs_
Req. approximations at and near the boundary.
Referenced by mtk::operator<<.
int mtk::Grad1D::num_bndy_coeffs_
Req. coeffs. per bndy pt. uni. order accuracy.
Referenced by mtk::operator<<.
int mtk::Grad1D::gradient_length_
Length of the output array.
int mtk::Grad1D::minrow_
Row from the optimizer with the minimum rel. nor.
int mtk::Grad1D::row_
Row currently processed by the optimizer.
int mtk::Grad1D::num_feasible_sols_
Number of feasible solutions for weights.
DenseMatrix mtk::Grad1D::rat_basis_null_space_
Rational b. null-space w. bndy.
Real* mtk::Grad1D::coeffs_interior_
Interior stencil.
Real* mtk::Grad1D::prem_apps_
2D array of boundary preliminary approximations.
Real* mtk::Grad1D::weights_crs_
Array containing weights from CRSA.
Real* mtk::Grad1D::weights_cbs_
Array containing weights from CBSA.
Real* mtk::Grad1D::mim_bndy_
Array containing mimetic boundary approximations.
Real* mtk::Grad1D::gradient_
Output array containing the operator and weights.
Referenced by mtk::operator<<.
Real mtk::Grad1D::mimetic_threshold_
< Mimetic threshold.
Real mtk::Grad1D::mimetic_measure_
< Mimetic measure.
std::vector<Real> mtk::Grad1D::sums_rows_mim_bndy_
Sum of each mimetic boundary row.
Referenced by mtk::operator<<.
std::ostream& operator<<(std::ostream &stream, Grad1D &in)
Output stream operator for printing.
mtk::Grad1D::Grad1D()
Default constructor.
mtk::Grad1D::Grad1D(const Grad1D &grad)
Copy constructor.
div Given divergence.
mtk::Grad1D::~Grad1D()
Destructor.
bool mtk::Grad1D::ConstructGrad1D(int order_accuracy=kDefaultOrderAccuracy, Real mimetic_threshold=kDefaultMimeticThreshold)
Factory method implementing the CBS Algorithm to build operator.
Success of the solution.
References mtk::Tools::Prevent, mtk::kZero, mtk::kCriticalOrderAccuracyGrad.
Referenced by mtk::Grad2D::ConstructGrad2D, mtk::Grad3D::ConstructGrad3D, mtk::Lap1D::ConstructLap1D, mtk::RobinBCDescriptor1D::ImposeOnLaplacianMatrix.
int mtk::Grad1D::num_bndy_coeffs() const
Returns how many coefficients are approximating at the boundary.
How many coefficients are approximating at the boundary.
mtk::Real * mtk::Grad1D::coeffs_interior() const
Returns coefficients for the interior of the grid.
Coefficients for the interior of the grid.
mtk::Real * mtk::Grad1D::weights_crs(void) const
Returns collection of weights as computed by the CRSA.
Success of the solution.
mtk::Real * mtk::Grad1D::weights_cbs(void) const
Returns collection of weights as computed by the CBSA.
Collection of weights as computed by the CBSA.
int mtk::Grad1D::num_feasible_sols() const
Return number of feasible solutions when using the CBSA for weights.
Return number of feasible solutions when using the CBSA for weights.
mtk::DenseMatrix mtk::Grad1D::mim_bndy() const
Return collection of mimetic approximations at the boundary.
Collection of mimetic approximations at the boundary.
References mtk::DenseMatrix::SetValue.
Referenced by mtk::RobinBCDescriptor1D::ImposeOnLaplacianMatrix.
std::vector< mtk::Real > mtk::Grad1D::sums_rows_mim_bndy() const
Return collection of row-sums mimetic approximations at the boundary.
Collection of row-sums mimetic approximations at the boundary.
mtk::Real mtk::Grad1D::mimetic_measure() const
Returns mimetic measure of the operator.
Real number which is the mimetic measure of the operator.
mtk::DenseMatrix mtk::Grad1D::ReturnAsDenseMatrix(Real west, Real east, int num_cells_x) const
Returns the operator as a dense matrix.
The operator as a dense matrix.
References mtk::Tools::Prevent, mtk::kOne, mtk::DenseMatrix::SetValue, mtk::kZero.
Referenced by mtk::Grad2D::ConstructGrad2D, mtk::Grad3D::ConstructGrad3D, mtk::Lap1D::ConstructLap1D.
mtk::DenseMatrix mtk::Grad1D::ReturnAsDenseMatrix(const UniStgGrid1D &grid) const
Returns the operator as a dense matrix.
The operator as a dense matrix.
References mtk::UniStgGrid1D::num_cells_x, mtk::Tools::Prevent, mtk::kOne, mtk::UniStgGrid1D::delta_x, mtk::DenseMatrix::SetValue, mtk::kZero.
mtk::DenseMatrix mtk::Grad1D::ReturnAsDimensionlessDenseMatrix(int num_cells_x) const
Returns the operator as a dimensionless dense matrix.
The operator as a dimensionless dense matrix.
References mtk::Tools::Prevent, mtk::DenseMatrix::SetValue, mtk::kZero.
bool mtk::Grad1D::ComputeStencilInteriorGrid(void)
Stage 1 of the CBS Algorithm.
Compute the stencil approximating the interior of the staggered grid.
References mtk::kZero, mtk::kOne, mtk::LAPACKAdapter::SolveDenseSystem.
bool mtk::Grad1D::ComputeRationalBasisNullSpace(void)
Stage 2.1 of the CBS Algorithm.
Compute a rational basis for the null-space of the Vandermonde matrix approximating at the west boundary.
References mtk::kZero, mtk::kOne, mtk::LAPACKAdapter::QRFactorDenseMatrix, mtk::DenseMatrix::data, mtk::DenseMatrix::num_rows, mtk::DenseMatrix::num_cols, mtk::DenseMatrix::Transpose, mtk::LAPACKAdapter::SolveDenseSystem, mtk::BLASAdapter::RealDenseMM.
bool mtk::Grad1D::ComputePreliminaryApproximations(void)
Stage 2.2 of the CBS Algorithm.
Compute the set of preliminary approximations on the boundary neighborhood.
References mtk::kZero, mtk::kOne, mtk::LAPACKAdapter::SolveRectangularDenseSystem, mtk::BLASAdapter::RealDenseMV.
bool mtk::Grad1D::ComputeWeights(void)
Stage 2.3 of the CBS Algorithm.
Compute the set of mimetic weights to impose the mimetic condition.
References mtk::DenseMatrix::data, mtk::kZero, mtk::kOne, mtk::DenseMatrix::num_cols, mtk::DenseMatrix::Transpose, mtk::LAPACKAdapter::SolveRectangularDenseSystem, mtk::kCriticalOrderAccuracyGrad, mtk::BLASAdapter::RealNRM2, mtk::GLPKAdapter::SolveSimplexAndCompare.
bool mtk::Grad1D::ComputeStencilBoundaryGrid(void)
Stage 2.4 of the CBS Algorithm.
Compute mimetic stencil approximating at boundary.
References mtk::kZero.
bool mtk::Grad1D::AssembleOperator(void)
Stage 3 of the CBS Algorithm.
Construct the output array with the operator and its weights.
References mtk::kZero, mtk::kDefaultOrderAccuracy.