mtk::Interp1D
DirInterp mtk::Interp1D::dir_interp_
Direction of interpolation.
int mtk::Interp1D::order_accuracy_
Order of numerical accuracy of the operator.
Referenced by mtk::operator<<.
Real* mtk::Interp1D::coeffs_interior_
Interior stencil.
Referenced by mtk::operator<<.
std::ostream& operator<<(std::ostream &stream, Interp1D &in)
Output stream operator for printing.
mtk::Interp1D::Interp1D()
Default constructor.
References mtk::SCALAR_TO_VECTOR.
mtk::Interp1D::Interp1D(const Interp1D &interp)
Copy constructor.
interp Given interpolation operator.
mtk::Interp1D::~Interp1D()
Destructor.
bool mtk::Interp1D::ConstructInterp1D(int order_accuracy=kDefaultOrderAccuracy, mtk::DirInterp dir=mtk::DirInterp::SCALAR_TO_VECTOR)
Factory method to build operator.
Success of the solution.
References mtk::Tools::Prevent, mtk::SCALAR_TO_VECTOR, mtk::VECTOR_TO_SCALAR, mtk::kZero, mtk::kOne.
Referenced by TestDefaultConstructorFactoryMethodDefault, TestReturnAsDenseMatrixWithGrid.
mtk::Real * mtk::Interp1D::coeffs_interior() const
Returns coefficients for the interior of the grid.
Coefficients for the interior of the grid.
mtk::DenseMatrix mtk::Interp1D::ReturnAsDenseMatrix(const UniStgGrid1D &grid) const
Returns the operator as a dense matrix.
The operator as a dense matrix.
References mtk::UniStgGrid1D::num_cells_x, mtk::Tools::Prevent, mtk::SCALAR_TO_VECTOR, mtk::DenseMatrix::set_encoded_operator, mtk::INTERPOLATION, mtk::DenseMatrix::SetValue, mtk::kOne.
Referenced by TestReturnAsDenseMatrixWithGrid.