mtk::Lap1D
int mtk::Lap1D::order_accuracy_
Order of numerical accuracy of the operator.
Referenced by mtk::operator<<.
int mtk::Lap1D::laplacian_length_
Length of the output array.
Real* mtk::Lap1D::laplacian_
Output array containing the operator and weights.
Referenced by mtk::operator<<.
Real mtk::Lap1D::delta_
< If 0.0, then this Laplacian is dimensionless.
Real mtk::Lap1D::mimetic_threshold_
< Mimetic threshold.
Real mtk::Lap1D::mimetic_measure_
< Mimetic measure.
std::vector<Real> mtk::Lap1D::sums_rows_mim_bndy_
Sum of each mimetic boundary row.
Referenced by mtk::operator<<.
std::ostream& operator<<(std::ostream &stream, Lap1D &in)
Output stream operator for printing.
mtk::Lap1D::Lap1D()
Default constructor.
mtk::Lap1D::Lap1D(const Lap1D &lap)
Copy constructor.
lap Given Laplacian.
mtk::Lap1D::~Lap1D()
Destructor.
int mtk::Lap1D::order_accuracy() const
Order of accuracy of the operator.
Order of accuracy of the operator.
Referenced by mtk::RobinBCDescriptor1D::ImposeOnLaplacianMatrix.
mtk::Real mtk::Lap1D::mimetic_threshold() const
Mimetic threshold used in the CBS algorithm to construct this operator.
Mimetic threshold used in the CBS algorithm to construct operator.
Referenced by mtk::RobinBCDescriptor1D::ImposeOnLaplacianMatrix.
mtk::Real mtk::Lap1D::delta() const
Value of $ \Delta x $ used be scaled. If 0, then dimensionless.
Value of $ \Delta x $ used be scaled. If 0, then dimensionless.
Referenced by mtk::RobinBCDescriptor1D::ImposeOnLaplacianMatrix.
bool mtk::Lap1D::ConstructLap1D(int order_accuracy=kDefaultOrderAccuracy, Real mimetic_threshold=kDefaultMimeticThreshold)
Factory method implementing the CBS Algorithm to build operator.
Success of the solution.
References mtk::Tools::Prevent, mtk::kZero, mtk::kCriticalOrderAccuracyDiv, mtk::Grad1D::ConstructGrad1D, mtk::Div1D::ConstructDiv1D, mtk::UniStgGrid1D::delta_x, mtk::Grad1D::ReturnAsDenseMatrix, mtk::Div1D::ReturnAsDenseMatrix, mtk::DenseMatrix::set_encoded_operator, mtk::LAPLACIAN, mtk::BLASAdapter::RealDenseMM, mtk::DenseMatrix::GetValue.
std::vector< mtk::Real > mtk::Lap1D::sums_rows_mim_bndy() const
Return collection of row-sums mimetic approximations at the boundary.
Collection of row-sums mimetic approximations at the boundary.
mtk::Real mtk::Lap1D::mimetic_measure() const
Returns mimetic measure of the operator.
Real number which is the mimetic measure of the operator.
mtk::DenseMatrix mtk::Lap1D::ReturnAsDenseMatrix(const UniStgGrid1D &grid) const
Return the operator as a dense matrix.
The operator as a dense matrix.
References mtk::UniStgGrid1D::num_cells_x, mtk::Tools::Prevent, mtk::DenseMatrix::set_encoded_operator, mtk::LAPLACIAN, mtk::UniStgGrid1D::delta_x, mtk::kOne, mtk::DenseMatrix::SetValue, mtk::DenseMatrix::GetValue.
const mtk::Real * mtk::Lap1D::data(const UniStgGrid1D &grid) const
Return the operator as a dense array.
The operator as a dense array.
References mtk::DenseMatrix::data.