mtk_div_1d_test.cc
void TestDefaultConstructorFactoryMethodDefault()
References mtk::Tools::BeginUnitTestNo, mtk::Div1D::ConstructDiv1D, mtk::Tools::EndUnitTestNo, mtk::Tools::Assert.
Referenced by main.
void TestDefaultConstructorFactoryMethodFourthOrder()
References mtk::Tools::BeginUnitTestNo, mtk::Div1D::ConstructDiv1D, mtk::Tools::EndUnitTestNo, mtk::Tools::Assert.
Referenced by main.
void TestDefaultConstructorFactoryMethodSixthOrder()
References mtk::Tools::BeginUnitTestNo, mtk::Div1D::ConstructDiv1D, mtk::Tools::EndUnitTestNo, mtk::Tools::Assert.
Referenced by main.
void TestDefaultConstructorFactoryMethodEightOrderDefThreshold()
References mtk::Tools::BeginUnitTestNo, mtk::Div1D::ConstructDiv1D, mtk::Tools::EndUnitTestNo, mtk::Tools::Assert.
Referenced by main.
void TestDefaultConstructorFactoryMethodTenthOrderDefThreshold()
References mtk::Tools::BeginUnitTestNo, mtk::Div1D::ConstructDiv1D, mtk::Tools::EndUnitTestNo, mtk::Tools::Assert.
Referenced by main.
void TestDefaultConstructorFactoryMethodTwelfthOrderDefThreshold()
References mtk::Tools::BeginUnitTestNo, mtk::Div1D::ConstructDiv1D, mtk::Tools::EndUnitTestNo, mtk::Tools::Assert.
Referenced by main.
void TestDefaultConstructorFactoryMethodFourteenthOrderDefThreshold()
References mtk::Tools::BeginUnitTestNo, mtk::Div1D::ConstructDiv1D, mtk::Tools::EndUnitTestNo, mtk::Tools::Assert.
Referenced by main.
void TestSecondOrderReturnAsDenseMatrixWithGrid()
References mtk::Tools::BeginUnitTestNo, mtk::Div1D::ConstructDiv1D, mtk::VECTOR, mtk::Div1D::ReturnAsDenseMatrix, cc, mtk::DenseMatrix::set_encoded_operator, mtk::DIVERGENCE, mtk::DenseMatrix::SetValue, mtk::Tools::EndUnitTestNo, mtk::Tools::Assert.
Referenced by main.
void TestFourthOrderReturnAsDenseMatrixWithGrid()
References mtk::Tools::BeginUnitTestNo, mtk::Div1D::ConstructDiv1D, mtk::VECTOR, mtk::Div1D::ReturnAsDimensionlessDenseMatrix, mtk::Tools::EndUnitTestNo.
Referenced by main.
void TestSixthOrderReturnAsDenseMatrixWithGrid()
References mtk::Tools::BeginUnitTestNo, mtk::Div1D::ConstructDiv1D, mtk::VECTOR, mtk::Div1D::ReturnAsDimensionlessDenseMatrix, mtk::Tools::EndUnitTestNo.
Referenced by main.
int main()
References TestDefaultConstructorFactoryMethodDefault, TestDefaultConstructorFactoryMethodFourthOrder, TestDefaultConstructorFactoryMethodSixthOrder, TestDefaultConstructorFactoryMethodEightOrderDefThreshold, TestDefaultConstructorFactoryMethodTenthOrderDefThreshold, TestDefaultConstructorFactoryMethodTwelfthOrderDefThreshold, TestDefaultConstructorFactoryMethodFourteenthOrderDefThreshold, TestSecondOrderReturnAsDenseMatrixWithGrid, TestFourthOrderReturnAsDenseMatrixWithGrid, TestSixthOrderReturnAsDenseMatrixWithGrid.