mtk_uni_stg_grid_1d_test.cc
void TestDefaultConstructor()
References mtk::Tools::BeginUnitTestNo, mtk::Tools::EndUnitTestNo, mtk::Tools::Assert, mtk::UniStgGrid1D::delta_x, mtk::kZero.
Referenced by main.
mtk::Real ScalarField(const mtk::Real &xx, const std::vector< mtk::Real > &pp)
Referenced by TestConstructWithWestBndyEastBndyNumCellsOStreamOperatorBindScalarField, TestBindScalarFieldWriteToFile.
void TestConstructWithWestBndyEastBndyNumCellsOStreamOperatorBindScalarField()
References mtk::Tools::BeginUnitTestNo, mtk::UniStgGrid1D::BindScalarField, ScalarField, mtk::Tools::EndUnitTestNo, mtk::Tools::Assert, mtk::UniStgGrid1D::delta_x, mtk::UniStgGrid1D::num_cells_x.
Referenced by main.
void TestBindScalarFieldWriteToFile()
References mtk::Tools::BeginUnitTestNo, mtk::UniStgGrid1D::BindScalarField, ScalarField, mtk::UniStgGrid1D::discrete_field, mtk::UniStgGrid1D::num_cells_x, mtk::UniStgGrid1D::WriteToFile, mtk::Tools::EndUnitTestNo, mtk::Tools::Assert.
Referenced by main.
mtk::Real VectorFieldPComponent(const mtk::Real &xx, const std::vector< mtk::Real > &pp)
Referenced by mtk::UniStgGrid2D::BindVectorField, mtk::UniStgGrid3D::BindVectorField, TestBindVectorField.
void TestBindVectorField()
References mtk::Tools::BeginUnitTestNo, mtk::VECTOR, mtk::UniStgGrid1D::BindVectorField, VectorFieldPComponent, mtk::UniStgGrid1D::discrete_field, mtk::UniStgGrid1D::num_cells_x, mtk::UniStgGrid1D::WriteToFile, mtk::Tools::EndUnitTestNo, mtk::Tools::Assert.
Referenced by main.
int main()
References TestDefaultConstructor, TestConstructWithWestBndyEastBndyNumCellsOStreamOperatorBindScalarField, TestBindScalarFieldWriteToFile, TestBindVectorField.