mtk_grad_1d_test.cc
void TestDefaultConstructorFactoryMethodDefault()
References mtk::Tools::BeginUnitTestNo, mtk::Grad1D::ConstructGrad1D, mtk::Tools::EndUnitTestNo, mtk::Tools::Assert.
Referenced by main.
void TestDefaultConstructorFactoryMethodFourthOrder()
References mtk::Tools::BeginUnitTestNo, mtk::Grad1D::ConstructGrad1D, mtk::Tools::EndUnitTestNo, mtk::Tools::Assert.
Referenced by main.
void TestDefaultConstructorFactoryMethodSixthOrder()
References mtk::Tools::BeginUnitTestNo, mtk::Grad1D::ConstructGrad1D, mtk::Tools::EndUnitTestNo, mtk::Tools::Assert.
Referenced by main.
void TestDefaultConstructorFactoryMethodEightOrderDefThreshold()
References mtk::Tools::BeginUnitTestNo, mtk::Grad1D::ConstructGrad1D, mtk::Tools::EndUnitTestNo, mtk::Tools::Assert.
Referenced by main.
void TestDefaultConstructorFactoryMethodTenthOrderDefThreshold()
References mtk::Tools::BeginUnitTestNo, mtk::Grad1D::ConstructGrad1D, mtk::Tools::EndUnitTestNo, mtk::Tools::Assert.
Referenced by main.
void TestReturnAsDenseMatrixWithGrid()
References mtk::Tools::BeginUnitTestNo, mtk::Grad1D::ConstructGrad1D, mtk::Grad1D::ReturnAsDenseMatrix, cc, mtk::DenseMatrix::set_encoded_operator, mtk::GRADIENT, mtk::DenseMatrix::SetValue, mtk::Tools::EndUnitTestNo, mtk::Tools::Assert.
Referenced by main.
void TestReturnAsDimensionlessDenseMatrix()
References mtk::Tools::BeginUnitTestNo, mtk::Grad1D::ConstructGrad1D, mtk::Grad1D::ReturnAsDimensionlessDenseMatrix, mtk::Tools::EndUnitTestNo, mtk::Tools::Assert.
Referenced by main.
void TestWriteToFile()
References mtk::Tools::BeginUnitTestNo, mtk::Grad1D::ConstructGrad1D, mtk::Grad1D::ReturnAsDenseMatrix, mtk::DenseMatrix::WriteToFile, mtk::Tools::EndUnitTestNo, mtk::Tools::Assert.
Referenced by main.
void TestMimBndy()
References mtk::Tools::BeginUnitTestNo, mtk::Grad1D::ConstructGrad1D, mtk::Grad1D::mim_bndy, mtk::Tools::EndUnitTestNo, mtk::Tools::Assert.
Referenced by main.
int main()
References TestDefaultConstructorFactoryMethodDefault, TestDefaultConstructorFactoryMethodFourthOrder, TestDefaultConstructorFactoryMethodSixthOrder, TestDefaultConstructorFactoryMethodEightOrderDefThreshold, TestDefaultConstructorFactoryMethodTenthOrderDefThreshold, TestReturnAsDenseMatrixWithGrid, TestReturnAsDimensionlessDenseMatrix, TestWriteToFile, TestMimBndy.