mtk_robin_bc_descriptor_2d_test.cc
void TestDefaultConstructorGetters()
References mtk::Tools::BeginUnitTestNo, mtk::RobinBCDescriptor2D::highest_order_diff_west, mtk::RobinBCDescriptor2D::highest_order_diff_east, mtk::RobinBCDescriptor2D::highest_order_diff_south, mtk::RobinBCDescriptor2D::highest_order_diff_north, mtk::Tools::EndUnitTestNo, mtk::Tools::Assert.
Referenced by main.
mtk::Real cc(const mtk::Real &xx, const mtk::Real &yy)
References mtk::kOne.
Referenced by mtk::Div1D::ReturnAsDenseMatrix, mtk::Div1D::ReturnAsDimensionlessDenseMatrix, mtk::Grad1D::ReturnAsDenseMatrix, mtk::Grad1D::ReturnAsDimensionlessDenseMatrix, mtk::Lap1D::ReturnAsDenseMatrix, mtk::RobinBCDescriptor2D::ImposeOnSouthBoundaryNoSpace, mtk::RobinBCDescriptor2D::ImposeOnSouthBoundaryWithSpace, mtk::RobinBCDescriptor2D::ImposeOnNorthBoundaryNoSpace, mtk::RobinBCDescriptor2D::ImposeOnNorthBoundaryWithSpace, mtk::RobinBCDescriptor2D::ImposeOnWestBoundaryNoSpace, mtk::RobinBCDescriptor2D::ImposeOnWestBoundaryWithSpace, mtk::RobinBCDescriptor2D::ImposeOnEastBoundaryNoSpace, mtk::RobinBCDescriptor2D::ImposeOnEastBoundaryWithSpace, mtk::operator<<, TestRealDenseMM, TestConstructorWithNumRowsNumCols, TestSetValueGetValue, TestSecondOrderReturnAsDenseMatrixWithGrid, TestDefaultConstructorFactory, TestReturnAsDenseMatrixWriteToFile, TestReturnAsDenseMatrixWithGrid, TestPushBackImposeOnLaplacianMatrix, TestImposeOnGrid, TestConstructWithWestEastNumCellsXSouthNorthBndysNumCellsYOStreamOperator, TestGetters, TestBindScalarFieldWriteToFile, TestBindVectorField.
void TestPushBackImposeOnLaplacianMatrix()
References mtk::Tools::BeginUnitTestNo, mtk::RobinBCDescriptor2D::PushBackWestCoeff, cc, mtk::RobinBCDescriptor2D::PushBackEastCoeff, mtk::RobinBCDescriptor2D::PushBackSouthCoeff, mtk::RobinBCDescriptor2D::PushBackNorthCoeff, mtk::RobinBCDescriptor2D::highest_order_diff_west, mtk::RobinBCDescriptor2D::highest_order_diff_east, mtk::RobinBCDescriptor2D::highest_order_diff_south, mtk::RobinBCDescriptor2D::highest_order_diff_north, mtk::Lap2D::ConstructLap2D, mtk::Lap2D::ReturnAsDenseMatrix, mtk::RobinBCDescriptor2D::ImposeOnLaplacianMatrix, mtk::Tools::EndUnitTestNo, mtk::Tools::Assert.
Referenced by main.
mtk::Real ScalarField(const mtk::Real &xx, const mtk::Real &yy)
Referenced by mtk::UniStgGrid1D::BindScalarField, mtk::UniStgGrid2D::BindScalarField, mtk::UniStgGrid3D::BindScalarField, TestImposeOnGrid.
mtk::Real HomogeneousDiricheletBC(const mtk::Real &xx, const mtk::Real &tt)
References mtk::kZero.
Referenced by TestImposeOnGrid.
void TestImposeOnGrid()
References mtk::Tools::BeginUnitTestNo, cc, mtk::UniStgGrid2D::BindScalarField, ScalarField, mtk::RobinBCDescriptor2D::set_west_condition, HomogeneousDiricheletBC, mtk::RobinBCDescriptor2D::set_east_condition, mtk::RobinBCDescriptor2D::set_south_condition, mtk::RobinBCDescriptor2D::set_north_condition, mtk::RobinBCDescriptor2D::ImposeOnGrid, mtk::UniStgGrid2D::WriteToFile, mtk::Tools::EndUnitTestNo, mtk::Tools::Assert.
Referenced by main.
int main()
References TestDefaultConstructorGetters, TestPushBackImposeOnLaplacianMatrix, TestImposeOnGrid.