mtk_uni_stg_grid_2d_test.cc
void TestDefaultConstructor()
References mtk::Tools::BeginUnitTestNo, mtk::Tools::EndUnitTestNo, mtk::Tools::Assert, mtk::UniStgGrid2D::delta_x, mtk::kZero, mtk::UniStgGrid2D::delta_y.
Referenced by main.
void TestConstructWithWestEastNumCellsXSouthNorthBndysNumCellsYOStreamOperator()
References mtk::Tools::BeginUnitTestNo, cc, mtk::Tools::EndUnitTestNo, mtk::Tools::Assert, mtk::UniStgGrid2D::delta_x, mtk::UniStgGrid2D::delta_y, mtk::kDefaultTolerance.
Referenced by main.
void TestGetters()
References mtk::Tools::BeginUnitTestNo, cc, mtk::UniStgGrid2D::west_bndy, mtk::UniStgGrid2D::east_bndy, mtk::UniStgGrid2D::num_cells_x, mtk::UniStgGrid2D::south_bndy, mtk::UniStgGrid2D::north_bndy, mtk::UniStgGrid2D::num_cells_y, mtk::Tools::EndUnitTestNo, mtk::Tools::Assert.
Referenced by main.
mtk::Real ScalarField(const mtk::Real &xx, const mtk::Real &yy)
Referenced by TestBindScalarFieldWriteToFile.
void TestBindScalarFieldWriteToFile()
References mtk::Tools::BeginUnitTestNo, cc, mtk::UniStgGrid2D::BindScalarField, ScalarField, mtk::UniStgGrid2D::WriteToFile, mtk::Tools::EndUnitTestNo.
Referenced by main.
mtk::Real VectorFieldPComponent(const mtk::Real &xx, const mtk::Real &yy)
Referenced by TestBindVectorField.
mtk::Real VectorFieldQComponent(const mtk::Real &xx, const mtk::Real &yy)
Referenced by mtk::UniStgGrid2D::BindVectorField, mtk::UniStgGrid3D::BindVectorField, TestBindVectorField.
void TestBindVectorField()
References mtk::Tools::BeginUnitTestNo, cc, mtk::VECTOR, mtk::UniStgGrid2D::BindVectorField, VectorFieldPComponent, VectorFieldQComponent, mtk::UniStgGrid2D::WriteToFile, mtk::Tools::EndUnitTestNo.
Referenced by main.
int main()
References TestDefaultConstructor, TestConstructWithWestEastNumCellsXSouthNorthBndysNumCellsYOStreamOperator, TestGetters, TestBindScalarFieldWriteToFile, TestBindVectorField.