mtk_lap_1d_test.cc
void TestDefaultConstructorFactoryMethodDefault()
References mtk::Tools::BeginUnitTestNo, mtk::Lap1D::ConstructLap1D, mtk::Tools::EndUnitTestNo, mtk::Tools::Assert.
Referenced by main.
void TestDefaultConstructorFactoryMethodFourthOrder()
References mtk::Tools::BeginUnitTestNo, mtk::Lap1D::ConstructLap1D, mtk::Tools::EndUnitTestNo, mtk::Tools::Assert.
Referenced by main.
void TestDefaultConstructorFactoryMethodSixthOrder()
References mtk::Tools::BeginUnitTestNo, mtk::Lap1D::ConstructLap1D, mtk::Tools::EndUnitTestNo, mtk::Tools::Assert.
Referenced by main.
void TestDefaultConstructorFactoryMethodEightOrderDefThreshold()
References mtk::Tools::BeginUnitTestNo, mtk::Lap1D::ConstructLap1D, mtk::Tools::EndUnitTestNo.
Referenced by main.
void TestDefaultConstructorFactoryMethodTenthOrderDefThreshold()
References mtk::Tools::BeginUnitTestNo, mtk::Lap1D::ConstructLap1D, mtk::Tools::EndUnitTestNo.
Referenced by main.
void TestDefaultConstructorFactoryMethodTwelfthOrderDefThreshold()
References mtk::Tools::BeginUnitTestNo, mtk::Lap1D::ConstructLap1D, mtk::Tools::EndUnitTestNo.
Referenced by main.
void TestReturnAsDenseMatrix()
References mtk::Tools::BeginUnitTestNo, mtk::Lap1D::ConstructLap1D, mtk::Lap1D::ReturnAsDenseMatrix, mtk::kDefaultTolerance, mtk::Tools::EndUnitTestNo, mtk::Tools::Assert.
Referenced by main.
int main()
References TestDefaultConstructorFactoryMethodDefault, TestDefaultConstructorFactoryMethodFourthOrder, TestDefaultConstructorFactoryMethodSixthOrder, TestDefaultConstructorFactoryMethodEightOrderDefThreshold, TestDefaultConstructorFactoryMethodTenthOrderDefThreshold, TestDefaultConstructorFactoryMethodTwelfthOrderDefThreshold, TestReturnAsDenseMatrix.