mtk_uni_stg_grid_3d_test.cc
void TestDefaultConstructor()
References mtk::Tools::BeginUnitTestNo, mtk::Tools::EndUnitTestNo, mtk::Tools::Assert, mtk::UniStgGrid3D::delta_x, mtk::kZero, mtk::UniStgGrid3D::delta_y, mtk::UniStgGrid3D::delta_z.
Referenced by main.
void TestConstructWithWestEastNumCellsXSouthNorthBndysNumCellsYOStreamOperator()
References mtk::Tools::BeginUnitTestNo, cc, mtk::Tools::EndUnitTestNo, mtk::Tools::Assert, mtk::UniStgGrid3D::delta_x, mtk::UniStgGrid3D::delta_y, mtk::kDefaultTolerance.
Referenced by main.
void TestGetters()
References mtk::Tools::BeginUnitTestNo, cc, mtk::UniStgGrid3D::west_bndy, mtk::UniStgGrid3D::east_bndy, mtk::UniStgGrid3D::num_cells_x, mtk::UniStgGrid3D::south_bndy, mtk::UniStgGrid3D::north_bndy, mtk::UniStgGrid3D::num_cells_y, mtk::UniStgGrid3D::bottom_bndy, mtk::UniStgGrid3D::top_bndy, mtk::UniStgGrid3D::num_cells_z, mtk::Tools::EndUnitTestNo, mtk::Tools::Assert.
Referenced by main.
mtk::Real ScalarField(const mtk::Real &xx, const mtk::Real &yy, const mtk::Real &zz)
Referenced by TestBindScalarFieldWriteToFile.
void TestBindScalarFieldWriteToFile()
References mtk::Tools::BeginUnitTestNo, cc, mtk::UniStgGrid3D::BindScalarField, ScalarField, mtk::UniStgGrid3D::WriteToFile, mtk::Tools::EndUnitTestNo.
Referenced by main.
int main()
References TestDefaultConstructor, TestConstructWithWestEastNumCellsXSouthNorthBndysNumCellsYOStreamOperator, TestGetters, TestBindScalarFieldWriteToFile.