mtk_matrix_test.cc
void TestDefaultConstructorGetters()
References mtk::Tools::BeginUnitTestNo, mtk::Matrix::encoded_operator, mtk::NOOP, mtk::Matrix::storage, mtk::DENSE, mtk::Matrix::ordering, mtk::ROW_MAJOR, mtk::Matrix::num_rows, mtk::Matrix::num_cols, mtk::Matrix::num_values, mtk::Matrix::leading_dimension, mtk::Matrix::num_zero, mtk::Matrix::num_non_zero, mtk::Matrix::num_null, mtk::Matrix::num_non_null, mtk::Matrix::num_low_diags, mtk::Matrix::num_upp_diags, mtk::Matrix::bandwidth, mtk::Matrix::abs_density, mtk::kZero, mtk::Matrix::rel_density, mtk::Matrix::abs_sparsity, mtk::Matrix::rel_sparsity, mtk::Tools::Assert, mtk::Tools::EndUnitTestNo.
Referenced by main.
void TestSettersGettersCopyConstructor()
References mtk::Tools::BeginUnitTestNo, mtk::Matrix::set_encoded_operator, mtk::GRADIENT, mtk::Matrix::set_storage, mtk::DENSE, mtk::Matrix::set_ordering, mtk::ROW_MAJOR, mtk::Matrix::set_num_rows, mtk::Matrix::set_num_cols, mtk::Matrix::set_num_low_diags, mtk::Matrix::set_num_upp_diags, mtk::Matrix::encoded_operator, mtk::Matrix::storage, mtk::Matrix::ordering, mtk::Matrix::num_rows, mtk::Matrix::num_cols, mtk::Matrix::num_values, mtk::Matrix::leading_dimension, mtk::Matrix::num_low_diags, mtk::Matrix::num_upp_diags, mtk::Matrix::bandwidth, mtk::Matrix::num_null, mtk::Matrix::num_non_null, mtk::Matrix::abs_density, mtk::kZero, mtk::Matrix::abs_sparsity, mtk::kOne, mtk::Matrix::num_zero, mtk::Matrix::num_non_zero, mtk::Matrix::rel_density, mtk::Matrix::rel_sparsity, mtk::Tools::Assert, mtk::Tools::EndUnitTestNo.
Referenced by main.
void TestIncreaseDecreaseNumNull()
References mtk::Tools::BeginUnitTestNo, mtk::Matrix::set_encoded_operator, mtk::DIVERGENCE, mtk::Matrix::set_storage, mtk::DENSE, mtk::Matrix::set_ordering, mtk::ROW_MAJOR, mtk::Matrix::set_num_rows, mtk::Matrix::set_num_cols, mtk::Matrix::encoded_operator, mtk::Matrix::storage, mtk::Matrix::ordering, mtk::Matrix::num_rows, mtk::Matrix::num_cols, mtk::Matrix::num_values, mtk::Matrix::leading_dimension, mtk::Matrix::num_null, mtk::Matrix::num_non_null, mtk::Matrix::abs_density, mtk::kZero, mtk::Matrix::abs_sparsity, mtk::kOne, mtk::Matrix::num_zero, mtk::Matrix::num_non_zero, mtk::Matrix::rel_density, mtk::Matrix::rel_sparsity, mtk::Matrix::DecreaseNumNull, mtk::kDefaultTolerance, mtk::Matrix::IncreaseNumNull, mtk::Tools::Assert, mtk::Tools::EndUnitTestNo.
Referenced by main.
void TestIncreaseDecreaseNumZero()
References mtk::Tools::BeginUnitTestNo, mtk::Matrix::set_encoded_operator, mtk::DIVERGENCE, mtk::Matrix::set_storage, mtk::DENSE, mtk::Matrix::set_ordering, mtk::ROW_MAJOR, mtk::Matrix::set_num_rows, mtk::Matrix::set_num_cols, mtk::Matrix::encoded_operator, mtk::Matrix::storage, mtk::Matrix::ordering, mtk::Matrix::num_rows, mtk::Matrix::num_cols, mtk::Matrix::num_values, mtk::Matrix::leading_dimension, mtk::Matrix::num_null, mtk::Matrix::num_non_null, mtk::Matrix::abs_density, mtk::kZero, mtk::Matrix::abs_sparsity, mtk::kOne, mtk::Matrix::num_zero, mtk::Matrix::num_non_zero, mtk::Matrix::rel_density, mtk::Matrix::rel_sparsity, mtk::Matrix::IncreaseNumZero, mtk::kDefaultTolerance, mtk::Matrix::DecreaseNumZero, mtk::Tools::Assert, mtk::Tools::EndUnitTestNo.
Referenced by main.
int main(int argc, char *argv[])
References TestDefaultConstructorGetters, TestSettersGettersCopyConstructor, TestIncreaseDecreaseNumNull, TestIncreaseDecreaseNumZero.