mtk
MatrixStorage
Dense matrices, implemented as a 1D array: DenseMatrix.
MatrixOrdering
Row-major ordering (C/C++).
FieldNature
Scalar-valued field.
DirInterp
Interpolations places scalar on vectors' location.
mtk::CoefficientFunction0D)(const Real &tt)
A function of a BC coefficient evaluated on a 0D domain and time.
This definition implies that, for now, coefficients will depend on space and time, thus no extra parameters can influence their behavior. We will fix this soon enough.
mtk::CoefficientFunction1D)(const Real &xx, const Real &tt)
A function of a BC coefficient evaluated on a 1D domain and time.
mtk::CoefficientFunction2D)(const Real &xx, const Real &yy, const Real &tt)
A function of a BC coefficient evaluated on a 2D domain and time.
mtk::Real
Users can simply change this to build a double- or single-precision MTK.
Defined as double if MTK_PRECISION_DOUBLE is defined on Makefile.inc.
mtk::kZero
MTK's zero defined according to selective compilation.
Declared as double if MTK_PRECISION_DOUBLE is defined on Makefile.inc.
Referenced by mtk::BLASAdapter::RealDenseMM, mtk::BLASAdapter::RealDenseSM, mtk::DenseMatrix::operator=, mtk::DenseMatrix::DenseMatrix, mtk::DenseMatrix::Transpose, mtk::DenseMatrix::OrderRowMajor, mtk::DenseMatrix::OrderColMajor, mtk::Div1D::ConstructDiv1D, mtk::Div1D::ReturnAsDenseMatrix, mtk::Div1D::ReturnAsDimensionlessDenseMatrix, mtk::Div1D::ComputeStencilInteriorGrid, mtk::Div1D::ComputeRationalBasisNullSpace, mtk::Div1D::ComputePreliminaryApproximations, mtk::Div1D::ComputeWeights, mtk::Div1D::ComputeStencilBoundaryGrid, mtk::Div1D::AssembleOperator, mtk::GLPKAdapter::SolveSimplexAndCompare, mtk::Grad1D::ConstructGrad1D, mtk::Grad1D::ReturnAsDenseMatrix, mtk::Grad1D::ReturnAsDimensionlessDenseMatrix, mtk::Grad1D::ComputeStencilInteriorGrid, mtk::Grad1D::ComputeRationalBasisNullSpace, mtk::Grad1D::ComputePreliminaryApproximations, mtk::Grad1D::ComputeWeights, mtk::Grad1D::ComputeStencilBoundaryGrid, mtk::Grad1D::AssembleOperator, mtk::Interp1D::ConstructInterp1D, mtk::Lap1D::ConstructLap1D, mtk::LAPACKAdapter::QRFactorDenseMatrix, mtk::LAPACKAdapter::SolveRectangularDenseSystem, mtk::UniStgGrid1D::UniStgGrid1D, mtk::UniStgGrid2D::UniStgGrid2D, mtk::UniStgGrid2D::WriteToFile, mtk::UniStgGrid3D::UniStgGrid3D.
mtk::kOne
MTK's one defined according to selective compilation.
Declared as double if MTK_PRECISION_DOUBLE is defined on Makefile.inc.
Referenced by mtk::BLASAdapter::RelNorm2Error, mtk::BLASAdapter::RealDenseMM, mtk::DenseMatrix::DenseMatrix, mtk::Div1D::ReturnAsDenseMatrix, mtk::Div1D::ComputeStencilInteriorGrid, mtk::Div1D::ComputeRationalBasisNullSpace, mtk::Div1D::ComputePreliminaryApproximations, mtk::Div1D::ComputeWeights, mtk::Grad1D::ReturnAsDenseMatrix, mtk::Grad1D::ComputeStencilInteriorGrid, mtk::Grad1D::ComputeRationalBasisNullSpace, mtk::Grad1D::ComputePreliminaryApproximations, mtk::Grad1D::ComputeWeights, mtk::Interp1D::ConstructInterp1D, mtk::Interp1D::ReturnAsDenseMatrix, mtk::Lap1D::ReturnAsDenseMatrix, mtk::RobinBCDescriptor1D::ImposeOnLaplacianMatrix, mtk::RobinBCDescriptor2D::ImposeOnWestBoundaryNoSpace, mtk::RobinBCDescriptor2D::ImposeOnEastBoundaryNoSpace.
mtk::kTwo
MTK's two defined according to selective compilation.
Declared as double if MTK_PRECISION_DOUBLE is defined on Makefile.inc.
Referenced by mtk::RobinBCDescriptor2D::ImposeOnSouthBoundaryNoSpace, mtk::RobinBCDescriptor2D::ImposeOnNorthBoundaryNoSpace, mtk::RobinBCDescriptor2D::ImposeOnWestBoundaryNoSpace, mtk::RobinBCDescriptor2D::ImposeOnEastBoundaryNoSpace, mtk::RobinBCDescriptor2D::ImposeOnGrid, mtk::UniStgGrid3D::BindScalarField.
mtk::kDefaultTolerance
Considered tolerance for comparisons in numerical methods.
Declared as double if MTK_PRECISION_DOUBLE is defined on Makefile.inc.
Referenced by mtk::DenseMatrix::operator==.
mtk::kDefaultMimeticThreshold
Default tolerance for higher-order mimetic operators.
Declared as double if MTK_PRECISION_DOUBLE is defined on Makefile.inc.
mtk::kDefaultOrderAccuracy
Default order of accuracy for mimetic operators.
Referenced by mtk::Div1D::AssembleOperator, operator<<, mtk::Grad1D::AssembleOperator.
mtk::kCriticalOrderAccuracyGrad
At this order (and higher) we must use the CBSA to construct gradients.
Referenced by mtk::Grad1D::ConstructGrad1D, mtk::Grad1D::ComputeWeights.
mtk::kCriticalOrderAccuracyDiv
At this order (and higher) we must use the CBSA to construct divergences.
Referenced by mtk::Div1D::ConstructDiv1D, mtk::Div1D::ComputeWeights, mtk::Lap1D::ConstructLap1D.
float mtk::snrm2_(int *n, float *x, int *incx)
Referenced by mtk::BLASAdapter::RealNRM2.
void mtk::saxpy_(int *n, float *sa, float *sx, int *incx, float *sy, int *incy)
Referenced by mtk::BLASAdapter::RealAXPY.
void mtk::sgemv_(char *trans, int *m, int *n, float *alpha, float *a, int *lda, float *x, int *incx, float *beta, float *y, int *incy)
Referenced by mtk::BLASAdapter::RealDenseMV.
void mtk::sgemm_(char *transa, char *transb, int *m, int *n, int *k, double *alpha, double *a, int *lda, double *b, aamm int *ldb, double *beta, double *c, int *ldc)
Referenced by mtk::BLASAdapter::RealDenseMM, mtk::BLASAdapter::RealDenseSM.
std::ostream& mtk::operator<<(std::ostream &stream, mtk::DenseMatrix &in)
References mtk::DenseMatrix::matrix_properties_, mtk::Matrix::num_rows, mtk::Matrix::num_cols, mtk::Matrix::ordering, COL_MAJOR, mtk::DenseMatrix::data_.
std::ostream& mtk::operator<<(std::ostream &stream, mtk::Div1D &in)
References mtk::Div1D::divergence_, mtk::Div1D::order_accuracy_, mtk::Div1D::dim_null_, mtk::Div1D::num_bndy_coeffs_, mtk::Div1D::sums_rows_mim_bndy_.
std::ostream& mtk::operator<<(std::ostream &stream, mtk::Grad1D &in)
References mtk::Grad1D::gradient_, mtk::Grad1D::order_accuracy_, kDefaultOrderAccuracy, mtk::Grad1D::num_bndy_approxs_, mtk::Grad1D::num_bndy_coeffs_, mtk::Grad1D::sums_rows_mim_bndy_.
std::ostream& mtk::operator<<(std::ostream &stream, mtk::Interp1D &in)
References mtk::Interp1D::order_accuracy_, mtk::Interp1D::coeffs_interior_.
std::ostream& mtk::operator<<(std::ostream &stream, mtk::Lap1D &in)
References mtk::Lap1D::laplacian_, mtk::Lap1D::order_accuracy_, mtk::Lap1D::sums_rows_mim_bndy_.
void mtk::sgesv_(int *n, int *nrhs, Real *a, int *lda, int *ipiv, Real *b, int *ldb, int *info)
void mtk::sgels_(char *trans, int *m, int *n, int *nrhs, Real *a, int *lda, Real *b, int *ldb, Real *work, int *lwork, int *info)
Single-precision GEneral matrix Least Squares solver.
SGELS solves overdetermined or underdetermined real linear systems involving an M-by-N matrix A, or its transpose, using a QR or LQ factorization of A. It is assumed that A has full rank.The following options are provided: If TRANS = 'N' and m >= n: find the least squares solution of an overdetermined system, i.e., solve the least squares problem minimize || B - A*X ||. If TRANS = 'N' and m < n: find the minimum norm solution of an underdetermined system A * X = B.If TRANS = 'T' and m >= n: find the minimum norm solution of an undetermined system A**T * X = B.If TRANS = 'T' and m < n: find the least squares solution of an overdetermined system, i.e., solve the least squares problem minimize || B - A**T * X ||. Several right hand side vectors b and solution vectors x can be handled in a single call; they are stored as the columns of the M-by-NRHS right hand side matrix B and the N-by-NRHS solution matrix X.http://www.math.utah.edu/software/lapack/lapack-s/sgels.html trans Am I giving the transpose of the matrix? m The number of rows of the matrix a. m >= 0. n The number of columns of the matrix a. n >= 0. nrhs The number of right-hand sides. a On entry, the m-by-n matrix a. lda The leading dimension of a. lda >= max(1,m). b On entry, matrix b of right-hand side vectors. ldb The leading dimension of b. ldb >= max(1,m,n). work On exit, if info = 0, work(1) is optimal lwork. lwork The dimension of the array work. info If info = 0, then successful exit.
Referenced by mtk::LAPACKAdapter::SolveRectangularDenseSystem.
void mtk::sgeqrf_(int *m, int *n, Real *a, int *lda, Real *tau, Real *work, int *lwork, int *info)
Single-precision GEneral matrix QR Factorization.
Single-Precision Orthogonal Make Q from QR: dormqr_ overwrites the general real M-by-N matrix C with (Table 1): SIDE = 'L' SIDE = 'R' TRANS = 'N': Q * C C * Q TRANS = 'T': Q**T * C C * Q**Twhere Q is a real orthogonal matrix defined as the product of k elementary reflectors Q = H(1) H(2) . . . H(k) as returned by SGEQRF. Q is of order M if SIDE = 'L' and of order N if SIDE = 'R'.http://www.netlib.org/lapack/explore-html/df/d97/sgeqrf_8f.html m The number of columns of the matrix a. n >= 0. n The number of columns of the matrix a. n >= 0. a On entry, the n-by-n matrix a. lda Leading dimension matrix. LDA >= max(1,M). tau Scalars from elementary reflectors. min(M,N). work Workspace. info = 0, work(1) is optimal lwork. lwork The dimension of work. lwork >= max(1,n). info info = 0: successful exit.
void mtk::sormqr_(char *side, char *trans, int *m, int *n, int *k, Real *a, int *lda, Real *tau, Real *c, int *ldc, Real *work, int *lwork, int *info)
Single-precision Orthogonal Matrix from QR factorization.
Single-Precision Orthogonal Make Q from QR: sormqr_ overwrites the general real M-by-N matrix C with (Table 1): SIDE = 'L' SIDE = 'R' TRANS = 'N': Q * C C * Q TRANS = 'T': Q**T * C C * Q**Twhere Q is a real orthogonal matrix defined as the product of k elementary reflectors Q = H(1) H(2) . . . H(k) as returned by SGEQRF. Q is of order M if SIDE = 'L' and of order N if SIDE = 'R'.http://www.netlib.org/lapack/explore-html/d0/d98/sormqr_8f_source.html side See Table 1 above. trans See Table 1 above. m Number of rows of the C matrix. n Number of columns of the C matrix. k Number of reflectors. a The matrix containing the reflectors. lda The dimension of work. lwork >= max(1,n). tau Scalar factors of the elementary reflectors. c Output matrix. ldc Leading dimension of the output matrix. work Workspace. info = 0, work(1) optimal lwork. lwork The dimension of work. info info = 0: successful exit.
std::ostream& mtk::operator<<(std::ostream &stream, mtk::UniStgGrid1D &in)
References mtk::UniStgGrid1D::west_bndy_x_, mtk::UniStgGrid1D::num_cells_x_, mtk::UniStgGrid1D::east_bndy_x_, mtk::UniStgGrid1D::discrete_domain_x_, mtk::UniStgGrid1D::nature_, SCALAR, mtk::UniStgGrid1D::discrete_field_.
std::ostream& mtk::operator<<(std::ostream &stream, mtk::UniStgGrid2D &in)
References mtk::UniStgGrid2D::west_bndy_, mtk::UniStgGrid2D::num_cells_x_, mtk::UniStgGrid2D::east_bndy_, mtk::UniStgGrid2D::south_bndy_, mtk::UniStgGrid2D::num_cells_y_, mtk::UniStgGrid2D::north_bndy_, mtk::UniStgGrid2D::discrete_domain_x_, mtk::UniStgGrid2D::discrete_domain_y_, mtk::UniStgGrid2D::nature_, SCALAR, mtk::UniStgGrid2D::discrete_field_.
std::ostream& mtk::operator<<(std::ostream &stream, mtk::UniStgGrid3D &in)
References mtk::UniStgGrid3D::west_bndy_, mtk::UniStgGrid3D::num_cells_x_, mtk::UniStgGrid3D::east_bndy_, mtk::UniStgGrid3D::south_bndy_, mtk::UniStgGrid3D::num_cells_y_, mtk::UniStgGrid3D::north_bndy_, mtk::UniStgGrid3D::bottom_bndy_, mtk::UniStgGrid3D::num_cells_z_, mtk::UniStgGrid3D::top_bndy_, mtk::UniStgGrid3D::discrete_domain_x_, mtk::UniStgGrid3D::discrete_domain_y_, mtk::UniStgGrid3D::discrete_domain_z_, mtk::UniStgGrid3D::nature_, SCALAR, mtk::UniStgGrid3D::discrete_field_.